/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ApprovalRequest service. Represents a row in the &quot;EDC_ApprovalRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.ApprovalRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.ApprovalRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApprovalRequest
 * @generated
 */
@ProviderType
public interface ApprovalRequestModel
	extends BaseModel<ApprovalRequest>, ShardedModel, TrashedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a approval request model instance should use the {@link ApprovalRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this approval request.
	 *
	 * @return the primary key of this approval request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this approval request.
	 *
	 * @param primaryKey the primary key of this approval request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this approval request.
	 *
	 * @return the uuid of this approval request
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this approval request.
	 *
	 * @param uuid the uuid of this approval request
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the approval request ID of this approval request.
	 *
	 * @return the approval request ID of this approval request
	 */
	public long getApprovalRequestId();

	/**
	 * Sets the approval request ID of this approval request.
	 *
	 * @param approvalRequestId the approval request ID of this approval request
	 */
	public void setApprovalRequestId(long approvalRequestId);

	/**
	 * Returns the group ID of this approval request.
	 *
	 * @return the group ID of this approval request
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this approval request.
	 *
	 * @param groupId the group ID of this approval request
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this approval request.
	 *
	 * @return the company ID of this approval request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this approval request.
	 *
	 * @param companyId the company ID of this approval request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this approval request.
	 *
	 * @return the project ID of this approval request
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this approval request.
	 *
	 * @param projectId the project ID of this approval request
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the status of this approval request.
	 *
	 * @return the status of this approval request
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this approval request.
	 *
	 * @param status the status of this approval request
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this approval request.
	 *
	 * @return the status by user ID of this approval request
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this approval request.
	 *
	 * @param statusByUserId the status by user ID of this approval request
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this approval request.
	 *
	 * @return the status by user uuid of this approval request
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this approval request.
	 *
	 * @param statusByUserUuid the status by user uuid of this approval request
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this approval request.
	 *
	 * @return the status by user name of this approval request
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this approval request.
	 *
	 * @param statusByUserName the status by user name of this approval request
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this approval request.
	 *
	 * @return the status date of this approval request
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this approval request.
	 *
	 * @param statusDate the status date of this approval request
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the request user ID of this approval request.
	 *
	 * @return the request user ID of this approval request
	 */
	public long getRequestUserId();

	/**
	 * Sets the request user ID of this approval request.
	 *
	 * @param requestUserId the request user ID of this approval request
	 */
	public void setRequestUserId(long requestUserId);

	/**
	 * Returns the request user uuid of this approval request.
	 *
	 * @return the request user uuid of this approval request
	 */
	public String getRequestUserUuid();

	/**
	 * Sets the request user uuid of this approval request.
	 *
	 * @param requestUserUuid the request user uuid of this approval request
	 */
	public void setRequestUserUuid(String requestUserUuid);

	/**
	 * Returns the request user name of this approval request.
	 *
	 * @return the request user name of this approval request
	 */
	@AutoEscape
	public String getRequestUserName();

	/**
	 * Sets the request user name of this approval request.
	 *
	 * @param requestUserName the request user name of this approval request
	 */
	public void setRequestUserName(String requestUserName);

	/**
	 * Returns the request date of this approval request.
	 *
	 * @return the request date of this approval request
	 */
	public Date getRequestDate();

	/**
	 * Sets the request date of this approval request.
	 *
	 * @param requestDate the request date of this approval request
	 */
	public void setRequestDate(Date requestDate);

	/**
	 * Returns the target users ID of this approval request.
	 *
	 * @return the target users ID of this approval request
	 */
	@AutoEscape
	public String getTargetUsersId();

	/**
	 * Sets the target users ID of this approval request.
	 *
	 * @param targetUsersId the target users ID of this approval request
	 */
	public void setTargetUsersId(String targetUsersId);

	/**
	 * Returns the class name of this approval request.
	 *
	 * @return the class name of this approval request
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this approval request.
	 *
	 * @param className the class name of this approval request
	 */
	public void setClassName(String className);

	/**
	 * Returns the class pk of this approval request.
	 *
	 * @return the class pk of this approval request
	 */
	public long getClassPK();

	/**
	 * Sets the class pk of this approval request.
	 *
	 * @param classPK the class pk of this approval request
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the trash entry created when this approval request was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this approval request.
	 *
	 * @return the trash entry created when this approval request was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this approval request.
	 *
	 * @return the class primary key of the trash entry for this approval request
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this approval request.
	 *
	 * @return the trash handler for this approval request
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this approval request is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this approval request is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this approval request is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this approval request is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this approval request is approved.
	 *
	 * @return <code>true</code> if this approval request is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this approval request is denied.
	 *
	 * @return <code>true</code> if this approval request is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this approval request is a draft.
	 *
	 * @return <code>true</code> if this approval request is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this approval request is expired.
	 *
	 * @return <code>true</code> if this approval request is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this approval request is inactive.
	 *
	 * @return <code>true</code> if this approval request is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this approval request is incomplete.
	 *
	 * @return <code>true</code> if this approval request is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this approval request is pending.
	 *
	 * @return <code>true</code> if this approval request is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this approval request is scheduled.
	 *
	 * @return <code>true</code> if this approval request is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}