/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AssignInstitutionRole service. Represents a row in the &quot;EDC_AssignInstitutionRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.AssignInstitutionRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.AssignInstitutionRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssignInstitutionRole
 * @generated
 */
@ProviderType
public interface AssignInstitutionRoleModel
	extends BaseModel<AssignInstitutionRole>, ShardedModel, StagedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assign institution role model instance should use the {@link AssignInstitutionRole} interface instead.
	 */

	/**
	 * Returns the primary key of this assign institution role.
	 *
	 * @return the primary key of this assign institution role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this assign institution role.
	 *
	 * @param primaryKey the primary key of this assign institution role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this assign institution role.
	 *
	 * @return the uuid of this assign institution role
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this assign institution role.
	 *
	 * @param uuid the uuid of this assign institution role
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the institution role ID of this assign institution role.
	 *
	 * @return the institution role ID of this assign institution role
	 */
	public long getInstitutionRoleId();

	/**
	 * Sets the institution role ID of this assign institution role.
	 *
	 * @param institutionRoleId the institution role ID of this assign institution role
	 */
	public void setInstitutionRoleId(long institutionRoleId);

	/**
	 * Returns the company ID of this assign institution role.
	 *
	 * @return the company ID of this assign institution role
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this assign institution role.
	 *
	 * @param companyId the company ID of this assign institution role
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this assign institution role.
	 *
	 * @return the group ID of this assign institution role
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this assign institution role.
	 *
	 * @param groupId the group ID of this assign institution role
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the institution ID of this assign institution role.
	 *
	 * @return the institution ID of this assign institution role
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this assign institution role.
	 *
	 * @param institutionId the institution ID of this assign institution role
	 */
	public void setInstitutionId(long institutionId);

	/**
	 * Returns the researcher ID of this assign institution role.
	 *
	 * @return the researcher ID of this assign institution role
	 */
	public long getResearcherId();

	/**
	 * Sets the researcher ID of this assign institution role.
	 *
	 * @param researcherId the researcher ID of this assign institution role
	 */
	public void setResearcherId(long researcherId);

	/**
	 * Returns the target user ID of this assign institution role.
	 *
	 * @return the target user ID of this assign institution role
	 */
	public long getTargetUserId();

	/**
	 * Sets the target user ID of this assign institution role.
	 *
	 * @param targetUserId the target user ID of this assign institution role
	 */
	public void setTargetUserId(long targetUserId);

	/**
	 * Returns the target user uuid of this assign institution role.
	 *
	 * @return the target user uuid of this assign institution role
	 */
	public String getTargetUserUuid();

	/**
	 * Sets the target user uuid of this assign institution role.
	 *
	 * @param targetUserUuid the target user uuid of this assign institution role
	 */
	public void setTargetUserUuid(String targetUserUuid);

	/**
	 * Returns the role name of this assign institution role.
	 *
	 * @return the role name of this assign institution role
	 */
	@AutoEscape
	public String getRoleName();

	/**
	 * Sets the role name of this assign institution role.
	 *
	 * @param roleName the role name of this assign institution role
	 */
	public void setRoleName(String roleName);

	/**
	 * Returns the active of this assign institution role.
	 *
	 * @return the active of this assign institution role
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this assign institution role is active.
	 *
	 * @return <code>true</code> if this assign institution role is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this assign institution role is active.
	 *
	 * @param active the active of this assign institution role
	 */
	public void setActive(boolean active);

	/**
	 * Returns the create date of this assign institution role.
	 *
	 * @return the create date of this assign institution role
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this assign institution role.
	 *
	 * @param createDate the create date of this assign institution role
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this assign institution role.
	 *
	 * @return the modified date of this assign institution role
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this assign institution role.
	 *
	 * @param modifiedDate the modified date of this assign institution role
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this assign institution role.
	 *
	 * @return the created by of this assign institution role
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this assign institution role.
	 *
	 * @param createdBy the created by of this assign institution role
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this assign institution role.
	 *
	 * @return the modified by of this assign institution role
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this assign institution role.
	 *
	 * @param modifiedBy the modified by of this assign institution role
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the status of this assign institution role.
	 *
	 * @return the status of this assign institution role
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this assign institution role was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this assign institution role.
	 *
	 * @return the trash entry created when this assign institution role was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this assign institution role.
	 *
	 * @return the class primary key of the trash entry for this assign institution role
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this assign institution role.
	 *
	 * @return the trash handler for this assign institution role
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this assign institution role is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this assign institution role is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this assign institution role is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this assign institution role is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}