/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AssignProjectScope service. Represents a row in the &quot;EDC_AssignProjectScope&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.AssignProjectScopeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.AssignProjectScopeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssignProjectScope
 * @generated
 */
@ProviderType
public interface AssignProjectScopeModel
	extends BaseModel<AssignProjectScope>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assign project scope model instance should use the {@link AssignProjectScope} interface instead.
	 */

	/**
	 * Returns the primary key of this assign project scope.
	 *
	 * @return the primary key of this assign project scope
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this assign project scope.
	 *
	 * @param primaryKey the primary key of this assign project scope
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this assign project scope.
	 *
	 * @return the uuid of this assign project scope
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this assign project scope.
	 *
	 * @param uuid the uuid of this assign project scope
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the project scope ID of this assign project scope.
	 *
	 * @return the project scope ID of this assign project scope
	 */
	public long getProjectScopeId();

	/**
	 * Sets the project scope ID of this assign project scope.
	 *
	 * @param projectScopeId the project scope ID of this assign project scope
	 */
	public void setProjectScopeId(long projectScopeId);

	/**
	 * Returns the company ID of this assign project scope.
	 *
	 * @return the company ID of this assign project scope
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this assign project scope.
	 *
	 * @param companyId the company ID of this assign project scope
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this assign project scope.
	 *
	 * @return the group ID of this assign project scope
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this assign project scope.
	 *
	 * @param groupId the group ID of this assign project scope
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the institution ID of this assign project scope.
	 *
	 * @return the institution ID of this assign project scope
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this assign project scope.
	 *
	 * @param institutionId the institution ID of this assign project scope
	 */
	public void setInstitutionId(long institutionId);

	/**
	 * Returns the researcher ID of this assign project scope.
	 *
	 * @return the researcher ID of this assign project scope
	 */
	public long getResearcherId();

	/**
	 * Sets the researcher ID of this assign project scope.
	 *
	 * @param researcherId the researcher ID of this assign project scope
	 */
	public void setResearcherId(long researcherId);

	/**
	 * Returns the project ID of this assign project scope.
	 *
	 * @return the project ID of this assign project scope
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this assign project scope.
	 *
	 * @param projectId the project ID of this assign project scope
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the target user ID of this assign project scope.
	 *
	 * @return the target user ID of this assign project scope
	 */
	public long getTargetUserId();

	/**
	 * Sets the target user ID of this assign project scope.
	 *
	 * @param targetUserId the target user ID of this assign project scope
	 */
	public void setTargetUserId(long targetUserId);

	/**
	 * Returns the target user uuid of this assign project scope.
	 *
	 * @return the target user uuid of this assign project scope
	 */
	public String getTargetUserUuid();

	/**
	 * Sets the target user uuid of this assign project scope.
	 *
	 * @param targetUserUuid the target user uuid of this assign project scope
	 */
	public void setTargetUserUuid(String targetUserUuid);

	/**
	 * Returns the scope role of this assign project scope.
	 *
	 * @return the scope role of this assign project scope
	 */
	@AutoEscape
	public String getScopeRole();

	/**
	 * Sets the scope role of this assign project scope.
	 *
	 * @param scopeRole the scope role of this assign project scope
	 */
	public void setScopeRole(String scopeRole);

	/**
	 * Returns the active of this assign project scope.
	 *
	 * @return the active of this assign project scope
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this assign project scope is active.
	 *
	 * @return <code>true</code> if this assign project scope is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this assign project scope is active.
	 *
	 * @param active the active of this assign project scope
	 */
	public void setActive(boolean active);

	/**
	 * Returns the create date of this assign project scope.
	 *
	 * @return the create date of this assign project scope
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this assign project scope.
	 *
	 * @param createDate the create date of this assign project scope
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this assign project scope.
	 *
	 * @return the modified date of this assign project scope
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this assign project scope.
	 *
	 * @param modifiedDate the modified date of this assign project scope
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this assign project scope.
	 *
	 * @return the created by of this assign project scope
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this assign project scope.
	 *
	 * @param createdBy the created by of this assign project scope
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this assign project scope.
	 *
	 * @return the modified by of this assign project scope
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this assign project scope.
	 *
	 * @param modifiedBy the modified by of this assign project scope
	 */
	public void setModifiedBy(long modifiedBy);

}