/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EdcLock service. Represents a row in the &quot;EDC_EdcLock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.EdcLockModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.EdcLockImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcLock
 * @generated
 */
@ProviderType
public interface EdcLockModel
	extends AttachedModel, BaseModel<EdcLock>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a edc lock model instance should use the {@link EdcLock} interface instead.
	 */

	/**
	 * Returns the primary key of this edc lock.
	 *
	 * @return the primary key of this edc lock
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this edc lock.
	 *
	 * @param primaryKey the primary key of this edc lock
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this edc lock.
	 *
	 * @return the uuid of this edc lock
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this edc lock.
	 *
	 * @param uuid the uuid of this edc lock
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the lock ID of this edc lock.
	 *
	 * @return the lock ID of this edc lock
	 */
	public long getLockId();

	/**
	 * Sets the lock ID of this edc lock.
	 *
	 * @param lockId the lock ID of this edc lock
	 */
	public void setLockId(long lockId);

	/**
	 * Returns the company ID of this edc lock.
	 *
	 * @return the company ID of this edc lock
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this edc lock.
	 *
	 * @param companyId the company ID of this edc lock
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this edc lock.
	 *
	 * @return the group ID of this edc lock
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this edc lock.
	 *
	 * @param groupId the group ID of this edc lock
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the project ID of this edc lock.
	 *
	 * @return the project ID of this edc lock
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this edc lock.
	 *
	 * @param projectId the project ID of this edc lock
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the fully qualified class name of this edc lock.
	 *
	 * @return the fully qualified class name of this edc lock
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this edc lock.
	 *
	 * @return the class name ID of this edc lock
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this edc lock.
	 *
	 * @param classNameId the class name ID of this edc lock
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this edc lock.
	 *
	 * @return the class pk of this edc lock
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this edc lock.
	 *
	 * @param classPK the class pk of this edc lock
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the lock type of this edc lock.
	 *
	 * @return the lock type of this edc lock
	 */
	@AutoEscape
	public String getLockType();

	/**
	 * Sets the lock type of this edc lock.
	 *
	 * @param lockType the lock type of this edc lock
	 */
	public void setLockType(String lockType);

	/**
	 * Returns the user ID of this edc lock.
	 *
	 * @return the user ID of this edc lock
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this edc lock.
	 *
	 * @param userId the user ID of this edc lock
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this edc lock.
	 *
	 * @return the user uuid of this edc lock
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this edc lock.
	 *
	 * @param userUuid the user uuid of this edc lock
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this edc lock.
	 *
	 * @return the user name of this edc lock
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this edc lock.
	 *
	 * @param userName the user name of this edc lock
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this edc lock.
	 *
	 * @return the create date of this edc lock
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this edc lock.
	 *
	 * @param createDate the create date of this edc lock
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this edc lock.
	 *
	 * @return the modified date of this edc lock
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this edc lock.
	 *
	 * @param modifiedDate the modified date of this edc lock
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the comment of this edc lock.
	 *
	 * @return the comment of this edc lock
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this edc lock.
	 *
	 * @param comment the comment of this edc lock
	 */
	public void setComment(String comment);

}