/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EdcPermissionRole service. Represents a row in the &quot;EDC_EdcPermissionRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.EdcPermissionRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.EdcPermissionRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcPermissionRole
 * @generated
 */
@ProviderType
public interface EdcPermissionRoleModel
	extends BaseModel<EdcPermissionRole>, ShardedModel, StagedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a edc permission role model instance should use the {@link EdcPermissionRole} interface instead.
	 */

	/**
	 * Returns the primary key of this edc permission role.
	 *
	 * @return the primary key of this edc permission role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this edc permission role.
	 *
	 * @param primaryKey the primary key of this edc permission role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this edc permission role.
	 *
	 * @return the uuid of this edc permission role
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this edc permission role.
	 *
	 * @param uuid the uuid of this edc permission role
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the permission role ID of this edc permission role.
	 *
	 * @return the permission role ID of this edc permission role
	 */
	public long getPermissionRoleId();

	/**
	 * Sets the permission role ID of this edc permission role.
	 *
	 * @param permissionRoleId the permission role ID of this edc permission role
	 */
	public void setPermissionRoleId(long permissionRoleId);

	/**
	 * Returns the company ID of this edc permission role.
	 *
	 * @return the company ID of this edc permission role
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this edc permission role.
	 *
	 * @param companyId the company ID of this edc permission role
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this edc permission role.
	 *
	 * @return the group ID of this edc permission role
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this edc permission role.
	 *
	 * @param groupId the group ID of this edc permission role
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the project ID of this edc permission role.
	 *
	 * @return the project ID of this edc permission role
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this edc permission role.
	 *
	 * @param projectId the project ID of this edc permission role
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the actor group of this edc permission role.
	 *
	 * @return the actor group of this edc permission role
	 */
	public long getActorGroup();

	/**
	 * Sets the actor group of this edc permission role.
	 *
	 * @param actorGroup the actor group of this edc permission role
	 */
	public void setActorGroup(long actorGroup);

	/**
	 * Returns the actor ID of this edc permission role.
	 *
	 * @return the actor ID of this edc permission role
	 */
	public long getActorId();

	/**
	 * Sets the actor ID of this edc permission role.
	 *
	 * @param actorId the actor ID of this edc permission role
	 */
	public void setActorId(long actorId);

	/**
	 * Returns the role name of this edc permission role.
	 *
	 * @return the role name of this edc permission role
	 */
	@AutoEscape
	public String getRoleName();

	/**
	 * Sets the role name of this edc permission role.
	 *
	 * @param roleName the role name of this edc permission role
	 */
	public void setRoleName(String roleName);

	/**
	 * Returns the active of this edc permission role.
	 *
	 * @return the active of this edc permission role
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this edc permission role is active.
	 *
	 * @return <code>true</code> if this edc permission role is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this edc permission role is active.
	 *
	 * @param active the active of this edc permission role
	 */
	public void setActive(boolean active);

	/**
	 * Returns the from date of this edc permission role.
	 *
	 * @return the from date of this edc permission role
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this edc permission role.
	 *
	 * @param fromDate the from date of this edc permission role
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this edc permission role.
	 *
	 * @return the to date of this edc permission role
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this edc permission role.
	 *
	 * @param toDate the to date of this edc permission role
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the create date of this edc permission role.
	 *
	 * @return the create date of this edc permission role
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this edc permission role.
	 *
	 * @param createDate the create date of this edc permission role
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this edc permission role.
	 *
	 * @return the modified date of this edc permission role
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this edc permission role.
	 *
	 * @param modifiedDate the modified date of this edc permission role
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this edc permission role.
	 *
	 * @return the created by of this edc permission role
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this edc permission role.
	 *
	 * @param createdBy the created by of this edc permission role
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this edc permission role.
	 *
	 * @return the modified by of this edc permission role
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this edc permission role.
	 *
	 * @param modifiedBy the modified by of this edc permission role
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the status of this edc permission role.
	 *
	 * @return the status of this edc permission role
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this edc permission role was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this edc permission role.
	 *
	 * @return the trash entry created when this edc permission role was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this edc permission role.
	 *
	 * @return the class primary key of the trash entry for this edc permission role
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this edc permission role.
	 *
	 * @return the trash handler for this edc permission role
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this edc permission role is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this edc permission role is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this edc permission role is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this edc permission role is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}