/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EdcPermissionScopeAudit service. Represents a row in the &quot;EDC_EdcPermissionScopeAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeAuditModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeAuditImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcPermissionScopeAudit
 * @generated
 */
@ProviderType
public interface EdcPermissionScopeAuditModel
	extends BaseModel<EdcPermissionScopeAudit>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a edc permission scope audit model instance should use the {@link EdcPermissionScopeAudit} interface instead.
	 */

	/**
	 * Returns the primary key of this edc permission scope audit.
	 *
	 * @return the primary key of this edc permission scope audit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this edc permission scope audit.
	 *
	 * @param primaryKey the primary key of this edc permission scope audit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this edc permission scope audit.
	 *
	 * @return the uuid of this edc permission scope audit
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this edc permission scope audit.
	 *
	 * @param uuid the uuid of this edc permission scope audit
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the audit scope ID of this edc permission scope audit.
	 *
	 * @return the audit scope ID of this edc permission scope audit
	 */
	public long getAuditScopeId();

	/**
	 * Sets the audit scope ID of this edc permission scope audit.
	 *
	 * @param auditScopeId the audit scope ID of this edc permission scope audit
	 */
	public void setAuditScopeId(long auditScopeId);

	/**
	 * Returns the company ID of this edc permission scope audit.
	 *
	 * @return the company ID of this edc permission scope audit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this edc permission scope audit.
	 *
	 * @param companyId the company ID of this edc permission scope audit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this edc permission scope audit.
	 *
	 * @return the group ID of this edc permission scope audit
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this edc permission scope audit.
	 *
	 * @param groupId the group ID of this edc permission scope audit
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the project ID of this edc permission scope audit.
	 *
	 * @return the project ID of this edc permission scope audit
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this edc permission scope audit.
	 *
	 * @param projectId the project ID of this edc permission scope audit
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the role name of this edc permission scope audit.
	 *
	 * @return the role name of this edc permission scope audit
	 */
	@AutoEscape
	public String getRoleName();

	/**
	 * Sets the role name of this edc permission scope audit.
	 *
	 * @param roleName the role name of this edc permission scope audit
	 */
	public void setRoleName(String roleName);

	/**
	 * Returns the module name of this edc permission scope audit.
	 *
	 * @return the module name of this edc permission scope audit
	 */
	@AutoEscape
	public String getModuleName();

	/**
	 * Sets the module name of this edc permission scope audit.
	 *
	 * @param moduleName the module name of this edc permission scope audit
	 */
	public void setModuleName(String moduleName);

	/**
	 * Returns the task key of this edc permission scope audit.
	 *
	 * @return the task key of this edc permission scope audit
	 */
	@AutoEscape
	public String getTaskKey();

	/**
	 * Sets the task key of this edc permission scope audit.
	 *
	 * @param taskKey the task key of this edc permission scope audit
	 */
	public void setTaskKey(String taskKey);

	/**
	 * Returns the from scope of this edc permission scope audit.
	 *
	 * @return the from scope of this edc permission scope audit
	 */
	@AutoEscape
	public String getFromScope();

	/**
	 * Sets the from scope of this edc permission scope audit.
	 *
	 * @param fromScope the from scope of this edc permission scope audit
	 */
	public void setFromScope(String fromScope);

	/**
	 * Returns the to scope of this edc permission scope audit.
	 *
	 * @return the to scope of this edc permission scope audit
	 */
	@AutoEscape
	public String getToScope();

	/**
	 * Sets the to scope of this edc permission scope audit.
	 *
	 * @param toScope the to scope of this edc permission scope audit
	 */
	public void setToScope(String toScope);

	/**
	 * Returns the from active of this edc permission scope audit.
	 *
	 * @return the from active of this edc permission scope audit
	 */
	@AutoEscape
	public String getFromActive();

	/**
	 * Sets the from active of this edc permission scope audit.
	 *
	 * @param fromActive the from active of this edc permission scope audit
	 */
	public void setFromActive(String fromActive);

	/**
	 * Returns the to active of this edc permission scope audit.
	 *
	 * @return the to active of this edc permission scope audit
	 */
	@AutoEscape
	public String getToActive();

	/**
	 * Sets the to active of this edc permission scope audit.
	 *
	 * @param toActive the to active of this edc permission scope audit
	 */
	public void setToActive(String toActive);

	/**
	 * Returns the remarks of this edc permission scope audit.
	 *
	 * @return the remarks of this edc permission scope audit
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this edc permission scope audit.
	 *
	 * @param remarks the remarks of this edc permission scope audit
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the create date of this edc permission scope audit.
	 *
	 * @return the create date of this edc permission scope audit
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this edc permission scope audit.
	 *
	 * @param createDate the create date of this edc permission scope audit
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the user ID of this edc permission scope audit.
	 *
	 * @return the user ID of this edc permission scope audit
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this edc permission scope audit.
	 *
	 * @param userId the user ID of this edc permission scope audit
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this edc permission scope audit.
	 *
	 * @return the user uuid of this edc permission scope audit
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this edc permission scope audit.
	 *
	 * @param userUuid the user uuid of this edc permission scope audit
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this edc permission scope audit.
	 *
	 * @return the user name of this edc permission scope audit
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this edc permission scope audit.
	 *
	 * @param userName the user name of this edc permission scope audit
	 */
	public void setUserName(String userName);

}