/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EdcPermissionScope service. Represents a row in the &quot;EDC_EdcPermissionScope&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcPermissionScope
 * @generated
 */
@ProviderType
public interface EdcPermissionScopeModel
	extends BaseModel<EdcPermissionScope>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a edc permission scope model instance should use the {@link EdcPermissionScope} interface instead.
	 */

	/**
	 * Returns the primary key of this edc permission scope.
	 *
	 * @return the primary key of this edc permission scope
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this edc permission scope.
	 *
	 * @param primaryKey the primary key of this edc permission scope
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this edc permission scope.
	 *
	 * @return the uuid of this edc permission scope
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this edc permission scope.
	 *
	 * @param uuid the uuid of this edc permission scope
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the permission scope ID of this edc permission scope.
	 *
	 * @return the permission scope ID of this edc permission scope
	 */
	public long getPermissionScopeId();

	/**
	 * Sets the permission scope ID of this edc permission scope.
	 *
	 * @param permissionScopeId the permission scope ID of this edc permission scope
	 */
	public void setPermissionScopeId(long permissionScopeId);

	/**
	 * Returns the company ID of this edc permission scope.
	 *
	 * @return the company ID of this edc permission scope
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this edc permission scope.
	 *
	 * @param companyId the company ID of this edc permission scope
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this edc permission scope.
	 *
	 * @return the group ID of this edc permission scope
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this edc permission scope.
	 *
	 * @param groupId the group ID of this edc permission scope
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the project ID of this edc permission scope.
	 *
	 * @return the project ID of this edc permission scope
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this edc permission scope.
	 *
	 * @param projectId the project ID of this edc permission scope
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the module name of this edc permission scope.
	 *
	 * @return the module name of this edc permission scope
	 */
	@AutoEscape
	public String getModuleName();

	/**
	 * Sets the module name of this edc permission scope.
	 *
	 * @param moduleName the module name of this edc permission scope
	 */
	public void setModuleName(String moduleName);

	/**
	 * Returns the task key of this edc permission scope.
	 *
	 * @return the task key of this edc permission scope
	 */
	@AutoEscape
	public String getTaskKey();

	/**
	 * Sets the task key of this edc permission scope.
	 *
	 * @param taskKey the task key of this edc permission scope
	 */
	public void setTaskKey(String taskKey);

	/**
	 * Returns the role name of this edc permission scope.
	 *
	 * @return the role name of this edc permission scope
	 */
	@AutoEscape
	public String getRoleName();

	/**
	 * Sets the role name of this edc permission scope.
	 *
	 * @param roleName the role name of this edc permission scope
	 */
	public void setRoleName(String roleName);

	/**
	 * Returns the scope role of this edc permission scope.
	 *
	 * @return the scope role of this edc permission scope
	 */
	@AutoEscape
	public String getScopeRole();

	/**
	 * Sets the scope role of this edc permission scope.
	 *
	 * @param scopeRole the scope role of this edc permission scope
	 */
	public void setScopeRole(String scopeRole);

	/**
	 * Returns the active of this edc permission scope.
	 *
	 * @return the active of this edc permission scope
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this edc permission scope is active.
	 *
	 * @return <code>true</code> if this edc permission scope is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this edc permission scope is active.
	 *
	 * @param active the active of this edc permission scope
	 */
	public void setActive(boolean active);

	/**
	 * Returns the from date of this edc permission scope.
	 *
	 * @return the from date of this edc permission scope
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this edc permission scope.
	 *
	 * @param fromDate the from date of this edc permission scope
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this edc permission scope.
	 *
	 * @return the to date of this edc permission scope
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this edc permission scope.
	 *
	 * @param toDate the to date of this edc permission scope
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the create date of this edc permission scope.
	 *
	 * @return the create date of this edc permission scope
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this edc permission scope.
	 *
	 * @param createDate the create date of this edc permission scope
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this edc permission scope.
	 *
	 * @return the modified date of this edc permission scope
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this edc permission scope.
	 *
	 * @param modifiedDate the modified date of this edc permission scope
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this edc permission scope.
	 *
	 * @return the created by of this edc permission scope
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this edc permission scope.
	 *
	 * @param createdBy the created by of this edc permission scope
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this edc permission scope.
	 *
	 * @return the modified by of this edc permission scope
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this edc permission scope.
	 *
	 * @param modifiedBy the modified by of this edc permission scope
	 */
	public void setModifiedBy(long modifiedBy);

}