/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EdcPermissionRoleAudit service. Represents a row in the &quot;EDC_EdcPermissionRoleAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.EdcPermissionRoleAuditModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.EdcPermissionRoleAuditImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcPermissionRoleAudit
 * @generated
 */
@ProviderType
public interface EdcPermissionRoleAuditModel
	extends BaseModel<EdcPermissionRoleAudit>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a edc permission role audit model instance should use the {@link EdcPermissionRoleAudit} interface instead.
	 */

	/**
	 * Returns the primary key of this edc permission role audit.
	 *
	 * @return the primary key of this edc permission role audit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this edc permission role audit.
	 *
	 * @param primaryKey the primary key of this edc permission role audit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this edc permission role audit.
	 *
	 * @return the uuid of this edc permission role audit
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this edc permission role audit.
	 *
	 * @param uuid the uuid of this edc permission role audit
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the audit role ID of this edc permission role audit.
	 *
	 * @return the audit role ID of this edc permission role audit
	 */
	public long getAuditRoleId();

	/**
	 * Sets the audit role ID of this edc permission role audit.
	 *
	 * @param auditRoleId the audit role ID of this edc permission role audit
	 */
	public void setAuditRoleId(long auditRoleId);

	/**
	 * Returns the company ID of this edc permission role audit.
	 *
	 * @return the company ID of this edc permission role audit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this edc permission role audit.
	 *
	 * @param companyId the company ID of this edc permission role audit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this edc permission role audit.
	 *
	 * @return the group ID of this edc permission role audit
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this edc permission role audit.
	 *
	 * @param groupId the group ID of this edc permission role audit
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the project ID of this edc permission role audit.
	 *
	 * @return the project ID of this edc permission role audit
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this edc permission role audit.
	 *
	 * @param projectId the project ID of this edc permission role audit
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the actor group of this edc permission role audit.
	 *
	 * @return the actor group of this edc permission role audit
	 */
	public long getActorGroup();

	/**
	 * Sets the actor group of this edc permission role audit.
	 *
	 * @param actorGroup the actor group of this edc permission role audit
	 */
	public void setActorGroup(long actorGroup);

	/**
	 * Returns the actor ID of this edc permission role audit.
	 *
	 * @return the actor ID of this edc permission role audit
	 */
	public long getActorId();

	/**
	 * Sets the actor ID of this edc permission role audit.
	 *
	 * @param actorId the actor ID of this edc permission role audit
	 */
	public void setActorId(long actorId);

	/**
	 * Returns the crud type of this edc permission role audit.
	 *
	 * @return the crud type of this edc permission role audit
	 */
	@AutoEscape
	public String getCrudType();

	/**
	 * Sets the crud type of this edc permission role audit.
	 *
	 * @param crudType the crud type of this edc permission role audit
	 */
	public void setCrudType(String crudType);

	/**
	 * Returns the from role of this edc permission role audit.
	 *
	 * @return the from role of this edc permission role audit
	 */
	@AutoEscape
	public String getFromRole();

	/**
	 * Sets the from role of this edc permission role audit.
	 *
	 * @param fromRole the from role of this edc permission role audit
	 */
	public void setFromRole(String fromRole);

	/**
	 * Returns the to role of this edc permission role audit.
	 *
	 * @return the to role of this edc permission role audit
	 */
	@AutoEscape
	public String getToRole();

	/**
	 * Sets the to role of this edc permission role audit.
	 *
	 * @param toRole the to role of this edc permission role audit
	 */
	public void setToRole(String toRole);

	/**
	 * Returns the from active of this edc permission role audit.
	 *
	 * @return the from active of this edc permission role audit
	 */
	@AutoEscape
	public String getFromActive();

	/**
	 * Sets the from active of this edc permission role audit.
	 *
	 * @param fromActive the from active of this edc permission role audit
	 */
	public void setFromActive(String fromActive);

	/**
	 * Returns the to active of this edc permission role audit.
	 *
	 * @return the to active of this edc permission role audit
	 */
	@AutoEscape
	public String getToActive();

	/**
	 * Sets the to active of this edc permission role audit.
	 *
	 * @param toActive the to active of this edc permission role audit
	 */
	public void setToActive(String toActive);

	/**
	 * Returns the remarks of this edc permission role audit.
	 *
	 * @return the remarks of this edc permission role audit
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this edc permission role audit.
	 *
	 * @param remarks the remarks of this edc permission role audit
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the create date of this edc permission role audit.
	 *
	 * @return the create date of this edc permission role audit
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this edc permission role audit.
	 *
	 * @param createDate the create date of this edc permission role audit
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the user ID of this edc permission role audit.
	 *
	 * @return the user ID of this edc permission role audit
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this edc permission role audit.
	 *
	 * @param userId the user ID of this edc permission role audit
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this edc permission role audit.
	 *
	 * @return the user uuid of this edc permission role audit
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this edc permission role audit.
	 *
	 * @param userUuid the user uuid of this edc permission role audit
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this edc permission role audit.
	 *
	 * @return the user name of this edc permission role audit
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this edc permission role audit.
	 *
	 * @param userName the user name of this edc permission role audit
	 */
	public void setUserName(String userName);

}