/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Institution service. Represents a row in the &quot;EDC_Institution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.InstitutionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.InstitutionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Institution
 * @generated
 */
@ProviderType
public interface InstitutionModel
	extends BaseModel<Institution>, GroupedModel, ShardedModel,
			StagedAuditedModel, TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a institution model instance should use the {@link Institution} interface instead.
	 */

	/**
	 * Returns the primary key of this institution.
	 *
	 * @return the primary key of this institution
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this institution.
	 *
	 * @param primaryKey the primary key of this institution
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this institution.
	 *
	 * @return the uuid of this institution
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this institution.
	 *
	 * @param uuid the uuid of this institution
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the institution ID of this institution.
	 *
	 * @return the institution ID of this institution
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this institution.
	 *
	 * @param institutionId the institution ID of this institution
	 */
	public void setInstitutionId(long institutionId);

	/**
	 * Returns the group ID of this institution.
	 *
	 * @return the group ID of this institution
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this institution.
	 *
	 * @param groupId the group ID of this institution
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this institution.
	 *
	 * @return the company ID of this institution
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this institution.
	 *
	 * @param companyId the company ID of this institution
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this institution.
	 *
	 * @return the project ID of this institution
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this institution.
	 *
	 * @param projectId the project ID of this institution
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the user ID of this institution.
	 *
	 * @return the user ID of this institution
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this institution.
	 *
	 * @param userId the user ID of this institution
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this institution.
	 *
	 * @return the user uuid of this institution
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this institution.
	 *
	 * @param userUuid the user uuid of this institution
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this institution.
	 *
	 * @return the user name of this institution
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this institution.
	 *
	 * @param userName the user name of this institution
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this institution.
	 *
	 * @return the create date of this institution
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this institution.
	 *
	 * @param createDate the create date of this institution
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this institution.
	 *
	 * @return the modified date of this institution
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this institution.
	 *
	 * @param modifiedDate the modified date of this institution
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this institution.
	 *
	 * @return the status of this institution
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this institution.
	 *
	 * @param status the status of this institution
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this institution.
	 *
	 * @return the status by user ID of this institution
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this institution.
	 *
	 * @param statusByUserId the status by user ID of this institution
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this institution.
	 *
	 * @return the status by user uuid of this institution
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this institution.
	 *
	 * @param statusByUserUuid the status by user uuid of this institution
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this institution.
	 *
	 * @return the status by user name of this institution
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this institution.
	 *
	 * @param statusByUserName the status by user name of this institution
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this institution.
	 *
	 * @return the status date of this institution
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this institution.
	 *
	 * @param statusDate the status date of this institution
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the code of this institution.
	 *
	 * @return the code of this institution
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this institution.
	 *
	 * @param code the code of this institution
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this institution.
	 *
	 * @return the name of this institution
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this institution.
	 *
	 * @param name the name of this institution
	 */
	public void setName(String name);

	/**
	 * Returns the en name of this institution.
	 *
	 * @return the en name of this institution
	 */
	@AutoEscape
	public String getEnName();

	/**
	 * Sets the en name of this institution.
	 *
	 * @param enName the en name of this institution
	 */
	public void setEnName(String enName);

	/**
	 * Returns the type of this institution.
	 *
	 * @return the type of this institution
	 */
	public int getType();

	/**
	 * Sets the type of this institution.
	 *
	 * @param type the type of this institution
	 */
	public void setType(int type);

	/**
	 * Returns the pi name of this institution.
	 *
	 * @return the pi name of this institution
	 */
	@AutoEscape
	public String getPiName();

	/**
	 * Sets the pi name of this institution.
	 *
	 * @param piName the pi name of this institution
	 */
	public void setPiName(String piName);

	/**
	 * Returns the contact num of this institution.
	 *
	 * @return the contact num of this institution
	 */
	@AutoEscape
	public String getContactNum();

	/**
	 * Sets the contact num of this institution.
	 *
	 * @param contactNum the contact num of this institution
	 */
	public void setContactNum(String contactNum);

	/**
	 * Returns the email of this institution.
	 *
	 * @return the email of this institution
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this institution.
	 *
	 * @param email the email of this institution
	 */
	public void setEmail(String email);

	/**
	 * Returns the irb date of this institution.
	 *
	 * @return the irb date of this institution
	 */
	public Date getIrbDate();

	/**
	 * Sets the irb date of this institution.
	 *
	 * @param irbDate the irb date of this institution
	 */
	public void setIrbDate(Date irbDate);

	/**
	 * Returns the trash entry created when this institution was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this institution.
	 *
	 * @return the trash entry created when this institution was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this institution.
	 *
	 * @return the class primary key of the trash entry for this institution
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this institution.
	 *
	 * @return the trash handler for this institution
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this institution is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this institution is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this institution is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this institution is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this institution is approved.
	 *
	 * @return <code>true</code> if this institution is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this institution is denied.
	 *
	 * @return <code>true</code> if this institution is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this institution is a draft.
	 *
	 * @return <code>true</code> if this institution is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this institution is expired.
	 *
	 * @return <code>true</code> if this institution is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this institution is inactive.
	 *
	 * @return <code>true</code> if this institution is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this institution is incomplete.
	 *
	 * @return <code>true</code> if this institution is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this institution is pending.
	 *
	 * @return <code>true</code> if this institution is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this institution is scheduled.
	 *
	 * @return <code>true</code> if this institution is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}