/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InstResearcher service. Represents a row in the &quot;EDC_InstResearcher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.InstResearcherModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.InstResearcherImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InstResearcher
 * @generated
 */
@ProviderType
public interface InstResearcherModel
	extends BaseModel<InstResearcher>, GroupedModel, ShardedModel,
			StagedAuditedModel, TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a inst researcher model instance should use the {@link InstResearcher} interface instead.
	 */

	/**
	 * Returns the primary key of this inst researcher.
	 *
	 * @return the primary key of this inst researcher
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this inst researcher.
	 *
	 * @param primaryKey the primary key of this inst researcher
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this inst researcher.
	 *
	 * @return the uuid of this inst researcher
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this inst researcher.
	 *
	 * @param uuid the uuid of this inst researcher
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the institution researcher ID of this inst researcher.
	 *
	 * @return the institution researcher ID of this inst researcher
	 */
	public long getInstitutionResearcherId();

	/**
	 * Sets the institution researcher ID of this inst researcher.
	 *
	 * @param institutionResearcherId the institution researcher ID of this inst researcher
	 */
	public void setInstitutionResearcherId(long institutionResearcherId);

	/**
	 * Returns the group ID of this inst researcher.
	 *
	 * @return the group ID of this inst researcher
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this inst researcher.
	 *
	 * @param groupId the group ID of this inst researcher
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this inst researcher.
	 *
	 * @return the company ID of this inst researcher
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this inst researcher.
	 *
	 * @param companyId the company ID of this inst researcher
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this inst researcher.
	 *
	 * @return the project ID of this inst researcher
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this inst researcher.
	 *
	 * @param projectId the project ID of this inst researcher
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the user ID of this inst researcher.
	 *
	 * @return the user ID of this inst researcher
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this inst researcher.
	 *
	 * @param userId the user ID of this inst researcher
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this inst researcher.
	 *
	 * @return the user uuid of this inst researcher
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this inst researcher.
	 *
	 * @param userUuid the user uuid of this inst researcher
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this inst researcher.
	 *
	 * @return the user name of this inst researcher
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this inst researcher.
	 *
	 * @param userName the user name of this inst researcher
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this inst researcher.
	 *
	 * @return the create date of this inst researcher
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this inst researcher.
	 *
	 * @param createDate the create date of this inst researcher
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this inst researcher.
	 *
	 * @return the modified date of this inst researcher
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this inst researcher.
	 *
	 * @param modifiedDate the modified date of this inst researcher
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the institution ID of this inst researcher.
	 *
	 * @return the institution ID of this inst researcher
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this inst researcher.
	 *
	 * @param institutionId the institution ID of this inst researcher
	 */
	public void setInstitutionId(long institutionId);

	/**
	 * Returns the researcher ID of this inst researcher.
	 *
	 * @return the researcher ID of this inst researcher
	 */
	public long getResearcherId();

	/**
	 * Sets the researcher ID of this inst researcher.
	 *
	 * @param researcherId the researcher ID of this inst researcher
	 */
	public void setResearcherId(long researcherId);

	/**
	 * Returns the status of this inst researcher.
	 *
	 * @return the status of this inst researcher
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this inst researcher was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this inst researcher.
	 *
	 * @return the trash entry created when this inst researcher was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this inst researcher.
	 *
	 * @return the class primary key of the trash entry for this inst researcher
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this inst researcher.
	 *
	 * @return the trash handler for this inst researcher
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this inst researcher is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this inst researcher is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this inst researcher is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this inst researcher is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}