/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InstanceLink service. Represents a row in the &quot;EDC_InstanceLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.InstanceLinkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.InstanceLinkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InstanceLink
 * @generated
 */
@ProviderType
public interface InstanceLinkModel
	extends BaseModel<InstanceLink>, GroupedModel, ShardedModel,
			StagedAuditedModel, TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a instance link model instance should use the {@link InstanceLink} interface instead.
	 */

	/**
	 * Returns the primary key of this instance link.
	 *
	 * @return the primary key of this instance link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this instance link.
	 *
	 * @param primaryKey the primary key of this instance link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this instance link.
	 *
	 * @return the uuid of this instance link
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this instance link.
	 *
	 * @param uuid the uuid of this instance link
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the link ID of this instance link.
	 *
	 * @return the link ID of this instance link
	 */
	public long getLinkId();

	/**
	 * Sets the link ID of this instance link.
	 *
	 * @param linkId the link ID of this instance link
	 */
	public void setLinkId(long linkId);

	/**
	 * Returns the group ID of this instance link.
	 *
	 * @return the group ID of this instance link
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this instance link.
	 *
	 * @param groupId the group ID of this instance link
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this instance link.
	 *
	 * @return the company ID of this instance link
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this instance link.
	 *
	 * @param companyId the company ID of this instance link
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this instance link.
	 *
	 * @return the project ID of this instance link
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this instance link.
	 *
	 * @param projectId the project ID of this instance link
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the institution ID of this instance link.
	 *
	 * @return the institution ID of this instance link
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this instance link.
	 *
	 * @param institutionId the institution ID of this instance link
	 */
	public void setInstitutionId(long institutionId);

	/**
	 * Returns the user ID of this instance link.
	 *
	 * @return the user ID of this instance link
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this instance link.
	 *
	 * @param userId the user ID of this instance link
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this instance link.
	 *
	 * @return the user uuid of this instance link
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this instance link.
	 *
	 * @param userUuid the user uuid of this instance link
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this instance link.
	 *
	 * @return the user name of this instance link
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this instance link.
	 *
	 * @param userName the user name of this instance link
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this instance link.
	 *
	 * @return the create date of this instance link
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this instance link.
	 *
	 * @param createDate the create date of this instance link
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this instance link.
	 *
	 * @return the modified date of this instance link
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this instance link.
	 *
	 * @param modifiedDate the modified date of this instance link
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the subject ID of this instance link.
	 *
	 * @return the subject ID of this instance link
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this instance link.
	 *
	 * @param subjectId the subject ID of this instance link
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the visit group ID of this instance link.
	 *
	 * @return the visit group ID of this instance link
	 */
	public long getVisitGroupId();

	/**
	 * Sets the visit group ID of this instance link.
	 *
	 * @param visitGroupId the visit group ID of this instance link
	 */
	public void setVisitGroupId(long visitGroupId);

	/**
	 * Returns the visit definition ID of this instance link.
	 *
	 * @return the visit definition ID of this instance link
	 */
	public long getVisitDefinitionId();

	/**
	 * Sets the visit definition ID of this instance link.
	 *
	 * @param visitDefinitionId the visit definition ID of this instance link
	 */
	public void setVisitDefinitionId(long visitDefinitionId);

	/**
	 * Returns the visit crf ID of this instance link.
	 *
	 * @return the visit crf ID of this instance link
	 */
	public long getVisitCRFId();

	/**
	 * Sets the visit crf ID of this instance link.
	 *
	 * @param visitCRFId the visit crf ID of this instance link
	 */
	public void setVisitCRFId(long visitCRFId);

	/**
	 * Returns the sub crf ID of this instance link.
	 *
	 * @return the sub crf ID of this instance link
	 */
	public long getSubCRFId();

	/**
	 * Sets the sub crf ID of this instance link.
	 *
	 * @param subCRFId the sub crf ID of this instance link
	 */
	public void setSubCRFId(long subCRFId);

	/**
	 * Returns the instance ID of this instance link.
	 *
	 * @return the instance ID of this instance link
	 */
	public long getInstanceId();

	/**
	 * Sets the instance ID of this instance link.
	 *
	 * @param instanceId the instance ID of this instance link
	 */
	public void setInstanceId(long instanceId);

	/**
	 * Returns the status of this instance link.
	 *
	 * @return the status of this instance link
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this instance link was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this instance link.
	 *
	 * @return the trash entry created when this instance link was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this instance link.
	 *
	 * @return the class primary key of the trash entry for this instance link
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this instance link.
	 *
	 * @return the trash handler for this instance link
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this instance link is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this instance link is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this instance link is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this instance link is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}