/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MetaCode service. Represents a row in the &quot;EDC_MetaCode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.MetaCodeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.MetaCodeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MetaCode
 * @generated
 */
@ProviderType
public interface MetaCodeModel
	extends BaseModel<MetaCode>, GroupedModel, ShardedModel, StagedAuditedModel,
			TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a meta code model instance should use the {@link MetaCode} interface instead.
	 */

	/**
	 * Returns the primary key of this meta code.
	 *
	 * @return the primary key of this meta code
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this meta code.
	 *
	 * @param primaryKey the primary key of this meta code
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this meta code.
	 *
	 * @return the uuid of this meta code
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this meta code.
	 *
	 * @param uuid the uuid of this meta code
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the meta code ID of this meta code.
	 *
	 * @return the meta code ID of this meta code
	 */
	public long getMetaCodeId();

	/**
	 * Sets the meta code ID of this meta code.
	 *
	 * @param metaCodeId the meta code ID of this meta code
	 */
	public void setMetaCodeId(long metaCodeId);

	/**
	 * Returns the group ID of this meta code.
	 *
	 * @return the group ID of this meta code
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this meta code.
	 *
	 * @param groupId the group ID of this meta code
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this meta code.
	 *
	 * @return the company ID of this meta code
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this meta code.
	 *
	 * @param companyId the company ID of this meta code
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this meta code.
	 *
	 * @return the project ID of this meta code
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this meta code.
	 *
	 * @param projectId the project ID of this meta code
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the user ID of this meta code.
	 *
	 * @return the user ID of this meta code
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this meta code.
	 *
	 * @param userId the user ID of this meta code
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this meta code.
	 *
	 * @return the user uuid of this meta code
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this meta code.
	 *
	 * @param userUuid the user uuid of this meta code
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this meta code.
	 *
	 * @return the user name of this meta code
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this meta code.
	 *
	 * @param userName the user name of this meta code
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this meta code.
	 *
	 * @return the create date of this meta code
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this meta code.
	 *
	 * @param createDate the create date of this meta code
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this meta code.
	 *
	 * @return the modified date of this meta code
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this meta code.
	 *
	 * @param modifiedDate the modified date of this meta code
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this meta code.
	 *
	 * @return the status of this meta code
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this meta code.
	 *
	 * @param status the status of this meta code
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this meta code.
	 *
	 * @return the status by user ID of this meta code
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this meta code.
	 *
	 * @param statusByUserId the status by user ID of this meta code
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this meta code.
	 *
	 * @return the status by user uuid of this meta code
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this meta code.
	 *
	 * @param statusByUserUuid the status by user uuid of this meta code
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this meta code.
	 *
	 * @return the status by user name of this meta code
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this meta code.
	 *
	 * @param statusByUserName the status by user name of this meta code
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this meta code.
	 *
	 * @return the status date of this meta code
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this meta code.
	 *
	 * @param statusDate the status date of this meta code
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the group code of this meta code.
	 *
	 * @return the group code of this meta code
	 */
	@AutoEscape
	public String getGroupCode();

	/**
	 * Sets the group code of this meta code.
	 *
	 * @param groupCode the group code of this meta code
	 */
	public void setGroupCode(String groupCode);

	/**
	 * Returns the code of this meta code.
	 *
	 * @return the code of this meta code
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this meta code.
	 *
	 * @param code the code of this meta code
	 */
	public void setCode(String code);

	/**
	 * Returns the label of this meta code.
	 *
	 * @return the label of this meta code
	 */
	@AutoEscape
	public String getLabel();

	/**
	 * Sets the label of this meta code.
	 *
	 * @param label the label of this meta code
	 */
	public void setLabel(String label);

	/**
	 * Returns the value type of this meta code.
	 *
	 * @return the value type of this meta code
	 */
	@AutoEscape
	public String getValueType();

	/**
	 * Sets the value type of this meta code.
	 *
	 * @param valueType the value type of this meta code
	 */
	public void setValueType(String valueType);

	/**
	 * Returns the value of this meta code.
	 *
	 * @return the value of this meta code
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this meta code.
	 *
	 * @param value the value of this meta code
	 */
	public void setValue(String value);

	/**
	 * Returns the active of this meta code.
	 *
	 * @return the active of this meta code
	 */
	public Boolean getActive();

	/**
	 * Sets the active of this meta code.
	 *
	 * @param active the active of this meta code
	 */
	public void setActive(Boolean active);

	/**
	 * Returns the inactive date of this meta code.
	 *
	 * @return the inactive date of this meta code
	 */
	public Date getInactiveDate();

	/**
	 * Sets the inactive date of this meta code.
	 *
	 * @param inactiveDate the inactive date of this meta code
	 */
	public void setInactiveDate(Date inactiveDate);

	/**
	 * Returns the trash entry created when this meta code was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this meta code.
	 *
	 * @return the trash entry created when this meta code was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this meta code.
	 *
	 * @return the class primary key of the trash entry for this meta code
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this meta code.
	 *
	 * @return the trash handler for this meta code
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this meta code is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this meta code is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this meta code is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this meta code is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this meta code is approved.
	 *
	 * @return <code>true</code> if this meta code is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this meta code is denied.
	 *
	 * @return <code>true</code> if this meta code is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this meta code is a draft.
	 *
	 * @return <code>true</code> if this meta code is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this meta code is expired.
	 *
	 * @return <code>true</code> if this meta code is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this meta code is inactive.
	 *
	 * @return <code>true</code> if this meta code is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this meta code is incomplete.
	 *
	 * @return <code>true</code> if this meta code is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this meta code is pending.
	 *
	 * @return <code>true</code> if this meta code is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this meta code is scheduled.
	 *
	 * @return <code>true</code> if this meta code is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}