/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Query service. Represents a row in the &quot;EDC_Query&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.QueryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.QueryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Query
 * @generated
 */
@ProviderType
public interface QueryModel
	extends BaseModel<Query>, GroupedModel, ShardedModel, StagedAuditedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a query model instance should use the {@link Query} interface instead.
	 */

	/**
	 * Returns the primary key of this query.
	 *
	 * @return the primary key of this query
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this query.
	 *
	 * @param primaryKey the primary key of this query
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this query.
	 *
	 * @return the uuid of this query
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this query.
	 *
	 * @param uuid the uuid of this query
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the query ID of this query.
	 *
	 * @return the query ID of this query
	 */
	public long getQueryId();

	/**
	 * Sets the query ID of this query.
	 *
	 * @param queryId the query ID of this query
	 */
	public void setQueryId(long queryId);

	/**
	 * Returns the group ID of this query.
	 *
	 * @return the group ID of this query
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this query.
	 *
	 * @param groupId the group ID of this query
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this query.
	 *
	 * @return the company ID of this query
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this query.
	 *
	 * @param companyId the company ID of this query
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this query.
	 *
	 * @return the project ID of this query
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this query.
	 *
	 * @param projectId the project ID of this query
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the user ID of this query.
	 *
	 * @return the user ID of this query
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this query.
	 *
	 * @param userId the user ID of this query
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this query.
	 *
	 * @return the user uuid of this query
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this query.
	 *
	 * @param userUuid the user uuid of this query
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this query.
	 *
	 * @return the user name of this query
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this query.
	 *
	 * @param userName the user name of this query
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this query.
	 *
	 * @return the create date of this query
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this query.
	 *
	 * @param createDate the create date of this query
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this query.
	 *
	 * @return the modified date of this query
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this query.
	 *
	 * @param modifiedDate the modified date of this query
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the subject ID of this query.
	 *
	 * @return the subject ID of this query
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this query.
	 *
	 * @param subjectId the subject ID of this query
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the visit group ID of this query.
	 *
	 * @return the visit group ID of this query
	 */
	public long getVisitGroupId();

	/**
	 * Sets the visit group ID of this query.
	 *
	 * @param visitGroupId the visit group ID of this query
	 */
	public void setVisitGroupId(long visitGroupId);

	/**
	 * Returns the visit definition ID of this query.
	 *
	 * @return the visit definition ID of this query
	 */
	public long getVisitDefinitionId();

	/**
	 * Sets the visit definition ID of this query.
	 *
	 * @param visitDefinitionId the visit definition ID of this query
	 */
	public void setVisitDefinitionId(long visitDefinitionId);

	/**
	 * Returns the visit crf ID of this query.
	 *
	 * @return the visit crf ID of this query
	 */
	public long getVisitCRFId();

	/**
	 * Sets the visit crf ID of this query.
	 *
	 * @param visitCRFId the visit crf ID of this query
	 */
	public void setVisitCRFId(long visitCRFId);

	/**
	 * Returns the sub crf ID of this query.
	 *
	 * @return the sub crf ID of this query
	 */
	public long getSubCRFId();

	/**
	 * Sets the sub crf ID of this query.
	 *
	 * @param subCRFId the sub crf ID of this query
	 */
	public void setSubCRFId(long subCRFId);

	/**
	 * Returns the instance ID of this query.
	 *
	 * @return the instance ID of this query
	 */
	public long getInstanceId();

	/**
	 * Sets the instance ID of this query.
	 *
	 * @param instanceId the instance ID of this query
	 */
	public void setInstanceId(long instanceId);

	/**
	 * Returns the item code of this query.
	 *
	 * @return the item code of this query
	 */
	public long getItemCode();

	/**
	 * Sets the item code of this query.
	 *
	 * @param itemCode the item code of this query
	 */
	public void setItemCode(long itemCode);

	/**
	 * Returns the source type of this query.
	 *
	 * @return the source type of this query
	 */
	@AutoEscape
	public String getSourceType();

	/**
	 * Sets the source type of this query.
	 *
	 * @param sourceType the source type of this query
	 */
	public void setSourceType(String sourceType);

	/**
	 * Returns the scope of this query.
	 *
	 * @return the scope of this query
	 */
	@AutoEscape
	public String getScope();

	/**
	 * Sets the scope of this query.
	 *
	 * @param scope the scope of this query
	 */
	public void setScope(String scope);

	/**
	 * Returns the is type manual of this query.
	 *
	 * @return the is type manual of this query
	 */
	@AutoEscape
	public String getIsTypeManual();

	/**
	 * Sets the is type manual of this query.
	 *
	 * @param isTypeManual the is type manual of this query
	 */
	public void setIsTypeManual(String isTypeManual);

	/**
	 * Returns the type of this query.
	 *
	 * @return the type of this query
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this query.
	 *
	 * @param type the type of this query
	 */
	public void setType(String type);

	/**
	 * Returns the open user ID of this query.
	 *
	 * @return the open user ID of this query
	 */
	public long getOpenUserId();

	/**
	 * Sets the open user ID of this query.
	 *
	 * @param openUserId the open user ID of this query
	 */
	public void setOpenUserId(long openUserId);

	/**
	 * Returns the open user uuid of this query.
	 *
	 * @return the open user uuid of this query
	 */
	public String getOpenUserUuid();

	/**
	 * Sets the open user uuid of this query.
	 *
	 * @param openUserUuid the open user uuid of this query
	 */
	public void setOpenUserUuid(String openUserUuid);

	/**
	 * Returns the open user name of this query.
	 *
	 * @return the open user name of this query
	 */
	@AutoEscape
	public String getOpenUserName();

	/**
	 * Sets the open user name of this query.
	 *
	 * @param openUserName the open user name of this query
	 */
	public void setOpenUserName(String openUserName);

	/**
	 * Returns the open date of this query.
	 *
	 * @return the open date of this query
	 */
	public Date getOpenDate();

	/**
	 * Sets the open date of this query.
	 *
	 * @param openDate the open date of this query
	 */
	public void setOpenDate(Date openDate);

	/**
	 * Returns the open comment of this query.
	 *
	 * @return the open comment of this query
	 */
	@AutoEscape
	public String getOpenComment();

	/**
	 * Sets the open comment of this query.
	 *
	 * @param openComment the open comment of this query
	 */
	public void setOpenComment(String openComment);

	/**
	 * Returns the answer user ID of this query.
	 *
	 * @return the answer user ID of this query
	 */
	public long getAnswerUserID();

	/**
	 * Sets the answer user ID of this query.
	 *
	 * @param answerUserID the answer user ID of this query
	 */
	public void setAnswerUserID(long answerUserID);

	/**
	 * Returns the answer user name of this query.
	 *
	 * @return the answer user name of this query
	 */
	@AutoEscape
	public String getAnswerUserName();

	/**
	 * Sets the answer user name of this query.
	 *
	 * @param answerUserName the answer user name of this query
	 */
	public void setAnswerUserName(String answerUserName);

	/**
	 * Returns the answer date of this query.
	 *
	 * @return the answer date of this query
	 */
	public Date getAnswerDate();

	/**
	 * Sets the answer date of this query.
	 *
	 * @param answerDate the answer date of this query
	 */
	public void setAnswerDate(Date answerDate);

	/**
	 * Returns the answer comment of this query.
	 *
	 * @return the answer comment of this query
	 */
	@AutoEscape
	public String getAnswerComment();

	/**
	 * Sets the answer comment of this query.
	 *
	 * @param answerComment the answer comment of this query
	 */
	public void setAnswerComment(String answerComment);

	/**
	 * Returns the close user ID of this query.
	 *
	 * @return the close user ID of this query
	 */
	public long getCloseUserID();

	/**
	 * Sets the close user ID of this query.
	 *
	 * @param closeUserID the close user ID of this query
	 */
	public void setCloseUserID(long closeUserID);

	/**
	 * Returns the close user name of this query.
	 *
	 * @return the close user name of this query
	 */
	@AutoEscape
	public String getCloseUserName();

	/**
	 * Sets the close user name of this query.
	 *
	 * @param closeUserName the close user name of this query
	 */
	public void setCloseUserName(String closeUserName);

	/**
	 * Returns the close date of this query.
	 *
	 * @return the close date of this query
	 */
	public Date getCloseDate();

	/**
	 * Sets the close date of this query.
	 *
	 * @param closeDate the close date of this query
	 */
	public void setCloseDate(Date closeDate);

	/**
	 * Returns the close comment of this query.
	 *
	 * @return the close comment of this query
	 */
	@AutoEscape
	public String getCloseComment();

	/**
	 * Sets the close comment of this query.
	 *
	 * @param closeComment the close comment of this query
	 */
	public void setCloseComment(String closeComment);

	/**
	 * Returns the query status of this query.
	 *
	 * @return the query status of this query
	 */
	public int getQueryStatus();

	/**
	 * Sets the query status of this query.
	 *
	 * @param queryStatus the query status of this query
	 */
	public void setQueryStatus(int queryStatus);

	/**
	 * Returns the is reopen of this query.
	 *
	 * @return the is reopen of this query
	 */
	@AutoEscape
	public String getIsReopen();

	/**
	 * Sets the is reopen of this query.
	 *
	 * @param isReopen the is reopen of this query
	 */
	public void setIsReopen(String isReopen);

	/**
	 * Returns the reopen ID of this query.
	 *
	 * @return the reopen ID of this query
	 */
	public long getReopenId();

	/**
	 * Sets the reopen ID of this query.
	 *
	 * @param reopenId the reopen ID of this query
	 */
	public void setReopenId(long reopenId);

	/**
	 * Returns the rule ID of this query.
	 *
	 * @return the rule ID of this query
	 */
	public long getRuleId();

	/**
	 * Sets the rule ID of this query.
	 *
	 * @param ruleId the rule ID of this query
	 */
	public void setRuleId(long ruleId);

	/**
	 * Returns the rule info of this query.
	 *
	 * @return the rule info of this query
	 */
	@AutoEscape
	public String getRuleInfo();

	/**
	 * Sets the rule info of this query.
	 *
	 * @param ruleInfo the rule info of this query
	 */
	public void setRuleInfo(String ruleInfo);

	/**
	 * Returns the active status of this query.
	 *
	 * @return the active status of this query
	 */
	public int getActiveStatus();

	/**
	 * Sets the active status of this query.
	 *
	 * @param activeStatus the active status of this query
	 */
	public void setActiveStatus(int activeStatus);

	/**
	 * Returns the inactive date of this query.
	 *
	 * @return the inactive date of this query
	 */
	public Date getInactiveDate();

	/**
	 * Sets the inactive date of this query.
	 *
	 * @param inactiveDate the inactive date of this query
	 */
	public void setInactiveDate(Date inactiveDate);

	/**
	 * Returns the status of this query.
	 *
	 * @return the status of this query
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this query was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this query.
	 *
	 * @return the trash entry created when this query was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this query.
	 *
	 * @return the class primary key of the trash entry for this query
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this query.
	 *
	 * @return the trash handler for this query
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this query is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this query is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this query is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this query is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}