/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Randomization service. Represents a row in the &quot;EDC_Randomization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.RandomizationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.RandomizationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Randomization
 * @generated
 */
@ProviderType
public interface RandomizationModel
	extends BaseModel<Randomization>, GroupedModel, ShardedModel,
			StagedAuditedModel, TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a randomization model instance should use the {@link Randomization} interface instead.
	 */

	/**
	 * Returns the primary key of this randomization.
	 *
	 * @return the primary key of this randomization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this randomization.
	 *
	 * @param primaryKey the primary key of this randomization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this randomization.
	 *
	 * @return the uuid of this randomization
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this randomization.
	 *
	 * @param uuid the uuid of this randomization
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the randomization ID of this randomization.
	 *
	 * @return the randomization ID of this randomization
	 */
	public long getRandomizationId();

	/**
	 * Sets the randomization ID of this randomization.
	 *
	 * @param randomizationId the randomization ID of this randomization
	 */
	public void setRandomizationId(long randomizationId);

	/**
	 * Returns the group ID of this randomization.
	 *
	 * @return the group ID of this randomization
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this randomization.
	 *
	 * @param groupId the group ID of this randomization
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this randomization.
	 *
	 * @return the company ID of this randomization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this randomization.
	 *
	 * @param companyId the company ID of this randomization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this randomization.
	 *
	 * @return the project ID of this randomization
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this randomization.
	 *
	 * @param projectId the project ID of this randomization
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the user ID of this randomization.
	 *
	 * @return the user ID of this randomization
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this randomization.
	 *
	 * @param userId the user ID of this randomization
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this randomization.
	 *
	 * @return the user uuid of this randomization
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this randomization.
	 *
	 * @param userUuid the user uuid of this randomization
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this randomization.
	 *
	 * @return the user name of this randomization
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this randomization.
	 *
	 * @param userName the user name of this randomization
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this randomization.
	 *
	 * @return the create date of this randomization
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this randomization.
	 *
	 * @param createDate the create date of this randomization
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this randomization.
	 *
	 * @return the modified date of this randomization
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this randomization.
	 *
	 * @param modifiedDate the modified date of this randomization
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this randomization.
	 *
	 * @return the status of this randomization
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this randomization.
	 *
	 * @param status the status of this randomization
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this randomization.
	 *
	 * @return the status by user ID of this randomization
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this randomization.
	 *
	 * @param statusByUserId the status by user ID of this randomization
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this randomization.
	 *
	 * @return the status by user uuid of this randomization
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this randomization.
	 *
	 * @param statusByUserUuid the status by user uuid of this randomization
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this randomization.
	 *
	 * @return the status by user name of this randomization
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this randomization.
	 *
	 * @param statusByUserName the status by user name of this randomization
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this randomization.
	 *
	 * @return the status date of this randomization
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this randomization.
	 *
	 * @param statusDate the status date of this randomization
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the random no of this randomization.
	 *
	 * @return the random no of this randomization
	 */
	@AutoEscape
	public String getRandomNo();

	/**
	 * Sets the random no of this randomization.
	 *
	 * @param randomNo the random no of this randomization
	 */
	public void setRandomNo(String randomNo);

	/**
	 * Returns the use status of this randomization.
	 *
	 * @return the use status of this randomization
	 */
	public int getUseStatus();

	/**
	 * Sets the use status of this randomization.
	 *
	 * @param useStatus the use status of this randomization
	 */
	public void setUseStatus(int useStatus);

	/**
	 * Returns the source type of this randomization.
	 *
	 * @return the source type of this randomization
	 */
	public int getSourceType();

	/**
	 * Sets the source type of this randomization.
	 *
	 * @param sourceType the source type of this randomization
	 */
	public void setSourceType(int sourceType);

	/**
	 * Returns the criteria of this randomization.
	 *
	 * @return the criteria of this randomization
	 */
	@AutoEscape
	public String getCriteria();

	/**
	 * Sets the criteria of this randomization.
	 *
	 * @param criteria the criteria of this randomization
	 */
	public void setCriteria(String criteria);

	/**
	 * Returns the exp group ID of this randomization.
	 *
	 * @return the exp group ID of this randomization
	 */
	public long getExpGroupId();

	/**
	 * Sets the exp group ID of this randomization.
	 *
	 * @param expGroupId the exp group ID of this randomization
	 */
	public void setExpGroupId(long expGroupId);

	/**
	 * Returns the trash entry created when this randomization was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this randomization.
	 *
	 * @return the trash entry created when this randomization was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this randomization.
	 *
	 * @return the class primary key of the trash entry for this randomization
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this randomization.
	 *
	 * @return the trash handler for this randomization
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this randomization is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this randomization is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this randomization is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this randomization is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this randomization is approved.
	 *
	 * @return <code>true</code> if this randomization is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this randomization is denied.
	 *
	 * @return <code>true</code> if this randomization is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this randomization is a draft.
	 *
	 * @return <code>true</code> if this randomization is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this randomization is expired.
	 *
	 * @return <code>true</code> if this randomization is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this randomization is inactive.
	 *
	 * @return <code>true</code> if this randomization is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this randomization is incomplete.
	 *
	 * @return <code>true</code> if this randomization is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this randomization is pending.
	 *
	 * @return <code>true</code> if this randomization is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this randomization is scheduled.
	 *
	 * @return <code>true</code> if this randomization is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}