/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Subject service. Represents a row in the &quot;EDC_Subject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.SubjectModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.SubjectImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Subject
 * @generated
 */
@ProviderType
public interface SubjectModel
	extends BaseModel<Subject>, GroupedModel, ShardedModel, StagedAuditedModel,
			TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subject model instance should use the {@link Subject} interface instead.
	 */

	/**
	 * Returns the primary key of this subject.
	 *
	 * @return the primary key of this subject
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subject.
	 *
	 * @param primaryKey the primary key of this subject
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this subject.
	 *
	 * @return the uuid of this subject
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this subject.
	 *
	 * @param uuid the uuid of this subject
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the subject ID of this subject.
	 *
	 * @return the subject ID of this subject
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this subject.
	 *
	 * @param subjectId the subject ID of this subject
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the group ID of this subject.
	 *
	 * @return the group ID of this subject
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this subject.
	 *
	 * @param groupId the group ID of this subject
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this subject.
	 *
	 * @return the company ID of this subject
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this subject.
	 *
	 * @param companyId the company ID of this subject
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this subject.
	 *
	 * @return the project ID of this subject
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this subject.
	 *
	 * @param projectId the project ID of this subject
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the institution ID of this subject.
	 *
	 * @return the institution ID of this subject
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this subject.
	 *
	 * @param institutionId the institution ID of this subject
	 */
	public void setInstitutionId(long institutionId);

	/**
	 * Returns the user ID of this subject.
	 *
	 * @return the user ID of this subject
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this subject.
	 *
	 * @param userId the user ID of this subject
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this subject.
	 *
	 * @return the user uuid of this subject
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this subject.
	 *
	 * @param userUuid the user uuid of this subject
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this subject.
	 *
	 * @return the user name of this subject
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this subject.
	 *
	 * @param userName the user name of this subject
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this subject.
	 *
	 * @return the create date of this subject
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this subject.
	 *
	 * @param createDate the create date of this subject
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this subject.
	 *
	 * @return the modified date of this subject
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this subject.
	 *
	 * @param modifiedDate the modified date of this subject
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this subject.
	 *
	 * @return the status of this subject
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this subject.
	 *
	 * @param status the status of this subject
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this subject.
	 *
	 * @return the status by user ID of this subject
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this subject.
	 *
	 * @param statusByUserId the status by user ID of this subject
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this subject.
	 *
	 * @return the status by user uuid of this subject
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this subject.
	 *
	 * @param statusByUserUuid the status by user uuid of this subject
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this subject.
	 *
	 * @return the status by user name of this subject
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this subject.
	 *
	 * @param statusByUserName the status by user name of this subject
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this subject.
	 *
	 * @return the status date of this subject
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this subject.
	 *
	 * @param statusDate the status date of this subject
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the serial ID of this subject.
	 *
	 * @return the serial ID of this subject
	 */
	@AutoEscape
	public String getSerialId();

	/**
	 * Sets the serial ID of this subject.
	 *
	 * @param serialId the serial ID of this subject
	 */
	public void setSerialId(String serialId);

	/**
	 * Returns the random no of this subject.
	 *
	 * @return the random no of this subject
	 */
	@AutoEscape
	public String getRandomNo();

	/**
	 * Sets the random no of this subject.
	 *
	 * @param randomNo the random no of this subject
	 */
	public void setRandomNo(String randomNo);

	/**
	 * Returns the name of this subject.
	 *
	 * @return the name of this subject
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this subject.
	 *
	 * @param name the name of this subject
	 */
	public void setName(String name);

	/**
	 * Returns the subject status of this subject.
	 *
	 * @return the subject status of this subject
	 */
	public int getSubjectStatus();

	/**
	 * Sets the subject status of this subject.
	 *
	 * @param subjectStatus the subject status of this subject
	 */
	public void setSubjectStatus(int subjectStatus);

	/**
	 * Returns the subject status apply date of this subject.
	 *
	 * @return the subject status apply date of this subject
	 */
	public Date getSubjectStatusApplyDate();

	/**
	 * Sets the subject status apply date of this subject.
	 *
	 * @param subjectStatusApplyDate the subject status apply date of this subject
	 */
	public void setSubjectStatusApplyDate(Date subjectStatusApplyDate);

	/**
	 * Returns the consent agree date of this subject.
	 *
	 * @return the consent agree date of this subject
	 */
	public Date getConsentAgreeDate();

	/**
	 * Sets the consent agree date of this subject.
	 *
	 * @param consentAgreeDate the consent agree date of this subject
	 */
	public void setConsentAgreeDate(Date consentAgreeDate);

	/**
	 * Returns the exp group ID of this subject.
	 *
	 * @return the exp group ID of this subject
	 */
	public long getExpGroupId();

	/**
	 * Sets the exp group ID of this subject.
	 *
	 * @param expGroupId the exp group ID of this subject
	 */
	public void setExpGroupId(long expGroupId);

	/**
	 * Returns the apply date of this subject.
	 *
	 * @return the apply date of this subject
	 */
	public Date getApplyDate();

	/**
	 * Sets the apply date of this subject.
	 *
	 * @param applyDate the apply date of this subject
	 */
	public void setApplyDate(Date applyDate);

	/**
	 * Returns the trash entry created when this subject was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this subject.
	 *
	 * @return the trash entry created when this subject was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this subject.
	 *
	 * @return the class primary key of the trash entry for this subject
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this subject.
	 *
	 * @return the trash handler for this subject
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this subject is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this subject is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this subject is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this subject is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this subject is approved.
	 *
	 * @return <code>true</code> if this subject is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this subject is denied.
	 *
	 * @return <code>true</code> if this subject is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this subject is a draft.
	 *
	 * @return <code>true</code> if this subject is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this subject is expired.
	 *
	 * @return <code>true</code> if this subject is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this subject is inactive.
	 *
	 * @return <code>true</code> if this subject is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this subject is incomplete.
	 *
	 * @return <code>true</code> if this subject is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this subject is pending.
	 *
	 * @return <code>true</code> if this subject is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this subject is scheduled.
	 *
	 * @return <code>true</code> if this subject is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}