/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the VisitEvent service. Represents a row in the &quot;EDC_VisitEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.VisitEventModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.VisitEventImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VisitEvent
 * @generated
 */
@ProviderType
public interface VisitEventModel
	extends BaseModel<VisitEvent>, GroupedModel, ShardedModel,
			StagedAuditedModel, TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a visit event model instance should use the {@link VisitEvent} interface instead.
	 */

	/**
	 * Returns the primary key of this visit event.
	 *
	 * @return the primary key of this visit event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this visit event.
	 *
	 * @param primaryKey the primary key of this visit event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this visit event.
	 *
	 * @return the uuid of this visit event
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this visit event.
	 *
	 * @param uuid the uuid of this visit event
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the visit event ID of this visit event.
	 *
	 * @return the visit event ID of this visit event
	 */
	public long getVisitEventId();

	/**
	 * Sets the visit event ID of this visit event.
	 *
	 * @param visitEventId the visit event ID of this visit event
	 */
	public void setVisitEventId(long visitEventId);

	/**
	 * Returns the group ID of this visit event.
	 *
	 * @return the group ID of this visit event
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this visit event.
	 *
	 * @param groupId the group ID of this visit event
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this visit event.
	 *
	 * @return the company ID of this visit event
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this visit event.
	 *
	 * @param companyId the company ID of this visit event
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this visit event.
	 *
	 * @return the project ID of this visit event
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this visit event.
	 *
	 * @param projectId the project ID of this visit event
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the institution ID of this visit event.
	 *
	 * @return the institution ID of this visit event
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this visit event.
	 *
	 * @param institutionId the institution ID of this visit event
	 */
	public void setInstitutionId(long institutionId);

	/**
	 * Returns the subject ID of this visit event.
	 *
	 * @return the subject ID of this visit event
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this visit event.
	 *
	 * @param subjectId the subject ID of this visit event
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the visit definition ID of this visit event.
	 *
	 * @return the visit definition ID of this visit event
	 */
	public long getVisitDefinitionId();

	/**
	 * Sets the visit definition ID of this visit event.
	 *
	 * @param visitDefinitionId the visit definition ID of this visit event
	 */
	public void setVisitDefinitionId(long visitDefinitionId);

	/**
	 * Returns the user ID of this visit event.
	 *
	 * @return the user ID of this visit event
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this visit event.
	 *
	 * @param userId the user ID of this visit event
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this visit event.
	 *
	 * @return the user uuid of this visit event
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this visit event.
	 *
	 * @param userUuid the user uuid of this visit event
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this visit event.
	 *
	 * @return the user name of this visit event
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this visit event.
	 *
	 * @param userName the user name of this visit event
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this visit event.
	 *
	 * @return the create date of this visit event
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this visit event.
	 *
	 * @param createDate the create date of this visit event
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this visit event.
	 *
	 * @return the modified date of this visit event
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this visit event.
	 *
	 * @param modifiedDate the modified date of this visit event
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this visit event.
	 *
	 * @return the status of this visit event
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this visit event.
	 *
	 * @param status the status of this visit event
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this visit event.
	 *
	 * @return the status by user ID of this visit event
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this visit event.
	 *
	 * @param statusByUserId the status by user ID of this visit event
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this visit event.
	 *
	 * @return the status by user uuid of this visit event
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this visit event.
	 *
	 * @param statusByUserUuid the status by user uuid of this visit event
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this visit event.
	 *
	 * @return the status by user name of this visit event
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this visit event.
	 *
	 * @param statusByUserName the status by user name of this visit event
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this visit event.
	 *
	 * @return the status date of this visit event
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this visit event.
	 *
	 * @param statusDate the status date of this visit event
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the anchor type of this visit event.
	 *
	 * @return the anchor type of this visit event
	 */
	@AutoEscape
	public String getAnchorType();

	/**
	 * Sets the anchor type of this visit event.
	 *
	 * @param anchorType the anchor type of this visit event
	 */
	public void setAnchorType(String anchorType);

	/**
	 * Returns the anchor date of this visit event.
	 *
	 * @return the anchor date of this visit event
	 */
	public Date getAnchorDate();

	/**
	 * Sets the anchor date of this visit event.
	 *
	 * @param anchorDate the anchor date of this visit event
	 */
	public void setAnchorDate(Date anchorDate);

	/**
	 * Returns the offset of this visit event.
	 *
	 * @return the offset of this visit event
	 */
	public int getOffset();

	/**
	 * Sets the offset of this visit event.
	 *
	 * @param offset the offset of this visit event
	 */
	public void setOffset(int offset);

	/**
	 * Returns the plan date of this visit event.
	 *
	 * @return the plan date of this visit event
	 */
	public Date getPlanDate();

	/**
	 * Sets the plan date of this visit event.
	 *
	 * @param planDate the plan date of this visit event
	 */
	public void setPlanDate(Date planDate);

	/**
	 * Returns the event date of this visit event.
	 *
	 * @return the event date of this visit event
	 */
	public Date getEventDate();

	/**
	 * Sets the event date of this visit event.
	 *
	 * @param eventDate the event date of this visit event
	 */
	public void setEventDate(Date eventDate);

	/**
	 * Returns the deviation status of this visit event.
	 *
	 * @return the deviation status of this visit event
	 */
	@AutoEscape
	public String getDeviationStatus();

	/**
	 * Sets the deviation status of this visit event.
	 *
	 * @param deviationStatus the deviation status of this visit event
	 */
	public void setDeviationStatus(String deviationStatus);

	/**
	 * Returns the instance link obj of this visit event.
	 *
	 * @return the instance link obj of this visit event
	 */
	@AutoEscape
	public String getInstanceLinkObj();

	/**
	 * Sets the instance link obj of this visit event.
	 *
	 * @param instanceLinkObj the instance link obj of this visit event
	 */
	public void setInstanceLinkObj(String instanceLinkObj);

	/**
	 * Returns the trash entry created when this visit event was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this visit event.
	 *
	 * @return the trash entry created when this visit event was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this visit event.
	 *
	 * @return the class primary key of the trash entry for this visit event
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this visit event.
	 *
	 * @return the trash handler for this visit event
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this visit event is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this visit event is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this visit event is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this visit event is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this visit event is approved.
	 *
	 * @return <code>true</code> if this visit event is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this visit event is denied.
	 *
	 * @return <code>true</code> if this visit event is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this visit event is a draft.
	 *
	 * @return <code>true</code> if this visit event is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this visit event is expired.
	 *
	 * @return <code>true</code> if this visit event is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this visit event is inactive.
	 *
	 * @return <code>true</code> if this visit event is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this visit event is incomplete.
	 *
	 * @return <code>true</code> if this visit event is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this visit event is pending.
	 *
	 * @return <code>true</code> if this visit event is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this visit event is scheduled.
	 *
	 * @return <code>true</code> if this visit event is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}