/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the VisitDefinition service. Represents a row in the &quot;EDC_VisitDefinition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dhsoft.edc.backend.model.impl.VisitDefinitionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dhsoft.edc.backend.model.impl.VisitDefinitionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VisitDefinition
 * @generated
 */
@ProviderType
public interface VisitDefinitionModel
	extends BaseModel<VisitDefinition>, GroupedModel, ShardedModel,
			StagedAuditedModel, TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a visit definition model instance should use the {@link VisitDefinition} interface instead.
	 */

	/**
	 * Returns the primary key of this visit definition.
	 *
	 * @return the primary key of this visit definition
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this visit definition.
	 *
	 * @param primaryKey the primary key of this visit definition
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this visit definition.
	 *
	 * @return the uuid of this visit definition
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this visit definition.
	 *
	 * @param uuid the uuid of this visit definition
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the visit definition ID of this visit definition.
	 *
	 * @return the visit definition ID of this visit definition
	 */
	public long getVisitDefinitionId();

	/**
	 * Sets the visit definition ID of this visit definition.
	 *
	 * @param visitDefinitionId the visit definition ID of this visit definition
	 */
	public void setVisitDefinitionId(long visitDefinitionId);

	/**
	 * Returns the group ID of this visit definition.
	 *
	 * @return the group ID of this visit definition
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this visit definition.
	 *
	 * @param groupId the group ID of this visit definition
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this visit definition.
	 *
	 * @return the company ID of this visit definition
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this visit definition.
	 *
	 * @param companyId the company ID of this visit definition
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this visit definition.
	 *
	 * @return the project ID of this visit definition
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this visit definition.
	 *
	 * @param projectId the project ID of this visit definition
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the visit group ID of this visit definition.
	 *
	 * @return the visit group ID of this visit definition
	 */
	public long getVisitGroupId();

	/**
	 * Sets the visit group ID of this visit definition.
	 *
	 * @param visitGroupId the visit group ID of this visit definition
	 */
	public void setVisitGroupId(long visitGroupId);

	/**
	 * Returns the user ID of this visit definition.
	 *
	 * @return the user ID of this visit definition
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this visit definition.
	 *
	 * @param userId the user ID of this visit definition
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this visit definition.
	 *
	 * @return the user uuid of this visit definition
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this visit definition.
	 *
	 * @param userUuid the user uuid of this visit definition
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this visit definition.
	 *
	 * @return the user name of this visit definition
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this visit definition.
	 *
	 * @param userName the user name of this visit definition
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this visit definition.
	 *
	 * @return the create date of this visit definition
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this visit definition.
	 *
	 * @param createDate the create date of this visit definition
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this visit definition.
	 *
	 * @return the modified date of this visit definition
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this visit definition.
	 *
	 * @param modifiedDate the modified date of this visit definition
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this visit definition.
	 *
	 * @return the status of this visit definition
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this visit definition.
	 *
	 * @param status the status of this visit definition
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this visit definition.
	 *
	 * @return the status by user ID of this visit definition
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this visit definition.
	 *
	 * @param statusByUserId the status by user ID of this visit definition
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this visit definition.
	 *
	 * @return the status by user uuid of this visit definition
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this visit definition.
	 *
	 * @param statusByUserUuid the status by user uuid of this visit definition
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this visit definition.
	 *
	 * @return the status by user name of this visit definition
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this visit definition.
	 *
	 * @param statusByUserName the status by user name of this visit definition
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this visit definition.
	 *
	 * @return the status date of this visit definition
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this visit definition.
	 *
	 * @param statusDate the status date of this visit definition
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the visit definition code of this visit definition.
	 *
	 * @return the visit definition code of this visit definition
	 */
	@AutoEscape
	public String getVisitDefinitionCode();

	/**
	 * Sets the visit definition code of this visit definition.
	 *
	 * @param visitDefinitionCode the visit definition code of this visit definition
	 */
	public void setVisitDefinitionCode(String visitDefinitionCode);

	/**
	 * Returns the name of this visit definition.
	 *
	 * @return the name of this visit definition
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this visit definition.
	 *
	 * @param name the name of this visit definition
	 */
	public void setName(String name);

	/**
	 * Returns the order of this visit definition.
	 *
	 * @return the order of this visit definition
	 */
	public int getOrder();

	/**
	 * Sets the order of this visit definition.
	 *
	 * @param order the order of this visit definition
	 */
	public void setOrder(int order);

	/**
	 * Returns the anchor type of this visit definition.
	 *
	 * @return the anchor type of this visit definition
	 */
	@AutoEscape
	public String getAnchorType();

	/**
	 * Sets the anchor type of this visit definition.
	 *
	 * @param anchorType the anchor type of this visit definition
	 */
	public void setAnchorType(String anchorType);

	/**
	 * Returns the offset of this visit definition.
	 *
	 * @return the offset of this visit definition
	 */
	public int getOffset();

	/**
	 * Sets the offset of this visit definition.
	 *
	 * @param offset the offset of this visit definition
	 */
	public void setOffset(int offset);

	/**
	 * Returns the window minus of this visit definition.
	 *
	 * @return the window minus of this visit definition
	 */
	public int getWindowMinus();

	/**
	 * Sets the window minus of this visit definition.
	 *
	 * @param windowMinus the window minus of this visit definition
	 */
	public void setWindowMinus(int windowMinus);

	/**
	 * Returns the window plus of this visit definition.
	 *
	 * @return the window plus of this visit definition
	 */
	public int getWindowPlus();

	/**
	 * Sets the window plus of this visit definition.
	 *
	 * @param windowPlus the window plus of this visit definition
	 */
	public void setWindowPlus(int windowPlus);

	/**
	 * Returns the type of this visit definition.
	 *
	 * @return the type of this visit definition
	 */
	public int getType();

	/**
	 * Sets the type of this visit definition.
	 *
	 * @param type the type of this visit definition
	 */
	public void setType(int type);

	/**
	 * Returns the repeat count of this visit definition.
	 *
	 * @return the repeat count of this visit definition
	 */
	public int getRepeatCount();

	/**
	 * Sets the repeat count of this visit definition.
	 *
	 * @param repeatCount the repeat count of this visit definition
	 */
	public void setRepeatCount(int repeatCount);

	/**
	 * Returns the visit crf ID of this visit definition.
	 *
	 * @return the visit crf ID of this visit definition
	 */
	public long getVisitCRFId();

	/**
	 * Sets the visit crf ID of this visit definition.
	 *
	 * @param visitCRFId the visit crf ID of this visit definition
	 */
	public void setVisitCRFId(long visitCRFId);

	/**
	 * Returns the trash entry created when this visit definition was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this visit definition.
	 *
	 * @return the trash entry created when this visit definition was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this visit definition.
	 *
	 * @return the class primary key of the trash entry for this visit definition
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this visit definition.
	 *
	 * @return the trash handler for this visit definition
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this visit definition is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this visit definition is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this visit definition is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this visit definition is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this visit definition is approved.
	 *
	 * @return <code>true</code> if this visit definition is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this visit definition is denied.
	 *
	 * @return <code>true</code> if this visit definition is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this visit definition is a draft.
	 *
	 * @return <code>true</code> if this visit definition is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this visit definition is expired.
	 *
	 * @return <code>true</code> if this visit definition is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this visit definition is inactive.
	 *
	 * @return <code>true</code> if this visit definition is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this visit definition is incomplete.
	 *
	 * @return <code>true</code> if this visit definition is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this visit definition is pending.
	 *
	 * @return <code>true</code> if this visit definition is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this visit definition is scheduled.
	 *
	 * @return <code>true</code> if this visit definition is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}