/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.ApprovalRequest;
import com.dhsoft.edc.backend.model.ApprovalRequestModel;
import com.dhsoft.edc.backend.model.ApprovalRequestSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApprovalRequest service. Represents a row in the &quot;EDC_ApprovalRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApprovalRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApprovalRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApprovalRequestImpl
 * @generated
 */
@JSON(strict = true)
public class ApprovalRequestModelImpl
	extends BaseModelImpl<ApprovalRequest> implements ApprovalRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a approval request model instance should use the <code>ApprovalRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_ApprovalRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"approvalRequestId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"requestUserId", Types.BIGINT},
		{"requestUserName", Types.VARCHAR}, {"requestDate", Types.TIMESTAMP},
		{"targetUsersId", Types.VARCHAR}, {"className", Types.VARCHAR},
		{"classPK", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("approvalRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("requestUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("requestUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("targetUsersId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("className", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_ApprovalRequest (uuid_ VARCHAR(75) null,approvalRequestId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,requestUserId LONG,requestUserName VARCHAR(75) null,requestDate DATE null,targetUsersId VARCHAR(75) null,className VARCHAR(75) null,classPK LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table EDC_ApprovalRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY approvalRequest.approvalRequestId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_ApprovalRequest.approvalRequestId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CLASSNAME_COLUMN_BITMASK = 1L;

	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long PROJECTID_COLUMN_BITMASK = 16L;

	public static final long STATUS_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static final long APPROVALREQUESTID_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ApprovalRequest toModel(ApprovalRequestSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ApprovalRequest model = new ApprovalRequestImpl();

		model.setUuid(soapModel.getUuid());
		model.setApprovalRequestId(soapModel.getApprovalRequestId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setRequestUserId(soapModel.getRequestUserId());
		model.setRequestUserName(soapModel.getRequestUserName());
		model.setRequestDate(soapModel.getRequestDate());
		model.setTargetUsersId(soapModel.getTargetUsersId());
		model.setClassName(soapModel.getClassName());
		model.setClassPK(soapModel.getClassPK());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ApprovalRequest> toModels(
		ApprovalRequestSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ApprovalRequest> models = new ArrayList<ApprovalRequest>(
			soapModels.length);

		for (ApprovalRequestSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ApprovalRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _approvalRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setApprovalRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _approvalRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApprovalRequest.class;
	}

	@Override
	public String getModelClassName() {
		return ApprovalRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApprovalRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApprovalRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApprovalRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ApprovalRequest)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApprovalRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApprovalRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApprovalRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApprovalRequest, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApprovalRequest, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ApprovalRequest, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ApprovalRequest, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ApprovalRequest, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ApprovalRequest, Object>>();
		Map<String, BiConsumer<ApprovalRequest, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ApprovalRequest, ?>>();

		attributeGetterFunctions.put("uuid", ApprovalRequest::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ApprovalRequest, String>)ApprovalRequest::setUuid);
		attributeGetterFunctions.put(
			"approvalRequestId", ApprovalRequest::getApprovalRequestId);
		attributeSetterBiConsumers.put(
			"approvalRequestId",
			(BiConsumer<ApprovalRequest, Long>)
				ApprovalRequest::setApprovalRequestId);
		attributeGetterFunctions.put("groupId", ApprovalRequest::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ApprovalRequest, Long>)ApprovalRequest::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ApprovalRequest::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ApprovalRequest, Long>)ApprovalRequest::setCompanyId);
		attributeGetterFunctions.put(
			"projectId", ApprovalRequest::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<ApprovalRequest, Long>)ApprovalRequest::setProjectId);
		attributeGetterFunctions.put("status", ApprovalRequest::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<ApprovalRequest, Integer>)ApprovalRequest::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", ApprovalRequest::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<ApprovalRequest, Long>)
				ApprovalRequest::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", ApprovalRequest::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<ApprovalRequest, String>)
				ApprovalRequest::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", ApprovalRequest::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<ApprovalRequest, Date>)ApprovalRequest::setStatusDate);
		attributeGetterFunctions.put(
			"requestUserId", ApprovalRequest::getRequestUserId);
		attributeSetterBiConsumers.put(
			"requestUserId",
			(BiConsumer<ApprovalRequest, Long>)
				ApprovalRequest::setRequestUserId);
		attributeGetterFunctions.put(
			"requestUserName", ApprovalRequest::getRequestUserName);
		attributeSetterBiConsumers.put(
			"requestUserName",
			(BiConsumer<ApprovalRequest, String>)
				ApprovalRequest::setRequestUserName);
		attributeGetterFunctions.put(
			"requestDate", ApprovalRequest::getRequestDate);
		attributeSetterBiConsumers.put(
			"requestDate",
			(BiConsumer<ApprovalRequest, Date>)ApprovalRequest::setRequestDate);
		attributeGetterFunctions.put(
			"targetUsersId", ApprovalRequest::getTargetUsersId);
		attributeSetterBiConsumers.put(
			"targetUsersId",
			(BiConsumer<ApprovalRequest, String>)
				ApprovalRequest::setTargetUsersId);
		attributeGetterFunctions.put(
			"className", ApprovalRequest::getClassName);
		attributeSetterBiConsumers.put(
			"className",
			(BiConsumer<ApprovalRequest, String>)ApprovalRequest::setClassName);
		attributeGetterFunctions.put("classPK", ApprovalRequest::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<ApprovalRequest, Long>)ApprovalRequest::setClassPK);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getApprovalRequestId() {
		return _approvalRequestId;
	}

	@Override
	public void setApprovalRequestId(long approvalRequestId) {
		_approvalRequestId = approvalRequestId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public long getRequestUserId() {
		return _requestUserId;
	}

	@Override
	public void setRequestUserId(long requestUserId) {
		_requestUserId = requestUserId;
	}

	@Override
	public String getRequestUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getRequestUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setRequestUserUuid(String requestUserUuid) {
	}

	@JSON
	@Override
	public String getRequestUserName() {
		if (_requestUserName == null) {
			return "";
		}
		else {
			return _requestUserName;
		}
	}

	@Override
	public void setRequestUserName(String requestUserName) {
		_requestUserName = requestUserName;
	}

	@JSON
	@Override
	public Date getRequestDate() {
		return _requestDate;
	}

	@Override
	public void setRequestDate(Date requestDate) {
		_requestDate = requestDate;
	}

	@JSON
	@Override
	public String getTargetUsersId() {
		if (_targetUsersId == null) {
			return "";
		}
		else {
			return _targetUsersId;
		}
	}

	@Override
	public void setTargetUsersId(String targetUsersId) {
		_targetUsersId = targetUsersId;
	}

	@JSON
	@Override
	public String getClassName() {
		if (_className == null) {
			return "";
		}
		else {
			return _className;
		}
	}

	@Override
	public void setClassName(String className) {
		_columnBitmask |= CLASSNAME_COLUMN_BITMASK;

		if (_originalClassName == null) {
			_originalClassName = _className;
		}

		_className = className;
	}

	public String getOriginalClassName() {
		return GetterUtil.getString(_originalClassName);
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ApprovalRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ApprovalRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApprovalRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApprovalRequestImpl approvalRequestImpl = new ApprovalRequestImpl();

		approvalRequestImpl.setUuid(getUuid());
		approvalRequestImpl.setApprovalRequestId(getApprovalRequestId());
		approvalRequestImpl.setGroupId(getGroupId());
		approvalRequestImpl.setCompanyId(getCompanyId());
		approvalRequestImpl.setProjectId(getProjectId());
		approvalRequestImpl.setStatus(getStatus());
		approvalRequestImpl.setStatusByUserId(getStatusByUserId());
		approvalRequestImpl.setStatusByUserName(getStatusByUserName());
		approvalRequestImpl.setStatusDate(getStatusDate());
		approvalRequestImpl.setRequestUserId(getRequestUserId());
		approvalRequestImpl.setRequestUserName(getRequestUserName());
		approvalRequestImpl.setRequestDate(getRequestDate());
		approvalRequestImpl.setTargetUsersId(getTargetUsersId());
		approvalRequestImpl.setClassName(getClassName());
		approvalRequestImpl.setClassPK(getClassPK());

		approvalRequestImpl.resetOriginalValues();

		return approvalRequestImpl;
	}

	@Override
	public int compareTo(ApprovalRequest approvalRequest) {
		long primaryKey = approvalRequest.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApprovalRequest)) {
			return false;
		}

		ApprovalRequest approvalRequest = (ApprovalRequest)object;

		long primaryKey = approvalRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalStatus = _status;

		_setOriginalStatus = false;

		_originalClassName = _className;

		_originalClassPK = _classPK;

		_setOriginalClassPK = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApprovalRequest> toCacheModel() {
		ApprovalRequestCacheModel approvalRequestCacheModel =
			new ApprovalRequestCacheModel();

		approvalRequestCacheModel.uuid = getUuid();

		String uuid = approvalRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			approvalRequestCacheModel.uuid = null;
		}

		approvalRequestCacheModel.approvalRequestId = getApprovalRequestId();

		approvalRequestCacheModel.groupId = getGroupId();

		approvalRequestCacheModel.companyId = getCompanyId();

		approvalRequestCacheModel.projectId = getProjectId();

		approvalRequestCacheModel.status = getStatus();

		approvalRequestCacheModel.statusByUserId = getStatusByUserId();

		approvalRequestCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = approvalRequestCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			approvalRequestCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			approvalRequestCacheModel.statusDate = statusDate.getTime();
		}
		else {
			approvalRequestCacheModel.statusDate = Long.MIN_VALUE;
		}

		approvalRequestCacheModel.requestUserId = getRequestUserId();

		approvalRequestCacheModel.requestUserName = getRequestUserName();

		String requestUserName = approvalRequestCacheModel.requestUserName;

		if ((requestUserName != null) && (requestUserName.length() == 0)) {
			approvalRequestCacheModel.requestUserName = null;
		}

		Date requestDate = getRequestDate();

		if (requestDate != null) {
			approvalRequestCacheModel.requestDate = requestDate.getTime();
		}
		else {
			approvalRequestCacheModel.requestDate = Long.MIN_VALUE;
		}

		approvalRequestCacheModel.targetUsersId = getTargetUsersId();

		String targetUsersId = approvalRequestCacheModel.targetUsersId;

		if ((targetUsersId != null) && (targetUsersId.length() == 0)) {
			approvalRequestCacheModel.targetUsersId = null;
		}

		approvalRequestCacheModel.className = getClassName();

		String className = approvalRequestCacheModel.className;

		if ((className != null) && (className.length() == 0)) {
			approvalRequestCacheModel.className = null;
		}

		approvalRequestCacheModel.classPK = getClassPK();

		return approvalRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApprovalRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApprovalRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApprovalRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ApprovalRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ApprovalRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ApprovalRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApprovalRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ApprovalRequest)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ApprovalRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ApprovalRequest.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _approvalRequestId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _requestUserId;
	private String _requestUserName;
	private Date _requestDate;
	private String _targetUsersId;
	private String _className;
	private String _originalClassName;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private long _columnBitmask;
	private ApprovalRequest _escapedModel;

}