/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.AssignInstitutionRole;
import com.dhsoft.edc.backend.model.AssignInstitutionRoleModel;
import com.dhsoft.edc.backend.model.AssignInstitutionRoleSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AssignInstitutionRole service. Represents a row in the &quot;EDC_AssignInstitutionRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AssignInstitutionRoleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssignInstitutionRoleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssignInstitutionRoleImpl
 * @generated
 */
@JSON(strict = true)
public class AssignInstitutionRoleModelImpl
	extends BaseModelImpl<AssignInstitutionRole>
	implements AssignInstitutionRoleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assign institution role model instance should use the <code>AssignInstitutionRole</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_AssignInstitutionRole";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"institutionRoleId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"institutionId", Types.BIGINT}, {"researcherId", Types.BIGINT},
		{"targetUserId", Types.BIGINT}, {"roleName", Types.VARCHAR},
		{"active_", Types.BOOLEAN}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"createdBy", Types.BIGINT},
		{"modifiedBy", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("institutionRoleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("institutionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("researcherId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("targetUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_AssignInstitutionRole (uuid_ VARCHAR(75) null,institutionRoleId LONG not null primary key,companyId LONG,groupId LONG,institutionId LONG,researcherId LONG,targetUserId LONG,roleName VARCHAR(75) null,active_ BOOLEAN,createDate DATE null,modifiedDate DATE null,createdBy LONG,modifiedBy LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table EDC_AssignInstitutionRole";

	public static final String ORDER_BY_JPQL =
		" ORDER BY assignInstitutionRole.roleName ASC, assignInstitutionRole.targetUserId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_AssignInstitutionRole.roleName ASC, EDC_AssignInstitutionRole.targetUserId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long INSTITUTIONID_COLUMN_BITMASK = 4L;

	public static final long ROLENAME_COLUMN_BITMASK = 8L;

	public static final long TARGETUSERID_COLUMN_BITMASK = 16L;

	public static final long UUID_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AssignInstitutionRole toModel(
		AssignInstitutionRoleSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		AssignInstitutionRole model = new AssignInstitutionRoleImpl();

		model.setUuid(soapModel.getUuid());
		model.setInstitutionRoleId(soapModel.getInstitutionRoleId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setInstitutionId(soapModel.getInstitutionId());
		model.setResearcherId(soapModel.getResearcherId());
		model.setTargetUserId(soapModel.getTargetUserId());
		model.setRoleName(soapModel.getRoleName());
		model.setActive(soapModel.isActive());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setModifiedBy(soapModel.getModifiedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AssignInstitutionRole> toModels(
		AssignInstitutionRoleSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<AssignInstitutionRole> models =
			new ArrayList<AssignInstitutionRole>(soapModels.length);

		for (AssignInstitutionRoleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public AssignInstitutionRoleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _institutionRoleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInstitutionRoleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _institutionRoleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssignInstitutionRole.class;
	}

	@Override
	public String getModelClassName() {
		return AssignInstitutionRole.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AssignInstitutionRole, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AssignInstitutionRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssignInstitutionRole, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AssignInstitutionRole)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AssignInstitutionRole, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AssignInstitutionRole, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AssignInstitutionRole)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AssignInstitutionRole, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AssignInstitutionRole, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AssignInstitutionRole, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AssignInstitutionRole, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AssignInstitutionRole, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AssignInstitutionRole, Object>>();
		Map<String, BiConsumer<AssignInstitutionRole, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<AssignInstitutionRole, ?>>();

		attributeGetterFunctions.put("uuid", AssignInstitutionRole::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<AssignInstitutionRole, String>)
				AssignInstitutionRole::setUuid);
		attributeGetterFunctions.put(
			"institutionRoleId", AssignInstitutionRole::getInstitutionRoleId);
		attributeSetterBiConsumers.put(
			"institutionRoleId",
			(BiConsumer<AssignInstitutionRole, Long>)
				AssignInstitutionRole::setInstitutionRoleId);
		attributeGetterFunctions.put(
			"companyId", AssignInstitutionRole::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AssignInstitutionRole, Long>)
				AssignInstitutionRole::setCompanyId);
		attributeGetterFunctions.put(
			"groupId", AssignInstitutionRole::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AssignInstitutionRole, Long>)
				AssignInstitutionRole::setGroupId);
		attributeGetterFunctions.put(
			"institutionId", AssignInstitutionRole::getInstitutionId);
		attributeSetterBiConsumers.put(
			"institutionId",
			(BiConsumer<AssignInstitutionRole, Long>)
				AssignInstitutionRole::setInstitutionId);
		attributeGetterFunctions.put(
			"researcherId", AssignInstitutionRole::getResearcherId);
		attributeSetterBiConsumers.put(
			"researcherId",
			(BiConsumer<AssignInstitutionRole, Long>)
				AssignInstitutionRole::setResearcherId);
		attributeGetterFunctions.put(
			"targetUserId", AssignInstitutionRole::getTargetUserId);
		attributeSetterBiConsumers.put(
			"targetUserId",
			(BiConsumer<AssignInstitutionRole, Long>)
				AssignInstitutionRole::setTargetUserId);
		attributeGetterFunctions.put(
			"roleName", AssignInstitutionRole::getRoleName);
		attributeSetterBiConsumers.put(
			"roleName",
			(BiConsumer<AssignInstitutionRole, String>)
				AssignInstitutionRole::setRoleName);
		attributeGetterFunctions.put(
			"active", AssignInstitutionRole::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<AssignInstitutionRole, Boolean>)
				AssignInstitutionRole::setActive);
		attributeGetterFunctions.put(
			"createDate", AssignInstitutionRole::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AssignInstitutionRole, Date>)
				AssignInstitutionRole::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AssignInstitutionRole::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AssignInstitutionRole, Date>)
				AssignInstitutionRole::setModifiedDate);
		attributeGetterFunctions.put(
			"createdBy", AssignInstitutionRole::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<AssignInstitutionRole, Long>)
				AssignInstitutionRole::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", AssignInstitutionRole::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<AssignInstitutionRole, Long>)
				AssignInstitutionRole::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getInstitutionRoleId() {
		return _institutionRoleId;
	}

	@Override
	public void setInstitutionRoleId(long institutionRoleId) {
		_institutionRoleId = institutionRoleId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@JSON
	@Override
	public long getResearcherId() {
		return _researcherId;
	}

	@Override
	public void setResearcherId(long researcherId) {
		_researcherId = researcherId;
	}

	@JSON
	@Override
	public long getTargetUserId() {
		return _targetUserId;
	}

	@Override
	public void setTargetUserId(long targetUserId) {
		_columnBitmask = -1L;

		if (!_setOriginalTargetUserId) {
			_setOriginalTargetUserId = true;

			_originalTargetUserId = _targetUserId;
		}

		_targetUserId = targetUserId;
	}

	@Override
	public String getTargetUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getTargetUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setTargetUserUuid(String targetUserUuid) {
	}

	public long getOriginalTargetUserId() {
		return _originalTargetUserId;
	}

	@JSON
	@Override
	public String getRoleName() {
		if (_roleName == null) {
			return "";
		}
		else {
			return _roleName;
		}
	}

	@Override
	public void setRoleName(String roleName) {
		_columnBitmask = -1L;

		if (_originalRoleName == null) {
			_originalRoleName = _roleName;
		}

		_roleName = roleName;
	}

	public String getOriginalRoleName() {
		return GetterUtil.getString(_originalRoleName);
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_active = active;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AssignInstitutionRole.class.getName()));
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AssignInstitutionRole.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssignInstitutionRole toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AssignInstitutionRole>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssignInstitutionRoleImpl assignInstitutionRoleImpl =
			new AssignInstitutionRoleImpl();

		assignInstitutionRoleImpl.setUuid(getUuid());
		assignInstitutionRoleImpl.setInstitutionRoleId(getInstitutionRoleId());
		assignInstitutionRoleImpl.setCompanyId(getCompanyId());
		assignInstitutionRoleImpl.setGroupId(getGroupId());
		assignInstitutionRoleImpl.setInstitutionId(getInstitutionId());
		assignInstitutionRoleImpl.setResearcherId(getResearcherId());
		assignInstitutionRoleImpl.setTargetUserId(getTargetUserId());
		assignInstitutionRoleImpl.setRoleName(getRoleName());
		assignInstitutionRoleImpl.setActive(isActive());
		assignInstitutionRoleImpl.setCreateDate(getCreateDate());
		assignInstitutionRoleImpl.setModifiedDate(getModifiedDate());
		assignInstitutionRoleImpl.setCreatedBy(getCreatedBy());
		assignInstitutionRoleImpl.setModifiedBy(getModifiedBy());

		assignInstitutionRoleImpl.resetOriginalValues();

		return assignInstitutionRoleImpl;
	}

	@Override
	public int compareTo(AssignInstitutionRole assignInstitutionRole) {
		int value = 0;

		value = getRoleName().compareTo(assignInstitutionRole.getRoleName());

		if (value != 0) {
			return value;
		}

		if (getTargetUserId() < assignInstitutionRole.getTargetUserId()) {
			value = -1;
		}
		else if (getTargetUserId() > assignInstitutionRole.getTargetUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AssignInstitutionRole)) {
			return false;
		}

		AssignInstitutionRole assignInstitutionRole =
			(AssignInstitutionRole)object;

		long primaryKey = assignInstitutionRole.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalInstitutionId = _institutionId;

		_setOriginalInstitutionId = false;

		_originalTargetUserId = _targetUserId;

		_setOriginalTargetUserId = false;

		_originalRoleName = _roleName;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AssignInstitutionRole> toCacheModel() {
		AssignInstitutionRoleCacheModel assignInstitutionRoleCacheModel =
			new AssignInstitutionRoleCacheModel();

		assignInstitutionRoleCacheModel.uuid = getUuid();

		String uuid = assignInstitutionRoleCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			assignInstitutionRoleCacheModel.uuid = null;
		}

		assignInstitutionRoleCacheModel.institutionRoleId =
			getInstitutionRoleId();

		assignInstitutionRoleCacheModel.companyId = getCompanyId();

		assignInstitutionRoleCacheModel.groupId = getGroupId();

		assignInstitutionRoleCacheModel.institutionId = getInstitutionId();

		assignInstitutionRoleCacheModel.researcherId = getResearcherId();

		assignInstitutionRoleCacheModel.targetUserId = getTargetUserId();

		assignInstitutionRoleCacheModel.roleName = getRoleName();

		String roleName = assignInstitutionRoleCacheModel.roleName;

		if ((roleName != null) && (roleName.length() == 0)) {
			assignInstitutionRoleCacheModel.roleName = null;
		}

		assignInstitutionRoleCacheModel.active = isActive();

		Date createDate = getCreateDate();

		if (createDate != null) {
			assignInstitutionRoleCacheModel.createDate = createDate.getTime();
		}
		else {
			assignInstitutionRoleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			assignInstitutionRoleCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			assignInstitutionRoleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		assignInstitutionRoleCacheModel.createdBy = getCreatedBy();

		assignInstitutionRoleCacheModel.modifiedBy = getModifiedBy();

		return assignInstitutionRoleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AssignInstitutionRole, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AssignInstitutionRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssignInstitutionRole, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AssignInstitutionRole)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AssignInstitutionRole, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AssignInstitutionRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssignInstitutionRole, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((AssignInstitutionRole)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AssignInstitutionRole>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AssignInstitutionRole.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _institutionRoleId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _researcherId;
	private long _targetUserId;
	private long _originalTargetUserId;
	private boolean _setOriginalTargetUserId;
	private String _roleName;
	private String _originalRoleName;
	private boolean _active;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdBy;
	private long _modifiedBy;
	private long _columnBitmask;
	private AssignInstitutionRole _escapedModel;

}