/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.AssignAudit;
import com.dhsoft.edc.backend.model.AssignAuditModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AssignAudit service. Represents a row in the &quot;EDC_AssignAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AssignAuditModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssignAuditImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssignAuditImpl
 * @generated
 */
public class AssignAuditModelImpl
	extends BaseModelImpl<AssignAudit> implements AssignAuditModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assign audit model instance should use the <code>AssignAudit</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_AssignAudit";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"auditId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"institutionId", Types.BIGINT},
		{"researcherId", Types.BIGINT}, {"projectId", Types.BIGINT},
		{"action", Types.VARCHAR}, {"targetUserId", Types.BIGINT},
		{"roleOrScope", Types.VARCHAR}, {"payload", Types.VARCHAR},
		{"actorUserId", Types.BIGINT}, {"actorUserName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("auditId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("institutionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("researcherId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("action", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("targetUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleOrScope", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("payload", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("actorUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("actorUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_AssignAudit (uuid_ VARCHAR(75) null,auditId LONG not null primary key,companyId LONG,institutionId LONG,researcherId LONG,projectId LONG,action VARCHAR(75) null,targetUserId LONG,roleOrScope VARCHAR(75) null,payload VARCHAR(75) null,actorUserId LONG,actorUserName VARCHAR(75) null,createDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table EDC_AssignAudit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY assignAudit.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_AssignAudit.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long INSTITUTIONID_COLUMN_BITMASK = 2L;

	public static final long PROJECTID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public AssignAuditModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _auditId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _auditId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssignAudit.class;
	}

	@Override
	public String getModelClassName() {
		return AssignAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AssignAudit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AssignAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssignAudit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AssignAudit)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AssignAudit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AssignAudit, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AssignAudit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AssignAudit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AssignAudit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AssignAudit, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AssignAudit, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AssignAudit, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AssignAudit, Object>>();
		Map<String, BiConsumer<AssignAudit, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AssignAudit, ?>>();

		attributeGetterFunctions.put("uuid", AssignAudit::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<AssignAudit, String>)AssignAudit::setUuid);
		attributeGetterFunctions.put("auditId", AssignAudit::getAuditId);
		attributeSetterBiConsumers.put(
			"auditId", (BiConsumer<AssignAudit, Long>)AssignAudit::setAuditId);
		attributeGetterFunctions.put("companyId", AssignAudit::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AssignAudit, Long>)AssignAudit::setCompanyId);
		attributeGetterFunctions.put(
			"institutionId", AssignAudit::getInstitutionId);
		attributeSetterBiConsumers.put(
			"institutionId",
			(BiConsumer<AssignAudit, Long>)AssignAudit::setInstitutionId);
		attributeGetterFunctions.put(
			"researcherId", AssignAudit::getResearcherId);
		attributeSetterBiConsumers.put(
			"researcherId",
			(BiConsumer<AssignAudit, Long>)AssignAudit::setResearcherId);
		attributeGetterFunctions.put("projectId", AssignAudit::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<AssignAudit, Long>)AssignAudit::setProjectId);
		attributeGetterFunctions.put("action", AssignAudit::getAction);
		attributeSetterBiConsumers.put(
			"action", (BiConsumer<AssignAudit, String>)AssignAudit::setAction);
		attributeGetterFunctions.put(
			"targetUserId", AssignAudit::getTargetUserId);
		attributeSetterBiConsumers.put(
			"targetUserId",
			(BiConsumer<AssignAudit, Long>)AssignAudit::setTargetUserId);
		attributeGetterFunctions.put(
			"roleOrScope", AssignAudit::getRoleOrScope);
		attributeSetterBiConsumers.put(
			"roleOrScope",
			(BiConsumer<AssignAudit, String>)AssignAudit::setRoleOrScope);
		attributeGetterFunctions.put("payload", AssignAudit::getPayload);
		attributeSetterBiConsumers.put(
			"payload",
			(BiConsumer<AssignAudit, String>)AssignAudit::setPayload);
		attributeGetterFunctions.put(
			"actorUserId", AssignAudit::getActorUserId);
		attributeSetterBiConsumers.put(
			"actorUserId",
			(BiConsumer<AssignAudit, Long>)AssignAudit::setActorUserId);
		attributeGetterFunctions.put(
			"actorUserName", AssignAudit::getActorUserName);
		attributeSetterBiConsumers.put(
			"actorUserName",
			(BiConsumer<AssignAudit, String>)AssignAudit::setActorUserName);
		attributeGetterFunctions.put("createDate", AssignAudit::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AssignAudit, Date>)AssignAudit::setCreateDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getAuditId() {
		return _auditId;
	}

	@Override
	public void setAuditId(long auditId) {
		_auditId = auditId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@Override
	public long getResearcherId() {
		return _researcherId;
	}

	@Override
	public void setResearcherId(long researcherId) {
		_researcherId = researcherId;
	}

	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@Override
	public String getAction() {
		if (_action == null) {
			return "";
		}
		else {
			return _action;
		}
	}

	@Override
	public void setAction(String action) {
		_action = action;
	}

	@Override
	public long getTargetUserId() {
		return _targetUserId;
	}

	@Override
	public void setTargetUserId(long targetUserId) {
		_targetUserId = targetUserId;
	}

	@Override
	public String getTargetUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getTargetUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setTargetUserUuid(String targetUserUuid) {
	}

	@Override
	public String getRoleOrScope() {
		if (_roleOrScope == null) {
			return "";
		}
		else {
			return _roleOrScope;
		}
	}

	@Override
	public void setRoleOrScope(String roleOrScope) {
		_roleOrScope = roleOrScope;
	}

	@Override
	public String getPayload() {
		if (_payload == null) {
			return "";
		}
		else {
			return _payload;
		}
	}

	@Override
	public void setPayload(String payload) {
		_payload = payload;
	}

	@Override
	public long getActorUserId() {
		return _actorUserId;
	}

	@Override
	public void setActorUserId(long actorUserId) {
		_actorUserId = actorUserId;
	}

	@Override
	public String getActorUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getActorUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setActorUserUuid(String actorUserUuid) {
	}

	@Override
	public String getActorUserName() {
		if (_actorUserName == null) {
			return "";
		}
		else {
			return _actorUserName;
		}
	}

	@Override
	public void setActorUserName(String actorUserName) {
		_actorUserName = actorUserName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AssignAudit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssignAudit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AssignAudit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssignAuditImpl assignAuditImpl = new AssignAuditImpl();

		assignAuditImpl.setUuid(getUuid());
		assignAuditImpl.setAuditId(getAuditId());
		assignAuditImpl.setCompanyId(getCompanyId());
		assignAuditImpl.setInstitutionId(getInstitutionId());
		assignAuditImpl.setResearcherId(getResearcherId());
		assignAuditImpl.setProjectId(getProjectId());
		assignAuditImpl.setAction(getAction());
		assignAuditImpl.setTargetUserId(getTargetUserId());
		assignAuditImpl.setRoleOrScope(getRoleOrScope());
		assignAuditImpl.setPayload(getPayload());
		assignAuditImpl.setActorUserId(getActorUserId());
		assignAuditImpl.setActorUserName(getActorUserName());
		assignAuditImpl.setCreateDate(getCreateDate());

		assignAuditImpl.resetOriginalValues();

		return assignAuditImpl;
	}

	@Override
	public int compareTo(AssignAudit assignAudit) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), assignAudit.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AssignAudit)) {
			return false;
		}

		AssignAudit assignAudit = (AssignAudit)object;

		long primaryKey = assignAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalInstitutionId = _institutionId;

		_setOriginalInstitutionId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AssignAudit> toCacheModel() {
		AssignAuditCacheModel assignAuditCacheModel =
			new AssignAuditCacheModel();

		assignAuditCacheModel.uuid = getUuid();

		String uuid = assignAuditCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			assignAuditCacheModel.uuid = null;
		}

		assignAuditCacheModel.auditId = getAuditId();

		assignAuditCacheModel.companyId = getCompanyId();

		assignAuditCacheModel.institutionId = getInstitutionId();

		assignAuditCacheModel.researcherId = getResearcherId();

		assignAuditCacheModel.projectId = getProjectId();

		assignAuditCacheModel.action = getAction();

		String action = assignAuditCacheModel.action;

		if ((action != null) && (action.length() == 0)) {
			assignAuditCacheModel.action = null;
		}

		assignAuditCacheModel.targetUserId = getTargetUserId();

		assignAuditCacheModel.roleOrScope = getRoleOrScope();

		String roleOrScope = assignAuditCacheModel.roleOrScope;

		if ((roleOrScope != null) && (roleOrScope.length() == 0)) {
			assignAuditCacheModel.roleOrScope = null;
		}

		assignAuditCacheModel.payload = getPayload();

		String payload = assignAuditCacheModel.payload;

		if ((payload != null) && (payload.length() == 0)) {
			assignAuditCacheModel.payload = null;
		}

		assignAuditCacheModel.actorUserId = getActorUserId();

		assignAuditCacheModel.actorUserName = getActorUserName();

		String actorUserName = assignAuditCacheModel.actorUserName;

		if ((actorUserName != null) && (actorUserName.length() == 0)) {
			assignAuditCacheModel.actorUserName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			assignAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			assignAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		return assignAuditCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AssignAudit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AssignAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssignAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AssignAudit)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AssignAudit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AssignAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssignAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AssignAudit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AssignAudit>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AssignAudit.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _auditId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _researcherId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private String _action;
	private long _targetUserId;
	private String _roleOrScope;
	private String _payload;
	private long _actorUserId;
	private String _actorUserName;
	private Date _createDate;
	private long _columnBitmask;
	private AssignAudit _escapedModel;

}