/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.AssignProjectScope;
import com.dhsoft.edc.backend.model.AssignProjectScopeModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AssignProjectScope service. Represents a row in the &quot;EDC_AssignProjectScope&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AssignProjectScopeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssignProjectScopeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssignProjectScopeImpl
 * @generated
 */
public class AssignProjectScopeModelImpl
	extends BaseModelImpl<AssignProjectScope>
	implements AssignProjectScopeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assign project scope model instance should use the <code>AssignProjectScope</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_AssignProjectScope";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"projectScopeId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"institutionId", Types.BIGINT}, {"researcherId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"targetUserId", Types.BIGINT},
		{"scopeRole", Types.VARCHAR}, {"active_", Types.BOOLEAN},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("projectScopeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("institutionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("researcherId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("targetUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("scopeRole", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_AssignProjectScope (uuid_ VARCHAR(75) null,projectScopeId LONG not null primary key,companyId LONG,groupId LONG,institutionId LONG,researcherId LONG,projectId LONG,targetUserId LONG,scopeRole VARCHAR(75) null,active_ BOOLEAN,createDate DATE null,modifiedDate DATE null,createdBy LONG,modifiedBy LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table EDC_AssignProjectScope";

	public static final String ORDER_BY_JPQL =
		" ORDER BY assignProjectScope.scopeRole ASC, assignProjectScope.targetUserId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_AssignProjectScope.scopeRole ASC, EDC_AssignProjectScope.targetUserId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long INSTITUTIONID_COLUMN_BITMASK = 4L;

	public static final long PROJECTID_COLUMN_BITMASK = 8L;

	public static final long SCOPEROLE_COLUMN_BITMASK = 16L;

	public static final long TARGETUSERID_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public AssignProjectScopeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _projectScopeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProjectScopeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _projectScopeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssignProjectScope.class;
	}

	@Override
	public String getModelClassName() {
		return AssignProjectScope.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AssignProjectScope, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AssignProjectScope, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssignProjectScope, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AssignProjectScope)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AssignProjectScope, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AssignProjectScope, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AssignProjectScope)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AssignProjectScope, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AssignProjectScope, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AssignProjectScope, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AssignProjectScope, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AssignProjectScope, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AssignProjectScope, Object>>();
		Map<String, BiConsumer<AssignProjectScope, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AssignProjectScope, ?>>();

		attributeGetterFunctions.put("uuid", AssignProjectScope::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<AssignProjectScope, String>)
				AssignProjectScope::setUuid);
		attributeGetterFunctions.put(
			"projectScopeId", AssignProjectScope::getProjectScopeId);
		attributeSetterBiConsumers.put(
			"projectScopeId",
			(BiConsumer<AssignProjectScope, Long>)
				AssignProjectScope::setProjectScopeId);
		attributeGetterFunctions.put(
			"companyId", AssignProjectScope::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AssignProjectScope, Long>)
				AssignProjectScope::setCompanyId);
		attributeGetterFunctions.put("groupId", AssignProjectScope::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AssignProjectScope, Long>)
				AssignProjectScope::setGroupId);
		attributeGetterFunctions.put(
			"institutionId", AssignProjectScope::getInstitutionId);
		attributeSetterBiConsumers.put(
			"institutionId",
			(BiConsumer<AssignProjectScope, Long>)
				AssignProjectScope::setInstitutionId);
		attributeGetterFunctions.put(
			"researcherId", AssignProjectScope::getResearcherId);
		attributeSetterBiConsumers.put(
			"researcherId",
			(BiConsumer<AssignProjectScope, Long>)
				AssignProjectScope::setResearcherId);
		attributeGetterFunctions.put(
			"projectId", AssignProjectScope::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<AssignProjectScope, Long>)
				AssignProjectScope::setProjectId);
		attributeGetterFunctions.put(
			"targetUserId", AssignProjectScope::getTargetUserId);
		attributeSetterBiConsumers.put(
			"targetUserId",
			(BiConsumer<AssignProjectScope, Long>)
				AssignProjectScope::setTargetUserId);
		attributeGetterFunctions.put(
			"scopeRole", AssignProjectScope::getScopeRole);
		attributeSetterBiConsumers.put(
			"scopeRole",
			(BiConsumer<AssignProjectScope, String>)
				AssignProjectScope::setScopeRole);
		attributeGetterFunctions.put("active", AssignProjectScope::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<AssignProjectScope, Boolean>)
				AssignProjectScope::setActive);
		attributeGetterFunctions.put(
			"createDate", AssignProjectScope::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AssignProjectScope, Date>)
				AssignProjectScope::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AssignProjectScope::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AssignProjectScope, Date>)
				AssignProjectScope::setModifiedDate);
		attributeGetterFunctions.put(
			"createdBy", AssignProjectScope::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<AssignProjectScope, Long>)
				AssignProjectScope::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", AssignProjectScope::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<AssignProjectScope, Long>)
				AssignProjectScope::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getProjectScopeId() {
		return _projectScopeId;
	}

	@Override
	public void setProjectScopeId(long projectScopeId) {
		_projectScopeId = projectScopeId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@Override
	public long getResearcherId() {
		return _researcherId;
	}

	@Override
	public void setResearcherId(long researcherId) {
		_researcherId = researcherId;
	}

	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@Override
	public long getTargetUserId() {
		return _targetUserId;
	}

	@Override
	public void setTargetUserId(long targetUserId) {
		_columnBitmask = -1L;

		if (!_setOriginalTargetUserId) {
			_setOriginalTargetUserId = true;

			_originalTargetUserId = _targetUserId;
		}

		_targetUserId = targetUserId;
	}

	@Override
	public String getTargetUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getTargetUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setTargetUserUuid(String targetUserUuid) {
	}

	public long getOriginalTargetUserId() {
		return _originalTargetUserId;
	}

	@Override
	public String getScopeRole() {
		if (_scopeRole == null) {
			return "";
		}
		else {
			return _scopeRole;
		}
	}

	@Override
	public void setScopeRole(String scopeRole) {
		_columnBitmask = -1L;

		if (_originalScopeRole == null) {
			_originalScopeRole = _scopeRole;
		}

		_scopeRole = scopeRole;
	}

	public String getOriginalScopeRole() {
		return GetterUtil.getString(_originalScopeRole);
	}

	@Override
	public boolean getActive() {
		return _active;
	}

	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_active = active;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AssignProjectScope.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AssignProjectScope.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssignProjectScope toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AssignProjectScope>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssignProjectScopeImpl assignProjectScopeImpl =
			new AssignProjectScopeImpl();

		assignProjectScopeImpl.setUuid(getUuid());
		assignProjectScopeImpl.setProjectScopeId(getProjectScopeId());
		assignProjectScopeImpl.setCompanyId(getCompanyId());
		assignProjectScopeImpl.setGroupId(getGroupId());
		assignProjectScopeImpl.setInstitutionId(getInstitutionId());
		assignProjectScopeImpl.setResearcherId(getResearcherId());
		assignProjectScopeImpl.setProjectId(getProjectId());
		assignProjectScopeImpl.setTargetUserId(getTargetUserId());
		assignProjectScopeImpl.setScopeRole(getScopeRole());
		assignProjectScopeImpl.setActive(isActive());
		assignProjectScopeImpl.setCreateDate(getCreateDate());
		assignProjectScopeImpl.setModifiedDate(getModifiedDate());
		assignProjectScopeImpl.setCreatedBy(getCreatedBy());
		assignProjectScopeImpl.setModifiedBy(getModifiedBy());

		assignProjectScopeImpl.resetOriginalValues();

		return assignProjectScopeImpl;
	}

	@Override
	public int compareTo(AssignProjectScope assignProjectScope) {
		int value = 0;

		value = getScopeRole().compareTo(assignProjectScope.getScopeRole());

		if (value != 0) {
			return value;
		}

		if (getTargetUserId() < assignProjectScope.getTargetUserId()) {
			value = -1;
		}
		else if (getTargetUserId() > assignProjectScope.getTargetUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AssignProjectScope)) {
			return false;
		}

		AssignProjectScope assignProjectScope = (AssignProjectScope)object;

		long primaryKey = assignProjectScope.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalInstitutionId = _institutionId;

		_setOriginalInstitutionId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalTargetUserId = _targetUserId;

		_setOriginalTargetUserId = false;

		_originalScopeRole = _scopeRole;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AssignProjectScope> toCacheModel() {
		AssignProjectScopeCacheModel assignProjectScopeCacheModel =
			new AssignProjectScopeCacheModel();

		assignProjectScopeCacheModel.uuid = getUuid();

		String uuid = assignProjectScopeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			assignProjectScopeCacheModel.uuid = null;
		}

		assignProjectScopeCacheModel.projectScopeId = getProjectScopeId();

		assignProjectScopeCacheModel.companyId = getCompanyId();

		assignProjectScopeCacheModel.groupId = getGroupId();

		assignProjectScopeCacheModel.institutionId = getInstitutionId();

		assignProjectScopeCacheModel.researcherId = getResearcherId();

		assignProjectScopeCacheModel.projectId = getProjectId();

		assignProjectScopeCacheModel.targetUserId = getTargetUserId();

		assignProjectScopeCacheModel.scopeRole = getScopeRole();

		String scopeRole = assignProjectScopeCacheModel.scopeRole;

		if ((scopeRole != null) && (scopeRole.length() == 0)) {
			assignProjectScopeCacheModel.scopeRole = null;
		}

		assignProjectScopeCacheModel.active = isActive();

		Date createDate = getCreateDate();

		if (createDate != null) {
			assignProjectScopeCacheModel.createDate = createDate.getTime();
		}
		else {
			assignProjectScopeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			assignProjectScopeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			assignProjectScopeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		assignProjectScopeCacheModel.createdBy = getCreatedBy();

		assignProjectScopeCacheModel.modifiedBy = getModifiedBy();

		return assignProjectScopeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AssignProjectScope, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AssignProjectScope, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssignProjectScope, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AssignProjectScope)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AssignProjectScope, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AssignProjectScope, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssignProjectScope, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AssignProjectScope)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AssignProjectScope>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AssignProjectScope.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _projectScopeId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _researcherId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _targetUserId;
	private long _originalTargetUserId;
	private boolean _setOriginalTargetUserId;
	private String _scopeRole;
	private String _originalScopeRole;
	private boolean _active;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdBy;
	private long _modifiedBy;
	private long _columnBitmask;
	private AssignProjectScope _escapedModel;

}