/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.EdcLock;
import com.dhsoft.edc.backend.model.EdcLockModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EdcLock service. Represents a row in the &quot;EDC_EdcLock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EdcLockModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EdcLockImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcLockImpl
 * @generated
 */
public class EdcLockModelImpl
	extends BaseModelImpl<EdcLock> implements EdcLockModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a edc lock model instance should use the <code>EdcLock</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_EdcLock";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"lockId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"lockType", Types.VARCHAR},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"comment_", Types.VARCHAR}, {"startDate", Types.TIMESTAMP},
		{"endDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lockId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lockType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("comment_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_EdcLock (uuid_ VARCHAR(75) null,lockId LONG not null primary key,companyId LONG,groupId LONG,projectId LONG,classNameId LONG,classPK LONG,lockType VARCHAR(75) null,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,comment_ VARCHAR(75) null,startDate DATE null,endDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table EDC_EdcLock";

	public static final String ORDER_BY_JPQL = " ORDER BY edcLock.lockId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_EdcLock.lockId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long LOCKTYPE_COLUMN_BITMASK = 16L;

	public static final long PROJECTID_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static final long LOCKID_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public EdcLockModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lockId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLockId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lockId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EdcLock.class;
	}

	@Override
	public String getModelClassName() {
		return EdcLock.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EdcLock, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EdcLock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcLock, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((EdcLock)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EdcLock, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EdcLock, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EdcLock)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EdcLock, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EdcLock, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EdcLock, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EdcLock, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EdcLock, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EdcLock, Object>>();
		Map<String, BiConsumer<EdcLock, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EdcLock, ?>>();

		attributeGetterFunctions.put("uuid", EdcLock::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<EdcLock, String>)EdcLock::setUuid);
		attributeGetterFunctions.put("lockId", EdcLock::getLockId);
		attributeSetterBiConsumers.put(
			"lockId", (BiConsumer<EdcLock, Long>)EdcLock::setLockId);
		attributeGetterFunctions.put("companyId", EdcLock::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<EdcLock, Long>)EdcLock::setCompanyId);
		attributeGetterFunctions.put("groupId", EdcLock::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<EdcLock, Long>)EdcLock::setGroupId);
		attributeGetterFunctions.put("projectId", EdcLock::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId", (BiConsumer<EdcLock, Long>)EdcLock::setProjectId);
		attributeGetterFunctions.put("classNameId", EdcLock::getClassNameId);
		attributeSetterBiConsumers.put(
			"classNameId", (BiConsumer<EdcLock, Long>)EdcLock::setClassNameId);
		attributeGetterFunctions.put("classPK", EdcLock::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK", (BiConsumer<EdcLock, Long>)EdcLock::setClassPK);
		attributeGetterFunctions.put("lockType", EdcLock::getLockType);
		attributeSetterBiConsumers.put(
			"lockType", (BiConsumer<EdcLock, String>)EdcLock::setLockType);
		attributeGetterFunctions.put("userId", EdcLock::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<EdcLock, Long>)EdcLock::setUserId);
		attributeGetterFunctions.put("userName", EdcLock::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<EdcLock, String>)EdcLock::setUserName);
		attributeGetterFunctions.put("createDate", EdcLock::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<EdcLock, Date>)EdcLock::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", EdcLock::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EdcLock, Date>)EdcLock::setModifiedDate);
		attributeGetterFunctions.put("comment", EdcLock::getComment);
		attributeSetterBiConsumers.put(
			"comment", (BiConsumer<EdcLock, String>)EdcLock::setComment);
		attributeGetterFunctions.put("startDate", EdcLock::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate", (BiConsumer<EdcLock, Date>)EdcLock::setStartDate);
		attributeGetterFunctions.put("endDate", EdcLock::getEndDate);
		attributeSetterBiConsumers.put(
			"endDate", (BiConsumer<EdcLock, Date>)EdcLock::setEndDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getLockId() {
		return _lockId;
	}

	@Override
	public void setLockId(long lockId) {
		_lockId = lockId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@Override
	public String getLockType() {
		if (_lockType == null) {
			return "";
		}
		else {
			return _lockType;
		}
	}

	@Override
	public void setLockType(String lockType) {
		_columnBitmask |= LOCKTYPE_COLUMN_BITMASK;

		if (_originalLockType == null) {
			_originalLockType = _lockType;
		}

		_lockType = lockType;
	}

	public String getOriginalLockType() {
		return GetterUtil.getString(_originalLockType);
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getComment() {
		if (_comment == null) {
			return "";
		}
		else {
			return _comment;
		}
	}

	@Override
	public void setComment(String comment) {
		_comment = comment;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EdcLock.class.getName()),
			getClassNameId());
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EdcLock.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EdcLock toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EdcLock>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EdcLockImpl edcLockImpl = new EdcLockImpl();

		edcLockImpl.setUuid(getUuid());
		edcLockImpl.setLockId(getLockId());
		edcLockImpl.setCompanyId(getCompanyId());
		edcLockImpl.setGroupId(getGroupId());
		edcLockImpl.setProjectId(getProjectId());
		edcLockImpl.setClassNameId(getClassNameId());
		edcLockImpl.setClassPK(getClassPK());
		edcLockImpl.setLockType(getLockType());
		edcLockImpl.setUserId(getUserId());
		edcLockImpl.setUserName(getUserName());
		edcLockImpl.setCreateDate(getCreateDate());
		edcLockImpl.setModifiedDate(getModifiedDate());
		edcLockImpl.setComment(getComment());
		edcLockImpl.setStartDate(getStartDate());
		edcLockImpl.setEndDate(getEndDate());

		edcLockImpl.resetOriginalValues();

		return edcLockImpl;
	}

	@Override
	public int compareTo(EdcLock edcLock) {
		long primaryKey = edcLock.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EdcLock)) {
			return false;
		}

		EdcLock edcLock = (EdcLock)object;

		long primaryKey = edcLock.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalClassNameId = _classNameId;

		_setOriginalClassNameId = false;

		_originalClassPK = _classPK;

		_setOriginalClassPK = false;

		_originalLockType = _lockType;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EdcLock> toCacheModel() {
		EdcLockCacheModel edcLockCacheModel = new EdcLockCacheModel();

		edcLockCacheModel.uuid = getUuid();

		String uuid = edcLockCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			edcLockCacheModel.uuid = null;
		}

		edcLockCacheModel.lockId = getLockId();

		edcLockCacheModel.companyId = getCompanyId();

		edcLockCacheModel.groupId = getGroupId();

		edcLockCacheModel.projectId = getProjectId();

		edcLockCacheModel.classNameId = getClassNameId();

		edcLockCacheModel.classPK = getClassPK();

		edcLockCacheModel.lockType = getLockType();

		String lockType = edcLockCacheModel.lockType;

		if ((lockType != null) && (lockType.length() == 0)) {
			edcLockCacheModel.lockType = null;
		}

		edcLockCacheModel.userId = getUserId();

		edcLockCacheModel.userName = getUserName();

		String userName = edcLockCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			edcLockCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			edcLockCacheModel.createDate = createDate.getTime();
		}
		else {
			edcLockCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			edcLockCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			edcLockCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		edcLockCacheModel.comment = getComment();

		String comment = edcLockCacheModel.comment;

		if ((comment != null) && (comment.length() == 0)) {
			edcLockCacheModel.comment = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			edcLockCacheModel.startDate = startDate.getTime();
		}
		else {
			edcLockCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			edcLockCacheModel.endDate = endDate.getTime();
		}
		else {
			edcLockCacheModel.endDate = Long.MIN_VALUE;
		}

		return edcLockCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EdcLock, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EdcLock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcLock, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EdcLock)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EdcLock, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EdcLock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcLock, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EdcLock)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EdcLock>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EdcLock.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _lockId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private String _lockType;
	private String _originalLockType;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _comment;
	private Date _startDate;
	private Date _endDate;
	private long _columnBitmask;
	private EdcLock _escapedModel;

}