/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.EdcPermissionRole;
import com.dhsoft.edc.backend.model.EdcPermissionRoleModel;
import com.dhsoft.edc.backend.model.EdcPermissionRoleSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EdcPermissionRole service. Represents a row in the &quot;EDC_EdcPermissionRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EdcPermissionRoleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EdcPermissionRoleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcPermissionRoleImpl
 * @generated
 */
@JSON(strict = true)
public class EdcPermissionRoleModelImpl
	extends BaseModelImpl<EdcPermissionRole> implements EdcPermissionRoleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a edc permission role model instance should use the <code>EdcPermissionRole</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_EdcPermissionRole";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"permissionRoleId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"actorGroup", Types.BIGINT},
		{"actorId", Types.BIGINT}, {"roleName", Types.VARCHAR},
		{"active_", Types.BOOLEAN}, {"fromDate", Types.TIMESTAMP},
		{"toDate", Types.TIMESTAMP}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"createdBy", Types.BIGINT},
		{"modifiedBy", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("permissionRoleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("actorGroup", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("actorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("fromDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("toDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_EdcPermissionRole (uuid_ VARCHAR(75) null,permissionRoleId LONG not null primary key,companyId LONG,groupId LONG,projectId LONG,actorGroup LONG,actorId LONG,roleName VARCHAR(75) null,active_ BOOLEAN,fromDate DATE null,toDate DATE null,createDate DATE null,modifiedDate DATE null,createdBy LONG,modifiedBy LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table EDC_EdcPermissionRole";

	public static final String ORDER_BY_JPQL =
		" ORDER BY edcPermissionRole.roleName ASC, edcPermissionRole.actorId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_EdcPermissionRole.roleName ASC, EDC_EdcPermissionRole.actorId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTORGROUP_COLUMN_BITMASK = 1L;

	public static final long ACTORID_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long PROJECTID_COLUMN_BITMASK = 16L;

	public static final long ROLENAME_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EdcPermissionRole toModel(EdcPermissionRoleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EdcPermissionRole model = new EdcPermissionRoleImpl();

		model.setUuid(soapModel.getUuid());
		model.setPermissionRoleId(soapModel.getPermissionRoleId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setProjectId(soapModel.getProjectId());
		model.setActorGroup(soapModel.getActorGroup());
		model.setActorId(soapModel.getActorId());
		model.setRoleName(soapModel.getRoleName());
		model.setActive(soapModel.isActive());
		model.setFromDate(soapModel.getFromDate());
		model.setToDate(soapModel.getToDate());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setModifiedBy(soapModel.getModifiedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EdcPermissionRole> toModels(
		EdcPermissionRoleSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EdcPermissionRole> models = new ArrayList<EdcPermissionRole>(
			soapModels.length);

		for (EdcPermissionRoleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EdcPermissionRoleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _permissionRoleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPermissionRoleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _permissionRoleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EdcPermissionRole.class;
	}

	@Override
	public String getModelClassName() {
		return EdcPermissionRole.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EdcPermissionRole, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EdcPermissionRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionRole, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EdcPermissionRole)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EdcPermissionRole, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EdcPermissionRole, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EdcPermissionRole)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EdcPermissionRole, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EdcPermissionRole, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EdcPermissionRole, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EdcPermissionRole, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EdcPermissionRole, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EdcPermissionRole, Object>>();
		Map<String, BiConsumer<EdcPermissionRole, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<EdcPermissionRole, ?>>();

		attributeGetterFunctions.put("uuid", EdcPermissionRole::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EdcPermissionRole, String>)EdcPermissionRole::setUuid);
		attributeGetterFunctions.put(
			"permissionRoleId", EdcPermissionRole::getPermissionRoleId);
		attributeSetterBiConsumers.put(
			"permissionRoleId",
			(BiConsumer<EdcPermissionRole, Long>)
				EdcPermissionRole::setPermissionRoleId);
		attributeGetterFunctions.put(
			"companyId", EdcPermissionRole::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EdcPermissionRole, Long>)
				EdcPermissionRole::setCompanyId);
		attributeGetterFunctions.put("groupId", EdcPermissionRole::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EdcPermissionRole, Long>)EdcPermissionRole::setGroupId);
		attributeGetterFunctions.put(
			"projectId", EdcPermissionRole::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<EdcPermissionRole, Long>)
				EdcPermissionRole::setProjectId);
		attributeGetterFunctions.put(
			"actorGroup", EdcPermissionRole::getActorGroup);
		attributeSetterBiConsumers.put(
			"actorGroup",
			(BiConsumer<EdcPermissionRole, Long>)
				EdcPermissionRole::setActorGroup);
		attributeGetterFunctions.put("actorId", EdcPermissionRole::getActorId);
		attributeSetterBiConsumers.put(
			"actorId",
			(BiConsumer<EdcPermissionRole, Long>)EdcPermissionRole::setActorId);
		attributeGetterFunctions.put(
			"roleName", EdcPermissionRole::getRoleName);
		attributeSetterBiConsumers.put(
			"roleName",
			(BiConsumer<EdcPermissionRole, String>)
				EdcPermissionRole::setRoleName);
		attributeGetterFunctions.put("active", EdcPermissionRole::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<EdcPermissionRole, Boolean>)
				EdcPermissionRole::setActive);
		attributeGetterFunctions.put(
			"fromDate", EdcPermissionRole::getFromDate);
		attributeSetterBiConsumers.put(
			"fromDate",
			(BiConsumer<EdcPermissionRole, Date>)
				EdcPermissionRole::setFromDate);
		attributeGetterFunctions.put("toDate", EdcPermissionRole::getToDate);
		attributeSetterBiConsumers.put(
			"toDate",
			(BiConsumer<EdcPermissionRole, Date>)EdcPermissionRole::setToDate);
		attributeGetterFunctions.put(
			"createDate", EdcPermissionRole::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EdcPermissionRole, Date>)
				EdcPermissionRole::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EdcPermissionRole::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EdcPermissionRole, Date>)
				EdcPermissionRole::setModifiedDate);
		attributeGetterFunctions.put(
			"createdBy", EdcPermissionRole::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<EdcPermissionRole, Long>)
				EdcPermissionRole::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", EdcPermissionRole::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<EdcPermissionRole, Long>)
				EdcPermissionRole::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPermissionRoleId() {
		return _permissionRoleId;
	}

	@Override
	public void setPermissionRoleId(long permissionRoleId) {
		_permissionRoleId = permissionRoleId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getActorGroup() {
		return _actorGroup;
	}

	@Override
	public void setActorGroup(long actorGroup) {
		_columnBitmask |= ACTORGROUP_COLUMN_BITMASK;

		if (!_setOriginalActorGroup) {
			_setOriginalActorGroup = true;

			_originalActorGroup = _actorGroup;
		}

		_actorGroup = actorGroup;
	}

	public long getOriginalActorGroup() {
		return _originalActorGroup;
	}

	@JSON
	@Override
	public long getActorId() {
		return _actorId;
	}

	@Override
	public void setActorId(long actorId) {
		_columnBitmask = -1L;

		if (!_setOriginalActorId) {
			_setOriginalActorId = true;

			_originalActorId = _actorId;
		}

		_actorId = actorId;
	}

	public long getOriginalActorId() {
		return _originalActorId;
	}

	@JSON
	@Override
	public String getRoleName() {
		if (_roleName == null) {
			return "";
		}
		else {
			return _roleName;
		}
	}

	@Override
	public void setRoleName(String roleName) {
		_columnBitmask = -1L;

		if (_originalRoleName == null) {
			_originalRoleName = _roleName;
		}

		_roleName = roleName;
	}

	public String getOriginalRoleName() {
		return GetterUtil.getString(_originalRoleName);
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_active = active;
	}

	@JSON
	@Override
	public Date getFromDate() {
		return _fromDate;
	}

	@Override
	public void setFromDate(Date fromDate) {
		_fromDate = fromDate;
	}

	@JSON
	@Override
	public Date getToDate() {
		return _toDate;
	}

	@Override
	public void setToDate(Date toDate) {
		_toDate = toDate;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EdcPermissionRole.class.getName()));
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EdcPermissionRole.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EdcPermissionRole toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EdcPermissionRole>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EdcPermissionRoleImpl edcPermissionRoleImpl =
			new EdcPermissionRoleImpl();

		edcPermissionRoleImpl.setUuid(getUuid());
		edcPermissionRoleImpl.setPermissionRoleId(getPermissionRoleId());
		edcPermissionRoleImpl.setCompanyId(getCompanyId());
		edcPermissionRoleImpl.setGroupId(getGroupId());
		edcPermissionRoleImpl.setProjectId(getProjectId());
		edcPermissionRoleImpl.setActorGroup(getActorGroup());
		edcPermissionRoleImpl.setActorId(getActorId());
		edcPermissionRoleImpl.setRoleName(getRoleName());
		edcPermissionRoleImpl.setActive(isActive());
		edcPermissionRoleImpl.setFromDate(getFromDate());
		edcPermissionRoleImpl.setToDate(getToDate());
		edcPermissionRoleImpl.setCreateDate(getCreateDate());
		edcPermissionRoleImpl.setModifiedDate(getModifiedDate());
		edcPermissionRoleImpl.setCreatedBy(getCreatedBy());
		edcPermissionRoleImpl.setModifiedBy(getModifiedBy());

		edcPermissionRoleImpl.resetOriginalValues();

		return edcPermissionRoleImpl;
	}

	@Override
	public int compareTo(EdcPermissionRole edcPermissionRole) {
		int value = 0;

		value = getRoleName().compareTo(edcPermissionRole.getRoleName());

		if (value != 0) {
			return value;
		}

		if (getActorId() < edcPermissionRole.getActorId()) {
			value = -1;
		}
		else if (getActorId() > edcPermissionRole.getActorId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EdcPermissionRole)) {
			return false;
		}

		EdcPermissionRole edcPermissionRole = (EdcPermissionRole)object;

		long primaryKey = edcPermissionRole.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalActorGroup = _actorGroup;

		_setOriginalActorGroup = false;

		_originalActorId = _actorId;

		_setOriginalActorId = false;

		_originalRoleName = _roleName;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EdcPermissionRole> toCacheModel() {
		EdcPermissionRoleCacheModel edcPermissionRoleCacheModel =
			new EdcPermissionRoleCacheModel();

		edcPermissionRoleCacheModel.uuid = getUuid();

		String uuid = edcPermissionRoleCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			edcPermissionRoleCacheModel.uuid = null;
		}

		edcPermissionRoleCacheModel.permissionRoleId = getPermissionRoleId();

		edcPermissionRoleCacheModel.companyId = getCompanyId();

		edcPermissionRoleCacheModel.groupId = getGroupId();

		edcPermissionRoleCacheModel.projectId = getProjectId();

		edcPermissionRoleCacheModel.actorGroup = getActorGroup();

		edcPermissionRoleCacheModel.actorId = getActorId();

		edcPermissionRoleCacheModel.roleName = getRoleName();

		String roleName = edcPermissionRoleCacheModel.roleName;

		if ((roleName != null) && (roleName.length() == 0)) {
			edcPermissionRoleCacheModel.roleName = null;
		}

		edcPermissionRoleCacheModel.active = isActive();

		Date fromDate = getFromDate();

		if (fromDate != null) {
			edcPermissionRoleCacheModel.fromDate = fromDate.getTime();
		}
		else {
			edcPermissionRoleCacheModel.fromDate = Long.MIN_VALUE;
		}

		Date toDate = getToDate();

		if (toDate != null) {
			edcPermissionRoleCacheModel.toDate = toDate.getTime();
		}
		else {
			edcPermissionRoleCacheModel.toDate = Long.MIN_VALUE;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			edcPermissionRoleCacheModel.createDate = createDate.getTime();
		}
		else {
			edcPermissionRoleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			edcPermissionRoleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			edcPermissionRoleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		edcPermissionRoleCacheModel.createdBy = getCreatedBy();

		edcPermissionRoleCacheModel.modifiedBy = getModifiedBy();

		return edcPermissionRoleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EdcPermissionRole, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EdcPermissionRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionRole, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EdcPermissionRole)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EdcPermissionRole, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EdcPermissionRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionRole, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EdcPermissionRole)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EdcPermissionRole>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EdcPermissionRole.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _permissionRoleId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _actorGroup;
	private long _originalActorGroup;
	private boolean _setOriginalActorGroup;
	private long _actorId;
	private long _originalActorId;
	private boolean _setOriginalActorId;
	private String _roleName;
	private String _originalRoleName;
	private boolean _active;
	private Date _fromDate;
	private Date _toDate;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdBy;
	private long _modifiedBy;
	private long _columnBitmask;
	private EdcPermissionRole _escapedModel;

}