/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.EdcPermissionRoleAudit;
import com.dhsoft.edc.backend.model.EdcPermissionRoleAuditModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EdcPermissionRoleAudit service. Represents a row in the &quot;EDC_EdcPermissionRoleAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EdcPermissionRoleAuditModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EdcPermissionRoleAuditImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcPermissionRoleAuditImpl
 * @generated
 */
public class EdcPermissionRoleAuditModelImpl
	extends BaseModelImpl<EdcPermissionRoleAudit>
	implements EdcPermissionRoleAuditModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a edc permission role audit model instance should use the <code>EdcPermissionRoleAudit</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_EdcPermissionRoleAudit";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"auditRoleId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"actorGroup", Types.BIGINT},
		{"actorId", Types.BIGINT}, {"crudType", Types.VARCHAR},
		{"fromRole", Types.VARCHAR}, {"toRole", Types.VARCHAR},
		{"fromActive", Types.VARCHAR}, {"toActive", Types.VARCHAR},
		{"remarks", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("auditRoleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("actorGroup", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("actorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("crudType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fromRole", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("toRole", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fromActive", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("toActive", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("remarks", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_EdcPermissionRoleAudit (uuid_ VARCHAR(75) null,auditRoleId LONG not null primary key,companyId LONG,groupId LONG,projectId LONG,actorGroup LONG,actorId LONG,crudType VARCHAR(75) null,fromRole VARCHAR(75) null,toRole VARCHAR(75) null,fromActive VARCHAR(75) null,toActive VARCHAR(75) null,remarks VARCHAR(75) null,createDate DATE null,userId LONG,userName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table EDC_EdcPermissionRoleAudit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY edcPermissionRoleAudit.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_EdcPermissionRoleAudit.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTORGROUP_COLUMN_BITMASK = 1L;

	public static final long ACTORID_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public EdcPermissionRoleAuditModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _auditRoleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditRoleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _auditRoleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EdcPermissionRoleAudit.class;
	}

	@Override
	public String getModelClassName() {
		return EdcPermissionRoleAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EdcPermissionRoleAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EdcPermissionRoleAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionRoleAudit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EdcPermissionRoleAudit)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EdcPermissionRoleAudit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EdcPermissionRoleAudit, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EdcPermissionRoleAudit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EdcPermissionRoleAudit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EdcPermissionRoleAudit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EdcPermissionRoleAudit, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EdcPermissionRoleAudit, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EdcPermissionRoleAudit, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EdcPermissionRoleAudit, Object>>();
		Map<String, BiConsumer<EdcPermissionRoleAudit, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<EdcPermissionRoleAudit, ?>>();

		attributeGetterFunctions.put("uuid", EdcPermissionRoleAudit::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EdcPermissionRoleAudit, String>)
				EdcPermissionRoleAudit::setUuid);
		attributeGetterFunctions.put(
			"auditRoleId", EdcPermissionRoleAudit::getAuditRoleId);
		attributeSetterBiConsumers.put(
			"auditRoleId",
			(BiConsumer<EdcPermissionRoleAudit, Long>)
				EdcPermissionRoleAudit::setAuditRoleId);
		attributeGetterFunctions.put(
			"companyId", EdcPermissionRoleAudit::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EdcPermissionRoleAudit, Long>)
				EdcPermissionRoleAudit::setCompanyId);
		attributeGetterFunctions.put(
			"groupId", EdcPermissionRoleAudit::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EdcPermissionRoleAudit, Long>)
				EdcPermissionRoleAudit::setGroupId);
		attributeGetterFunctions.put(
			"projectId", EdcPermissionRoleAudit::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<EdcPermissionRoleAudit, Long>)
				EdcPermissionRoleAudit::setProjectId);
		attributeGetterFunctions.put(
			"actorGroup", EdcPermissionRoleAudit::getActorGroup);
		attributeSetterBiConsumers.put(
			"actorGroup",
			(BiConsumer<EdcPermissionRoleAudit, Long>)
				EdcPermissionRoleAudit::setActorGroup);
		attributeGetterFunctions.put(
			"actorId", EdcPermissionRoleAudit::getActorId);
		attributeSetterBiConsumers.put(
			"actorId",
			(BiConsumer<EdcPermissionRoleAudit, Long>)
				EdcPermissionRoleAudit::setActorId);
		attributeGetterFunctions.put(
			"crudType", EdcPermissionRoleAudit::getCrudType);
		attributeSetterBiConsumers.put(
			"crudType",
			(BiConsumer<EdcPermissionRoleAudit, String>)
				EdcPermissionRoleAudit::setCrudType);
		attributeGetterFunctions.put(
			"fromRole", EdcPermissionRoleAudit::getFromRole);
		attributeSetterBiConsumers.put(
			"fromRole",
			(BiConsumer<EdcPermissionRoleAudit, String>)
				EdcPermissionRoleAudit::setFromRole);
		attributeGetterFunctions.put(
			"toRole", EdcPermissionRoleAudit::getToRole);
		attributeSetterBiConsumers.put(
			"toRole",
			(BiConsumer<EdcPermissionRoleAudit, String>)
				EdcPermissionRoleAudit::setToRole);
		attributeGetterFunctions.put(
			"fromActive", EdcPermissionRoleAudit::getFromActive);
		attributeSetterBiConsumers.put(
			"fromActive",
			(BiConsumer<EdcPermissionRoleAudit, String>)
				EdcPermissionRoleAudit::setFromActive);
		attributeGetterFunctions.put(
			"toActive", EdcPermissionRoleAudit::getToActive);
		attributeSetterBiConsumers.put(
			"toActive",
			(BiConsumer<EdcPermissionRoleAudit, String>)
				EdcPermissionRoleAudit::setToActive);
		attributeGetterFunctions.put(
			"remarks", EdcPermissionRoleAudit::getRemarks);
		attributeSetterBiConsumers.put(
			"remarks",
			(BiConsumer<EdcPermissionRoleAudit, String>)
				EdcPermissionRoleAudit::setRemarks);
		attributeGetterFunctions.put(
			"createDate", EdcPermissionRoleAudit::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EdcPermissionRoleAudit, Date>)
				EdcPermissionRoleAudit::setCreateDate);
		attributeGetterFunctions.put(
			"userId", EdcPermissionRoleAudit::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EdcPermissionRoleAudit, Long>)
				EdcPermissionRoleAudit::setUserId);
		attributeGetterFunctions.put(
			"userName", EdcPermissionRoleAudit::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EdcPermissionRoleAudit, String>)
				EdcPermissionRoleAudit::setUserName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getAuditRoleId() {
		return _auditRoleId;
	}

	@Override
	public void setAuditRoleId(long auditRoleId) {
		_auditRoleId = auditRoleId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_projectId = projectId;
	}

	@Override
	public long getActorGroup() {
		return _actorGroup;
	}

	@Override
	public void setActorGroup(long actorGroup) {
		_columnBitmask |= ACTORGROUP_COLUMN_BITMASK;

		if (!_setOriginalActorGroup) {
			_setOriginalActorGroup = true;

			_originalActorGroup = _actorGroup;
		}

		_actorGroup = actorGroup;
	}

	public long getOriginalActorGroup() {
		return _originalActorGroup;
	}

	@Override
	public long getActorId() {
		return _actorId;
	}

	@Override
	public void setActorId(long actorId) {
		_columnBitmask |= ACTORID_COLUMN_BITMASK;

		if (!_setOriginalActorId) {
			_setOriginalActorId = true;

			_originalActorId = _actorId;
		}

		_actorId = actorId;
	}

	public long getOriginalActorId() {
		return _originalActorId;
	}

	@Override
	public String getCrudType() {
		if (_crudType == null) {
			return "";
		}
		else {
			return _crudType;
		}
	}

	@Override
	public void setCrudType(String crudType) {
		_crudType = crudType;
	}

	@Override
	public String getFromRole() {
		if (_fromRole == null) {
			return "";
		}
		else {
			return _fromRole;
		}
	}

	@Override
	public void setFromRole(String fromRole) {
		_fromRole = fromRole;
	}

	@Override
	public String getToRole() {
		if (_toRole == null) {
			return "";
		}
		else {
			return _toRole;
		}
	}

	@Override
	public void setToRole(String toRole) {
		_toRole = toRole;
	}

	@Override
	public String getFromActive() {
		if (_fromActive == null) {
			return "";
		}
		else {
			return _fromActive;
		}
	}

	@Override
	public void setFromActive(String fromActive) {
		_fromActive = fromActive;
	}

	@Override
	public String getToActive() {
		if (_toActive == null) {
			return "";
		}
		else {
			return _toActive;
		}
	}

	@Override
	public void setToActive(String toActive) {
		_toActive = toActive;
	}

	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return "";
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		_remarks = remarks;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EdcPermissionRoleAudit.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EdcPermissionRoleAudit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EdcPermissionRoleAudit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EdcPermissionRoleAuditImpl edcPermissionRoleAuditImpl =
			new EdcPermissionRoleAuditImpl();

		edcPermissionRoleAuditImpl.setUuid(getUuid());
		edcPermissionRoleAuditImpl.setAuditRoleId(getAuditRoleId());
		edcPermissionRoleAuditImpl.setCompanyId(getCompanyId());
		edcPermissionRoleAuditImpl.setGroupId(getGroupId());
		edcPermissionRoleAuditImpl.setProjectId(getProjectId());
		edcPermissionRoleAuditImpl.setActorGroup(getActorGroup());
		edcPermissionRoleAuditImpl.setActorId(getActorId());
		edcPermissionRoleAuditImpl.setCrudType(getCrudType());
		edcPermissionRoleAuditImpl.setFromRole(getFromRole());
		edcPermissionRoleAuditImpl.setToRole(getToRole());
		edcPermissionRoleAuditImpl.setFromActive(getFromActive());
		edcPermissionRoleAuditImpl.setToActive(getToActive());
		edcPermissionRoleAuditImpl.setRemarks(getRemarks());
		edcPermissionRoleAuditImpl.setCreateDate(getCreateDate());
		edcPermissionRoleAuditImpl.setUserId(getUserId());
		edcPermissionRoleAuditImpl.setUserName(getUserName());

		edcPermissionRoleAuditImpl.resetOriginalValues();

		return edcPermissionRoleAuditImpl;
	}

	@Override
	public int compareTo(EdcPermissionRoleAudit edcPermissionRoleAudit) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), edcPermissionRoleAudit.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EdcPermissionRoleAudit)) {
			return false;
		}

		EdcPermissionRoleAudit edcPermissionRoleAudit =
			(EdcPermissionRoleAudit)object;

		long primaryKey = edcPermissionRoleAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalActorGroup = _actorGroup;

		_setOriginalActorGroup = false;

		_originalActorId = _actorId;

		_setOriginalActorId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EdcPermissionRoleAudit> toCacheModel() {
		EdcPermissionRoleAuditCacheModel edcPermissionRoleAuditCacheModel =
			new EdcPermissionRoleAuditCacheModel();

		edcPermissionRoleAuditCacheModel.uuid = getUuid();

		String uuid = edcPermissionRoleAuditCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			edcPermissionRoleAuditCacheModel.uuid = null;
		}

		edcPermissionRoleAuditCacheModel.auditRoleId = getAuditRoleId();

		edcPermissionRoleAuditCacheModel.companyId = getCompanyId();

		edcPermissionRoleAuditCacheModel.groupId = getGroupId();

		edcPermissionRoleAuditCacheModel.projectId = getProjectId();

		edcPermissionRoleAuditCacheModel.actorGroup = getActorGroup();

		edcPermissionRoleAuditCacheModel.actorId = getActorId();

		edcPermissionRoleAuditCacheModel.crudType = getCrudType();

		String crudType = edcPermissionRoleAuditCacheModel.crudType;

		if ((crudType != null) && (crudType.length() == 0)) {
			edcPermissionRoleAuditCacheModel.crudType = null;
		}

		edcPermissionRoleAuditCacheModel.fromRole = getFromRole();

		String fromRole = edcPermissionRoleAuditCacheModel.fromRole;

		if ((fromRole != null) && (fromRole.length() == 0)) {
			edcPermissionRoleAuditCacheModel.fromRole = null;
		}

		edcPermissionRoleAuditCacheModel.toRole = getToRole();

		String toRole = edcPermissionRoleAuditCacheModel.toRole;

		if ((toRole != null) && (toRole.length() == 0)) {
			edcPermissionRoleAuditCacheModel.toRole = null;
		}

		edcPermissionRoleAuditCacheModel.fromActive = getFromActive();

		String fromActive = edcPermissionRoleAuditCacheModel.fromActive;

		if ((fromActive != null) && (fromActive.length() == 0)) {
			edcPermissionRoleAuditCacheModel.fromActive = null;
		}

		edcPermissionRoleAuditCacheModel.toActive = getToActive();

		String toActive = edcPermissionRoleAuditCacheModel.toActive;

		if ((toActive != null) && (toActive.length() == 0)) {
			edcPermissionRoleAuditCacheModel.toActive = null;
		}

		edcPermissionRoleAuditCacheModel.remarks = getRemarks();

		String remarks = edcPermissionRoleAuditCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			edcPermissionRoleAuditCacheModel.remarks = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			edcPermissionRoleAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			edcPermissionRoleAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		edcPermissionRoleAuditCacheModel.userId = getUserId();

		edcPermissionRoleAuditCacheModel.userName = getUserName();

		String userName = edcPermissionRoleAuditCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			edcPermissionRoleAuditCacheModel.userName = null;
		}

		return edcPermissionRoleAuditCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EdcPermissionRoleAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EdcPermissionRoleAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionRoleAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EdcPermissionRoleAudit)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EdcPermissionRoleAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EdcPermissionRoleAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionRoleAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((EdcPermissionRoleAudit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EdcPermissionRoleAudit>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EdcPermissionRoleAudit.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _auditRoleId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _projectId;
	private long _actorGroup;
	private long _originalActorGroup;
	private boolean _setOriginalActorGroup;
	private long _actorId;
	private long _originalActorId;
	private boolean _setOriginalActorId;
	private String _crudType;
	private String _fromRole;
	private String _toRole;
	private String _fromActive;
	private String _toActive;
	private String _remarks;
	private Date _createDate;
	private long _userId;
	private String _userName;
	private long _columnBitmask;
	private EdcPermissionRoleAudit _escapedModel;

}