/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.EdcPermissionScope;
import com.dhsoft.edc.backend.model.EdcPermissionScopeModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EdcPermissionScope service. Represents a row in the &quot;EDC_EdcPermissionScope&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EdcPermissionScopeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EdcPermissionScopeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcPermissionScopeImpl
 * @generated
 */
public class EdcPermissionScopeModelImpl
	extends BaseModelImpl<EdcPermissionScope>
	implements EdcPermissionScopeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a edc permission scope model instance should use the <code>EdcPermissionScope</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_EdcPermissionScope";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"permissionScopeId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"moduleName", Types.VARCHAR},
		{"taskKey", Types.VARCHAR}, {"roleName", Types.VARCHAR},
		{"scopeRole", Types.VARCHAR}, {"active_", Types.BOOLEAN},
		{"fromDate", Types.TIMESTAMP}, {"toDate", Types.TIMESTAMP},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("permissionScopeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("moduleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("taskKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("roleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scopeRole", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("fromDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("toDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_EdcPermissionScope (uuid_ VARCHAR(75) null,permissionScopeId LONG not null primary key,companyId LONG,groupId LONG,projectId LONG,moduleName VARCHAR(75) null,taskKey VARCHAR(75) null,roleName VARCHAR(75) null,scopeRole VARCHAR(75) null,active_ BOOLEAN,fromDate DATE null,toDate DATE null,createDate DATE null,modifiedDate DATE null,createdBy LONG,modifiedBy LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table EDC_EdcPermissionScope";

	public static final String ORDER_BY_JPQL =
		" ORDER BY edcPermissionScope.moduleName ASC, edcPermissionScope.taskKey ASC, edcPermissionScope.roleName ASC, edcPermissionScope.scopeRole ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_EdcPermissionScope.moduleName ASC, EDC_EdcPermissionScope.taskKey ASC, EDC_EdcPermissionScope.roleName ASC, EDC_EdcPermissionScope.scopeRole ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long MODULENAME_COLUMN_BITMASK = 4L;

	public static final long PROJECTID_COLUMN_BITMASK = 8L;

	public static final long SCOPEROLE_COLUMN_BITMASK = 16L;

	public static final long TASKKEY_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static final long ROLENAME_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public EdcPermissionScopeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _permissionScopeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPermissionScopeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _permissionScopeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EdcPermissionScope.class;
	}

	@Override
	public String getModelClassName() {
		return EdcPermissionScope.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EdcPermissionScope, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EdcPermissionScope, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionScope, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EdcPermissionScope)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EdcPermissionScope, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EdcPermissionScope, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EdcPermissionScope)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EdcPermissionScope, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EdcPermissionScope, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EdcPermissionScope, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EdcPermissionScope, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EdcPermissionScope, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EdcPermissionScope, Object>>();
		Map<String, BiConsumer<EdcPermissionScope, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<EdcPermissionScope, ?>>();

		attributeGetterFunctions.put("uuid", EdcPermissionScope::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EdcPermissionScope, String>)
				EdcPermissionScope::setUuid);
		attributeGetterFunctions.put(
			"permissionScopeId", EdcPermissionScope::getPermissionScopeId);
		attributeSetterBiConsumers.put(
			"permissionScopeId",
			(BiConsumer<EdcPermissionScope, Long>)
				EdcPermissionScope::setPermissionScopeId);
		attributeGetterFunctions.put(
			"companyId", EdcPermissionScope::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EdcPermissionScope, Long>)
				EdcPermissionScope::setCompanyId);
		attributeGetterFunctions.put("groupId", EdcPermissionScope::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EdcPermissionScope, Long>)
				EdcPermissionScope::setGroupId);
		attributeGetterFunctions.put(
			"projectId", EdcPermissionScope::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<EdcPermissionScope, Long>)
				EdcPermissionScope::setProjectId);
		attributeGetterFunctions.put(
			"moduleName", EdcPermissionScope::getModuleName);
		attributeSetterBiConsumers.put(
			"moduleName",
			(BiConsumer<EdcPermissionScope, String>)
				EdcPermissionScope::setModuleName);
		attributeGetterFunctions.put("taskKey", EdcPermissionScope::getTaskKey);
		attributeSetterBiConsumers.put(
			"taskKey",
			(BiConsumer<EdcPermissionScope, String>)
				EdcPermissionScope::setTaskKey);
		attributeGetterFunctions.put(
			"roleName", EdcPermissionScope::getRoleName);
		attributeSetterBiConsumers.put(
			"roleName",
			(BiConsumer<EdcPermissionScope, String>)
				EdcPermissionScope::setRoleName);
		attributeGetterFunctions.put(
			"scopeRole", EdcPermissionScope::getScopeRole);
		attributeSetterBiConsumers.put(
			"scopeRole",
			(BiConsumer<EdcPermissionScope, String>)
				EdcPermissionScope::setScopeRole);
		attributeGetterFunctions.put("active", EdcPermissionScope::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<EdcPermissionScope, Boolean>)
				EdcPermissionScope::setActive);
		attributeGetterFunctions.put(
			"fromDate", EdcPermissionScope::getFromDate);
		attributeSetterBiConsumers.put(
			"fromDate",
			(BiConsumer<EdcPermissionScope, Date>)
				EdcPermissionScope::setFromDate);
		attributeGetterFunctions.put("toDate", EdcPermissionScope::getToDate);
		attributeSetterBiConsumers.put(
			"toDate",
			(BiConsumer<EdcPermissionScope, Date>)
				EdcPermissionScope::setToDate);
		attributeGetterFunctions.put(
			"createDate", EdcPermissionScope::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EdcPermissionScope, Date>)
				EdcPermissionScope::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EdcPermissionScope::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EdcPermissionScope, Date>)
				EdcPermissionScope::setModifiedDate);
		attributeGetterFunctions.put(
			"createdBy", EdcPermissionScope::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<EdcPermissionScope, Long>)
				EdcPermissionScope::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", EdcPermissionScope::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<EdcPermissionScope, Long>)
				EdcPermissionScope::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getPermissionScopeId() {
		return _permissionScopeId;
	}

	@Override
	public void setPermissionScopeId(long permissionScopeId) {
		_permissionScopeId = permissionScopeId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@Override
	public String getModuleName() {
		if (_moduleName == null) {
			return "";
		}
		else {
			return _moduleName;
		}
	}

	@Override
	public void setModuleName(String moduleName) {
		_columnBitmask = -1L;

		if (_originalModuleName == null) {
			_originalModuleName = _moduleName;
		}

		_moduleName = moduleName;
	}

	public String getOriginalModuleName() {
		return GetterUtil.getString(_originalModuleName);
	}

	@Override
	public String getTaskKey() {
		if (_taskKey == null) {
			return "";
		}
		else {
			return _taskKey;
		}
	}

	@Override
	public void setTaskKey(String taskKey) {
		_columnBitmask = -1L;

		if (_originalTaskKey == null) {
			_originalTaskKey = _taskKey;
		}

		_taskKey = taskKey;
	}

	public String getOriginalTaskKey() {
		return GetterUtil.getString(_originalTaskKey);
	}

	@Override
	public String getRoleName() {
		if (_roleName == null) {
			return "";
		}
		else {
			return _roleName;
		}
	}

	@Override
	public void setRoleName(String roleName) {
		_columnBitmask = -1L;

		_roleName = roleName;
	}

	@Override
	public String getScopeRole() {
		if (_scopeRole == null) {
			return "";
		}
		else {
			return _scopeRole;
		}
	}

	@Override
	public void setScopeRole(String scopeRole) {
		_columnBitmask = -1L;

		if (_originalScopeRole == null) {
			_originalScopeRole = _scopeRole;
		}

		_scopeRole = scopeRole;
	}

	public String getOriginalScopeRole() {
		return GetterUtil.getString(_originalScopeRole);
	}

	@Override
	public boolean getActive() {
		return _active;
	}

	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_active = active;
	}

	@Override
	public Date getFromDate() {
		return _fromDate;
	}

	@Override
	public void setFromDate(Date fromDate) {
		_fromDate = fromDate;
	}

	@Override
	public Date getToDate() {
		return _toDate;
	}

	@Override
	public void setToDate(Date toDate) {
		_toDate = toDate;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EdcPermissionScope.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EdcPermissionScope.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EdcPermissionScope toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EdcPermissionScope>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EdcPermissionScopeImpl edcPermissionScopeImpl =
			new EdcPermissionScopeImpl();

		edcPermissionScopeImpl.setUuid(getUuid());
		edcPermissionScopeImpl.setPermissionScopeId(getPermissionScopeId());
		edcPermissionScopeImpl.setCompanyId(getCompanyId());
		edcPermissionScopeImpl.setGroupId(getGroupId());
		edcPermissionScopeImpl.setProjectId(getProjectId());
		edcPermissionScopeImpl.setModuleName(getModuleName());
		edcPermissionScopeImpl.setTaskKey(getTaskKey());
		edcPermissionScopeImpl.setRoleName(getRoleName());
		edcPermissionScopeImpl.setScopeRole(getScopeRole());
		edcPermissionScopeImpl.setActive(isActive());
		edcPermissionScopeImpl.setFromDate(getFromDate());
		edcPermissionScopeImpl.setToDate(getToDate());
		edcPermissionScopeImpl.setCreateDate(getCreateDate());
		edcPermissionScopeImpl.setModifiedDate(getModifiedDate());
		edcPermissionScopeImpl.setCreatedBy(getCreatedBy());
		edcPermissionScopeImpl.setModifiedBy(getModifiedBy());

		edcPermissionScopeImpl.resetOriginalValues();

		return edcPermissionScopeImpl;
	}

	@Override
	public int compareTo(EdcPermissionScope edcPermissionScope) {
		int value = 0;

		value = getModuleName().compareTo(edcPermissionScope.getModuleName());

		if (value != 0) {
			return value;
		}

		value = getTaskKey().compareTo(edcPermissionScope.getTaskKey());

		if (value != 0) {
			return value;
		}

		value = getRoleName().compareTo(edcPermissionScope.getRoleName());

		if (value != 0) {
			return value;
		}

		value = getScopeRole().compareTo(edcPermissionScope.getScopeRole());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EdcPermissionScope)) {
			return false;
		}

		EdcPermissionScope edcPermissionScope = (EdcPermissionScope)object;

		long primaryKey = edcPermissionScope.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalModuleName = _moduleName;

		_originalTaskKey = _taskKey;

		_originalScopeRole = _scopeRole;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EdcPermissionScope> toCacheModel() {
		EdcPermissionScopeCacheModel edcPermissionScopeCacheModel =
			new EdcPermissionScopeCacheModel();

		edcPermissionScopeCacheModel.uuid = getUuid();

		String uuid = edcPermissionScopeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			edcPermissionScopeCacheModel.uuid = null;
		}

		edcPermissionScopeCacheModel.permissionScopeId = getPermissionScopeId();

		edcPermissionScopeCacheModel.companyId = getCompanyId();

		edcPermissionScopeCacheModel.groupId = getGroupId();

		edcPermissionScopeCacheModel.projectId = getProjectId();

		edcPermissionScopeCacheModel.moduleName = getModuleName();

		String moduleName = edcPermissionScopeCacheModel.moduleName;

		if ((moduleName != null) && (moduleName.length() == 0)) {
			edcPermissionScopeCacheModel.moduleName = null;
		}

		edcPermissionScopeCacheModel.taskKey = getTaskKey();

		String taskKey = edcPermissionScopeCacheModel.taskKey;

		if ((taskKey != null) && (taskKey.length() == 0)) {
			edcPermissionScopeCacheModel.taskKey = null;
		}

		edcPermissionScopeCacheModel.roleName = getRoleName();

		String roleName = edcPermissionScopeCacheModel.roleName;

		if ((roleName != null) && (roleName.length() == 0)) {
			edcPermissionScopeCacheModel.roleName = null;
		}

		edcPermissionScopeCacheModel.scopeRole = getScopeRole();

		String scopeRole = edcPermissionScopeCacheModel.scopeRole;

		if ((scopeRole != null) && (scopeRole.length() == 0)) {
			edcPermissionScopeCacheModel.scopeRole = null;
		}

		edcPermissionScopeCacheModel.active = isActive();

		Date fromDate = getFromDate();

		if (fromDate != null) {
			edcPermissionScopeCacheModel.fromDate = fromDate.getTime();
		}
		else {
			edcPermissionScopeCacheModel.fromDate = Long.MIN_VALUE;
		}

		Date toDate = getToDate();

		if (toDate != null) {
			edcPermissionScopeCacheModel.toDate = toDate.getTime();
		}
		else {
			edcPermissionScopeCacheModel.toDate = Long.MIN_VALUE;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			edcPermissionScopeCacheModel.createDate = createDate.getTime();
		}
		else {
			edcPermissionScopeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			edcPermissionScopeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			edcPermissionScopeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		edcPermissionScopeCacheModel.createdBy = getCreatedBy();

		edcPermissionScopeCacheModel.modifiedBy = getModifiedBy();

		return edcPermissionScopeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EdcPermissionScope, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EdcPermissionScope, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionScope, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EdcPermissionScope)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EdcPermissionScope, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EdcPermissionScope, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionScope, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EdcPermissionScope)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EdcPermissionScope>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EdcPermissionScope.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _permissionScopeId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private String _moduleName;
	private String _originalModuleName;
	private String _taskKey;
	private String _originalTaskKey;
	private String _roleName;
	private String _scopeRole;
	private String _originalScopeRole;
	private boolean _active;
	private Date _fromDate;
	private Date _toDate;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdBy;
	private long _modifiedBy;
	private long _columnBitmask;
	private EdcPermissionScope _escapedModel;

}