/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.EdcPermissionScopeAudit;
import com.dhsoft.edc.backend.model.EdcPermissionScopeAuditModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EdcPermissionScopeAudit service. Represents a row in the &quot;EDC_EdcPermissionScopeAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EdcPermissionScopeAuditModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EdcPermissionScopeAuditImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EdcPermissionScopeAuditImpl
 * @generated
 */
public class EdcPermissionScopeAuditModelImpl
	extends BaseModelImpl<EdcPermissionScopeAudit>
	implements EdcPermissionScopeAuditModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a edc permission scope audit model instance should use the <code>EdcPermissionScopeAudit</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_EdcPermissionScopeAudit";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"auditScopeId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"roleName", Types.VARCHAR},
		{"moduleName", Types.VARCHAR}, {"taskKey", Types.VARCHAR},
		{"fromScope", Types.VARCHAR}, {"toScope", Types.VARCHAR},
		{"fromActive", Types.VARCHAR}, {"toActive", Types.VARCHAR},
		{"remarks", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("auditScopeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("moduleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("taskKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fromScope", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("toScope", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fromActive", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("toActive", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("remarks", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_EdcPermissionScopeAudit (uuid_ VARCHAR(75) null,auditScopeId LONG not null primary key,companyId LONG,groupId LONG,projectId LONG,roleName VARCHAR(75) null,moduleName VARCHAR(75) null,taskKey VARCHAR(75) null,fromScope VARCHAR(75) null,toScope VARCHAR(75) null,fromActive VARCHAR(75) null,toActive VARCHAR(75) null,remarks VARCHAR(75) null,createDate DATE null,userId LONG,userName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table EDC_EdcPermissionScopeAudit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY edcPermissionScopeAudit.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_EdcPermissionScopeAudit.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long MODULENAME_COLUMN_BITMASK = 4L;

	public static final long ROLENAME_COLUMN_BITMASK = 8L;

	public static final long TASKKEY_COLUMN_BITMASK = 16L;

	public static final long UUID_COLUMN_BITMASK = 32L;

	public static final long CREATEDATE_COLUMN_BITMASK = 64L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public EdcPermissionScopeAuditModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _auditScopeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditScopeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _auditScopeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EdcPermissionScopeAudit.class;
	}

	@Override
	public String getModelClassName() {
		return EdcPermissionScopeAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EdcPermissionScopeAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EdcPermissionScopeAudit, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionScopeAudit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EdcPermissionScopeAudit)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EdcPermissionScopeAudit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EdcPermissionScopeAudit, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EdcPermissionScopeAudit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EdcPermissionScopeAudit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EdcPermissionScopeAudit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EdcPermissionScopeAudit, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<EdcPermissionScopeAudit, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<EdcPermissionScopeAudit, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EdcPermissionScopeAudit, Object>>();
		Map<String, BiConsumer<EdcPermissionScopeAudit, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<EdcPermissionScopeAudit, ?>>();

		attributeGetterFunctions.put("uuid", EdcPermissionScopeAudit::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setUuid);
		attributeGetterFunctions.put(
			"auditScopeId", EdcPermissionScopeAudit::getAuditScopeId);
		attributeSetterBiConsumers.put(
			"auditScopeId",
			(BiConsumer<EdcPermissionScopeAudit, Long>)
				EdcPermissionScopeAudit::setAuditScopeId);
		attributeGetterFunctions.put(
			"companyId", EdcPermissionScopeAudit::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EdcPermissionScopeAudit, Long>)
				EdcPermissionScopeAudit::setCompanyId);
		attributeGetterFunctions.put(
			"groupId", EdcPermissionScopeAudit::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EdcPermissionScopeAudit, Long>)
				EdcPermissionScopeAudit::setGroupId);
		attributeGetterFunctions.put(
			"projectId", EdcPermissionScopeAudit::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<EdcPermissionScopeAudit, Long>)
				EdcPermissionScopeAudit::setProjectId);
		attributeGetterFunctions.put(
			"roleName", EdcPermissionScopeAudit::getRoleName);
		attributeSetterBiConsumers.put(
			"roleName",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setRoleName);
		attributeGetterFunctions.put(
			"moduleName", EdcPermissionScopeAudit::getModuleName);
		attributeSetterBiConsumers.put(
			"moduleName",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setModuleName);
		attributeGetterFunctions.put(
			"taskKey", EdcPermissionScopeAudit::getTaskKey);
		attributeSetterBiConsumers.put(
			"taskKey",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setTaskKey);
		attributeGetterFunctions.put(
			"fromScope", EdcPermissionScopeAudit::getFromScope);
		attributeSetterBiConsumers.put(
			"fromScope",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setFromScope);
		attributeGetterFunctions.put(
			"toScope", EdcPermissionScopeAudit::getToScope);
		attributeSetterBiConsumers.put(
			"toScope",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setToScope);
		attributeGetterFunctions.put(
			"fromActive", EdcPermissionScopeAudit::getFromActive);
		attributeSetterBiConsumers.put(
			"fromActive",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setFromActive);
		attributeGetterFunctions.put(
			"toActive", EdcPermissionScopeAudit::getToActive);
		attributeSetterBiConsumers.put(
			"toActive",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setToActive);
		attributeGetterFunctions.put(
			"remarks", EdcPermissionScopeAudit::getRemarks);
		attributeSetterBiConsumers.put(
			"remarks",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setRemarks);
		attributeGetterFunctions.put(
			"createDate", EdcPermissionScopeAudit::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EdcPermissionScopeAudit, Date>)
				EdcPermissionScopeAudit::setCreateDate);
		attributeGetterFunctions.put(
			"userId", EdcPermissionScopeAudit::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EdcPermissionScopeAudit, Long>)
				EdcPermissionScopeAudit::setUserId);
		attributeGetterFunctions.put(
			"userName", EdcPermissionScopeAudit::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EdcPermissionScopeAudit, String>)
				EdcPermissionScopeAudit::setUserName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getAuditScopeId() {
		return _auditScopeId;
	}

	@Override
	public void setAuditScopeId(long auditScopeId) {
		_auditScopeId = auditScopeId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_projectId = projectId;
	}

	@Override
	public String getRoleName() {
		if (_roleName == null) {
			return "";
		}
		else {
			return _roleName;
		}
	}

	@Override
	public void setRoleName(String roleName) {
		_columnBitmask |= ROLENAME_COLUMN_BITMASK;

		if (_originalRoleName == null) {
			_originalRoleName = _roleName;
		}

		_roleName = roleName;
	}

	public String getOriginalRoleName() {
		return GetterUtil.getString(_originalRoleName);
	}

	@Override
	public String getModuleName() {
		if (_moduleName == null) {
			return "";
		}
		else {
			return _moduleName;
		}
	}

	@Override
	public void setModuleName(String moduleName) {
		_columnBitmask |= MODULENAME_COLUMN_BITMASK;

		if (_originalModuleName == null) {
			_originalModuleName = _moduleName;
		}

		_moduleName = moduleName;
	}

	public String getOriginalModuleName() {
		return GetterUtil.getString(_originalModuleName);
	}

	@Override
	public String getTaskKey() {
		if (_taskKey == null) {
			return "";
		}
		else {
			return _taskKey;
		}
	}

	@Override
	public void setTaskKey(String taskKey) {
		_columnBitmask |= TASKKEY_COLUMN_BITMASK;

		if (_originalTaskKey == null) {
			_originalTaskKey = _taskKey;
		}

		_taskKey = taskKey;
	}

	public String getOriginalTaskKey() {
		return GetterUtil.getString(_originalTaskKey);
	}

	@Override
	public String getFromScope() {
		if (_fromScope == null) {
			return "";
		}
		else {
			return _fromScope;
		}
	}

	@Override
	public void setFromScope(String fromScope) {
		_fromScope = fromScope;
	}

	@Override
	public String getToScope() {
		if (_toScope == null) {
			return "";
		}
		else {
			return _toScope;
		}
	}

	@Override
	public void setToScope(String toScope) {
		_toScope = toScope;
	}

	@Override
	public String getFromActive() {
		if (_fromActive == null) {
			return "";
		}
		else {
			return _fromActive;
		}
	}

	@Override
	public void setFromActive(String fromActive) {
		_fromActive = fromActive;
	}

	@Override
	public String getToActive() {
		if (_toActive == null) {
			return "";
		}
		else {
			return _toActive;
		}
	}

	@Override
	public void setToActive(String toActive) {
		_toActive = toActive;
	}

	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return "";
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		_remarks = remarks;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EdcPermissionScopeAudit.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EdcPermissionScopeAudit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EdcPermissionScopeAudit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EdcPermissionScopeAuditImpl edcPermissionScopeAuditImpl =
			new EdcPermissionScopeAuditImpl();

		edcPermissionScopeAuditImpl.setUuid(getUuid());
		edcPermissionScopeAuditImpl.setAuditScopeId(getAuditScopeId());
		edcPermissionScopeAuditImpl.setCompanyId(getCompanyId());
		edcPermissionScopeAuditImpl.setGroupId(getGroupId());
		edcPermissionScopeAuditImpl.setProjectId(getProjectId());
		edcPermissionScopeAuditImpl.setRoleName(getRoleName());
		edcPermissionScopeAuditImpl.setModuleName(getModuleName());
		edcPermissionScopeAuditImpl.setTaskKey(getTaskKey());
		edcPermissionScopeAuditImpl.setFromScope(getFromScope());
		edcPermissionScopeAuditImpl.setToScope(getToScope());
		edcPermissionScopeAuditImpl.setFromActive(getFromActive());
		edcPermissionScopeAuditImpl.setToActive(getToActive());
		edcPermissionScopeAuditImpl.setRemarks(getRemarks());
		edcPermissionScopeAuditImpl.setCreateDate(getCreateDate());
		edcPermissionScopeAuditImpl.setUserId(getUserId());
		edcPermissionScopeAuditImpl.setUserName(getUserName());

		edcPermissionScopeAuditImpl.resetOriginalValues();

		return edcPermissionScopeAuditImpl;
	}

	@Override
	public int compareTo(EdcPermissionScopeAudit edcPermissionScopeAudit) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), edcPermissionScopeAudit.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EdcPermissionScopeAudit)) {
			return false;
		}

		EdcPermissionScopeAudit edcPermissionScopeAudit =
			(EdcPermissionScopeAudit)object;

		long primaryKey = edcPermissionScopeAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalRoleName = _roleName;

		_originalModuleName = _moduleName;

		_originalTaskKey = _taskKey;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EdcPermissionScopeAudit> toCacheModel() {
		EdcPermissionScopeAuditCacheModel edcPermissionScopeAuditCacheModel =
			new EdcPermissionScopeAuditCacheModel();

		edcPermissionScopeAuditCacheModel.uuid = getUuid();

		String uuid = edcPermissionScopeAuditCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			edcPermissionScopeAuditCacheModel.uuid = null;
		}

		edcPermissionScopeAuditCacheModel.auditScopeId = getAuditScopeId();

		edcPermissionScopeAuditCacheModel.companyId = getCompanyId();

		edcPermissionScopeAuditCacheModel.groupId = getGroupId();

		edcPermissionScopeAuditCacheModel.projectId = getProjectId();

		edcPermissionScopeAuditCacheModel.roleName = getRoleName();

		String roleName = edcPermissionScopeAuditCacheModel.roleName;

		if ((roleName != null) && (roleName.length() == 0)) {
			edcPermissionScopeAuditCacheModel.roleName = null;
		}

		edcPermissionScopeAuditCacheModel.moduleName = getModuleName();

		String moduleName = edcPermissionScopeAuditCacheModel.moduleName;

		if ((moduleName != null) && (moduleName.length() == 0)) {
			edcPermissionScopeAuditCacheModel.moduleName = null;
		}

		edcPermissionScopeAuditCacheModel.taskKey = getTaskKey();

		String taskKey = edcPermissionScopeAuditCacheModel.taskKey;

		if ((taskKey != null) && (taskKey.length() == 0)) {
			edcPermissionScopeAuditCacheModel.taskKey = null;
		}

		edcPermissionScopeAuditCacheModel.fromScope = getFromScope();

		String fromScope = edcPermissionScopeAuditCacheModel.fromScope;

		if ((fromScope != null) && (fromScope.length() == 0)) {
			edcPermissionScopeAuditCacheModel.fromScope = null;
		}

		edcPermissionScopeAuditCacheModel.toScope = getToScope();

		String toScope = edcPermissionScopeAuditCacheModel.toScope;

		if ((toScope != null) && (toScope.length() == 0)) {
			edcPermissionScopeAuditCacheModel.toScope = null;
		}

		edcPermissionScopeAuditCacheModel.fromActive = getFromActive();

		String fromActive = edcPermissionScopeAuditCacheModel.fromActive;

		if ((fromActive != null) && (fromActive.length() == 0)) {
			edcPermissionScopeAuditCacheModel.fromActive = null;
		}

		edcPermissionScopeAuditCacheModel.toActive = getToActive();

		String toActive = edcPermissionScopeAuditCacheModel.toActive;

		if ((toActive != null) && (toActive.length() == 0)) {
			edcPermissionScopeAuditCacheModel.toActive = null;
		}

		edcPermissionScopeAuditCacheModel.remarks = getRemarks();

		String remarks = edcPermissionScopeAuditCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			edcPermissionScopeAuditCacheModel.remarks = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			edcPermissionScopeAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			edcPermissionScopeAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		edcPermissionScopeAuditCacheModel.userId = getUserId();

		edcPermissionScopeAuditCacheModel.userName = getUserName();

		String userName = edcPermissionScopeAuditCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			edcPermissionScopeAuditCacheModel.userName = null;
		}

		return edcPermissionScopeAuditCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EdcPermissionScopeAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EdcPermissionScopeAudit, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionScopeAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EdcPermissionScopeAudit)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EdcPermissionScopeAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EdcPermissionScopeAudit, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EdcPermissionScopeAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((EdcPermissionScopeAudit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, EdcPermissionScopeAudit>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						EdcPermissionScopeAudit.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _auditScopeId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _projectId;
	private String _roleName;
	private String _originalRoleName;
	private String _moduleName;
	private String _originalModuleName;
	private String _taskKey;
	private String _originalTaskKey;
	private String _fromScope;
	private String _toScope;
	private String _fromActive;
	private String _toActive;
	private String _remarks;
	private Date _createDate;
	private long _userId;
	private String _userName;
	private long _columnBitmask;
	private EdcPermissionScopeAudit _escapedModel;

}