/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.InstResearcher;
import com.dhsoft.edc.backend.model.InstResearcherModel;
import com.dhsoft.edc.backend.model.InstResearcherSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the InstResearcher service. Represents a row in the &quot;EDC_InstResearcher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>InstResearcherModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InstResearcherImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InstResearcherImpl
 * @generated
 */
@JSON(strict = true)
public class InstResearcherModelImpl
	extends BaseModelImpl<InstResearcher> implements InstResearcherModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a inst researcher model instance should use the <code>InstResearcher</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_InstResearcher";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"institutionResearcherId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"institutionId", Types.BIGINT},
		{"researcherId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("institutionResearcherId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("institutionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("researcherId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_InstResearcher (uuid_ VARCHAR(75) null,institutionResearcherId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,institutionId LONG,researcherId LONG)";

	public static final String TABLE_SQL_DROP = "drop table EDC_InstResearcher";

	public static final String ORDER_BY_JPQL =
		" ORDER BY instResearcher.institutionResearcherId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_InstResearcher.institutionResearcherId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long INSTITUTIONID_COLUMN_BITMASK = 4L;

	public static final long PROJECTID_COLUMN_BITMASK = 8L;

	public static final long RESEARCHERID_COLUMN_BITMASK = 16L;

	public static final long USERID_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static final long INSTITUTIONRESEARCHERID_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static InstResearcher toModel(InstResearcherSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		InstResearcher model = new InstResearcherImpl();

		model.setUuid(soapModel.getUuid());
		model.setInstitutionResearcherId(
			soapModel.getInstitutionResearcherId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setInstitutionId(soapModel.getInstitutionId());
		model.setResearcherId(soapModel.getResearcherId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<InstResearcher> toModels(
		InstResearcherSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<InstResearcher> models = new ArrayList<InstResearcher>(
			soapModels.length);

		for (InstResearcherSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public InstResearcherModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _institutionResearcherId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInstitutionResearcherId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _institutionResearcherId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return InstResearcher.class;
	}

	@Override
	public String getModelClassName() {
		return InstResearcher.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<InstResearcher, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<InstResearcher, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InstResearcher, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((InstResearcher)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<InstResearcher, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<InstResearcher, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(InstResearcher)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<InstResearcher, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<InstResearcher, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<InstResearcher, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<InstResearcher, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<InstResearcher, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<InstResearcher, Object>>();
		Map<String, BiConsumer<InstResearcher, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<InstResearcher, ?>>();

		attributeGetterFunctions.put("uuid", InstResearcher::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<InstResearcher, String>)InstResearcher::setUuid);
		attributeGetterFunctions.put(
			"institutionResearcherId",
			InstResearcher::getInstitutionResearcherId);
		attributeSetterBiConsumers.put(
			"institutionResearcherId",
			(BiConsumer<InstResearcher, Long>)
				InstResearcher::setInstitutionResearcherId);
		attributeGetterFunctions.put("groupId", InstResearcher::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<InstResearcher, Long>)InstResearcher::setGroupId);
		attributeGetterFunctions.put("companyId", InstResearcher::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<InstResearcher, Long>)InstResearcher::setCompanyId);
		attributeGetterFunctions.put("projectId", InstResearcher::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<InstResearcher, Long>)InstResearcher::setProjectId);
		attributeGetterFunctions.put("userId", InstResearcher::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<InstResearcher, Long>)InstResearcher::setUserId);
		attributeGetterFunctions.put("userName", InstResearcher::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<InstResearcher, String>)InstResearcher::setUserName);
		attributeGetterFunctions.put(
			"createDate", InstResearcher::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<InstResearcher, Date>)InstResearcher::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", InstResearcher::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<InstResearcher, Date>)InstResearcher::setModifiedDate);
		attributeGetterFunctions.put(
			"institutionId", InstResearcher::getInstitutionId);
		attributeSetterBiConsumers.put(
			"institutionId",
			(BiConsumer<InstResearcher, Long>)InstResearcher::setInstitutionId);
		attributeGetterFunctions.put(
			"researcherId", InstResearcher::getResearcherId);
		attributeSetterBiConsumers.put(
			"researcherId",
			(BiConsumer<InstResearcher, Long>)InstResearcher::setResearcherId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getInstitutionResearcherId() {
		return _institutionResearcherId;
	}

	@Override
	public void setInstitutionResearcherId(long institutionResearcherId) {
		_institutionResearcherId = institutionResearcherId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@JSON
	@Override
	public long getResearcherId() {
		return _researcherId;
	}

	@Override
	public void setResearcherId(long researcherId) {
		_columnBitmask |= RESEARCHERID_COLUMN_BITMASK;

		if (!_setOriginalResearcherId) {
			_setOriginalResearcherId = true;

			_originalResearcherId = _researcherId;
		}

		_researcherId = researcherId;
	}

	public long getOriginalResearcherId() {
		return _originalResearcherId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(InstResearcher.class.getName()));
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), InstResearcher.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public InstResearcher toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, InstResearcher>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InstResearcherImpl instResearcherImpl = new InstResearcherImpl();

		instResearcherImpl.setUuid(getUuid());
		instResearcherImpl.setInstitutionResearcherId(
			getInstitutionResearcherId());
		instResearcherImpl.setGroupId(getGroupId());
		instResearcherImpl.setCompanyId(getCompanyId());
		instResearcherImpl.setProjectId(getProjectId());
		instResearcherImpl.setUserId(getUserId());
		instResearcherImpl.setUserName(getUserName());
		instResearcherImpl.setCreateDate(getCreateDate());
		instResearcherImpl.setModifiedDate(getModifiedDate());
		instResearcherImpl.setInstitutionId(getInstitutionId());
		instResearcherImpl.setResearcherId(getResearcherId());

		instResearcherImpl.resetOriginalValues();

		return instResearcherImpl;
	}

	@Override
	public int compareTo(InstResearcher instResearcher) {
		long primaryKey = instResearcher.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof InstResearcher)) {
			return false;
		}

		InstResearcher instResearcher = (InstResearcher)object;

		long primaryKey = instResearcher.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;
		_originalInstitutionId = _institutionId;

		_setOriginalInstitutionId = false;

		_originalResearcherId = _researcherId;

		_setOriginalResearcherId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<InstResearcher> toCacheModel() {
		InstResearcherCacheModel instResearcherCacheModel =
			new InstResearcherCacheModel();

		instResearcherCacheModel.uuid = getUuid();

		String uuid = instResearcherCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			instResearcherCacheModel.uuid = null;
		}

		instResearcherCacheModel.institutionResearcherId =
			getInstitutionResearcherId();

		instResearcherCacheModel.groupId = getGroupId();

		instResearcherCacheModel.companyId = getCompanyId();

		instResearcherCacheModel.projectId = getProjectId();

		instResearcherCacheModel.userId = getUserId();

		instResearcherCacheModel.userName = getUserName();

		String userName = instResearcherCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			instResearcherCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			instResearcherCacheModel.createDate = createDate.getTime();
		}
		else {
			instResearcherCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			instResearcherCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			instResearcherCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		instResearcherCacheModel.institutionId = getInstitutionId();

		instResearcherCacheModel.researcherId = getResearcherId();

		return instResearcherCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<InstResearcher, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<InstResearcher, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InstResearcher, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((InstResearcher)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<InstResearcher, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<InstResearcher, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InstResearcher, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((InstResearcher)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, InstResearcher>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					InstResearcher.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _institutionResearcherId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _researcherId;
	private long _originalResearcherId;
	private boolean _setOriginalResearcherId;
	private long _columnBitmask;
	private InstResearcher _escapedModel;

}