/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.MetaGroup;
import com.dhsoft.edc.backend.model.MetaGroupModel;
import com.dhsoft.edc.backend.model.MetaGroupSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MetaGroup service. Represents a row in the &quot;EDC_MetaGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MetaGroupModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MetaGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MetaGroupImpl
 * @generated
 */
@JSON(strict = true)
public class MetaGroupModelImpl
	extends BaseModelImpl<MetaGroup> implements MetaGroupModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a meta group model instance should use the <code>MetaGroup</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_MetaGroup";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"metaGroupId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"groupCode", Types.VARCHAR},
		{"groupName", Types.VARCHAR}, {"type_", Types.VARCHAR},
		{"active_", Types.BOOLEAN}, {"inactiveDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("metaGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("groupCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("inactiveDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_MetaGroup (uuid_ VARCHAR(75) null,metaGroupId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,groupCode VARCHAR(75) null,groupName VARCHAR(75) null,type_ VARCHAR(75) null,active_ BOOLEAN,inactiveDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table EDC_MetaGroup";

	public static final String ORDER_BY_JPQL =
		" ORDER BY metaGroup.groupCode ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_MetaGroup.groupCode ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPCODE_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long PROJECTID_COLUMN_BITMASK = 8L;

	public static final long USERID_COLUMN_BITMASK = 16L;

	public static final long UUID_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MetaGroup toModel(MetaGroupSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MetaGroup model = new MetaGroupImpl();

		model.setUuid(soapModel.getUuid());
		model.setMetaGroupId(soapModel.getMetaGroupId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setGroupCode(soapModel.getGroupCode());
		model.setGroupName(soapModel.getGroupName());
		model.setType(soapModel.getType());
		model.setActive(soapModel.getActive());
		model.setInactiveDate(soapModel.getInactiveDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MetaGroup> toModels(MetaGroupSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MetaGroup> models = new ArrayList<MetaGroup>(soapModels.length);

		for (MetaGroupSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MetaGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _metaGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMetaGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _metaGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MetaGroup.class;
	}

	@Override
	public String getModelClassName() {
		return MetaGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MetaGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MetaGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MetaGroup, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MetaGroup)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MetaGroup, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MetaGroup, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MetaGroup)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MetaGroup, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MetaGroup, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MetaGroup, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MetaGroup, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MetaGroup, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MetaGroup, Object>>();
		Map<String, BiConsumer<MetaGroup, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MetaGroup, ?>>();

		attributeGetterFunctions.put("uuid", MetaGroup::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<MetaGroup, String>)MetaGroup::setUuid);
		attributeGetterFunctions.put("metaGroupId", MetaGroup::getMetaGroupId);
		attributeSetterBiConsumers.put(
			"metaGroupId",
			(BiConsumer<MetaGroup, Long>)MetaGroup::setMetaGroupId);
		attributeGetterFunctions.put("groupId", MetaGroup::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<MetaGroup, Long>)MetaGroup::setGroupId);
		attributeGetterFunctions.put("companyId", MetaGroup::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<MetaGroup, Long>)MetaGroup::setCompanyId);
		attributeGetterFunctions.put("projectId", MetaGroup::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId", (BiConsumer<MetaGroup, Long>)MetaGroup::setProjectId);
		attributeGetterFunctions.put("userId", MetaGroup::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<MetaGroup, Long>)MetaGroup::setUserId);
		attributeGetterFunctions.put("userName", MetaGroup::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<MetaGroup, String>)MetaGroup::setUserName);
		attributeGetterFunctions.put("createDate", MetaGroup::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MetaGroup, Date>)MetaGroup::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MetaGroup::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MetaGroup, Date>)MetaGroup::setModifiedDate);
		attributeGetterFunctions.put("status", MetaGroup::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<MetaGroup, Integer>)MetaGroup::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", MetaGroup::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<MetaGroup, Long>)MetaGroup::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", MetaGroup::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<MetaGroup, String>)MetaGroup::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", MetaGroup::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<MetaGroup, Date>)MetaGroup::setStatusDate);
		attributeGetterFunctions.put("groupCode", MetaGroup::getGroupCode);
		attributeSetterBiConsumers.put(
			"groupCode",
			(BiConsumer<MetaGroup, String>)MetaGroup::setGroupCode);
		attributeGetterFunctions.put("groupName", MetaGroup::getGroupName);
		attributeSetterBiConsumers.put(
			"groupName",
			(BiConsumer<MetaGroup, String>)MetaGroup::setGroupName);
		attributeGetterFunctions.put("type", MetaGroup::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<MetaGroup, String>)MetaGroup::setType);
		attributeGetterFunctions.put("active", MetaGroup::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<MetaGroup, Boolean>)MetaGroup::setActive);
		attributeGetterFunctions.put(
			"inactiveDate", MetaGroup::getInactiveDate);
		attributeSetterBiConsumers.put(
			"inactiveDate",
			(BiConsumer<MetaGroup, Date>)MetaGroup::setInactiveDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getMetaGroupId() {
		return _metaGroupId;
	}

	@Override
	public void setMetaGroupId(long metaGroupId) {
		_metaGroupId = metaGroupId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getGroupCode() {
		if (_groupCode == null) {
			return "";
		}
		else {
			return _groupCode;
		}
	}

	@Override
	public void setGroupCode(String groupCode) {
		_columnBitmask = -1L;

		if (_originalGroupCode == null) {
			_originalGroupCode = _groupCode;
		}

		_groupCode = groupCode;
	}

	public String getOriginalGroupCode() {
		return GetterUtil.getString(_originalGroupCode);
	}

	@JSON
	@Override
	public String getGroupName() {
		if (_groupName == null) {
			return "";
		}
		else {
			return _groupName;
		}
	}

	@Override
	public void setGroupName(String groupName) {
		_groupName = groupName;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@JSON
	@Override
	public Boolean getActive() {
		return _active;
	}

	@Override
	public void setActive(Boolean active) {
		_active = active;
	}

	@JSON
	@Override
	public Date getInactiveDate() {
		return _inactiveDate;
	}

	@Override
	public void setInactiveDate(Date inactiveDate) {
		_inactiveDate = inactiveDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(MetaGroup.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MetaGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MetaGroup toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MetaGroup>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MetaGroupImpl metaGroupImpl = new MetaGroupImpl();

		metaGroupImpl.setUuid(getUuid());
		metaGroupImpl.setMetaGroupId(getMetaGroupId());
		metaGroupImpl.setGroupId(getGroupId());
		metaGroupImpl.setCompanyId(getCompanyId());
		metaGroupImpl.setProjectId(getProjectId());
		metaGroupImpl.setUserId(getUserId());
		metaGroupImpl.setUserName(getUserName());
		metaGroupImpl.setCreateDate(getCreateDate());
		metaGroupImpl.setModifiedDate(getModifiedDate());
		metaGroupImpl.setStatus(getStatus());
		metaGroupImpl.setStatusByUserId(getStatusByUserId());
		metaGroupImpl.setStatusByUserName(getStatusByUserName());
		metaGroupImpl.setStatusDate(getStatusDate());
		metaGroupImpl.setGroupCode(getGroupCode());
		metaGroupImpl.setGroupName(getGroupName());
		metaGroupImpl.setType(getType());
		metaGroupImpl.setActive(getActive());
		metaGroupImpl.setInactiveDate(getInactiveDate());

		metaGroupImpl.resetOriginalValues();

		return metaGroupImpl;
	}

	@Override
	public int compareTo(MetaGroup metaGroup) {
		int value = 0;

		value = getGroupCode().compareTo(metaGroup.getGroupCode());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MetaGroup)) {
			return false;
		}

		MetaGroup metaGroup = (MetaGroup)object;

		long primaryKey = metaGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;

		_originalGroupCode = _groupCode;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MetaGroup> toCacheModel() {
		MetaGroupCacheModel metaGroupCacheModel = new MetaGroupCacheModel();

		metaGroupCacheModel.uuid = getUuid();

		String uuid = metaGroupCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			metaGroupCacheModel.uuid = null;
		}

		metaGroupCacheModel.metaGroupId = getMetaGroupId();

		metaGroupCacheModel.groupId = getGroupId();

		metaGroupCacheModel.companyId = getCompanyId();

		metaGroupCacheModel.projectId = getProjectId();

		metaGroupCacheModel.userId = getUserId();

		metaGroupCacheModel.userName = getUserName();

		String userName = metaGroupCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			metaGroupCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			metaGroupCacheModel.createDate = createDate.getTime();
		}
		else {
			metaGroupCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			metaGroupCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			metaGroupCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		metaGroupCacheModel.status = getStatus();

		metaGroupCacheModel.statusByUserId = getStatusByUserId();

		metaGroupCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = metaGroupCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			metaGroupCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			metaGroupCacheModel.statusDate = statusDate.getTime();
		}
		else {
			metaGroupCacheModel.statusDate = Long.MIN_VALUE;
		}

		metaGroupCacheModel.groupCode = getGroupCode();

		String groupCode = metaGroupCacheModel.groupCode;

		if ((groupCode != null) && (groupCode.length() == 0)) {
			metaGroupCacheModel.groupCode = null;
		}

		metaGroupCacheModel.groupName = getGroupName();

		String groupName = metaGroupCacheModel.groupName;

		if ((groupName != null) && (groupName.length() == 0)) {
			metaGroupCacheModel.groupName = null;
		}

		metaGroupCacheModel.type = getType();

		String type = metaGroupCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			metaGroupCacheModel.type = null;
		}

		Boolean active = getActive();

		if (active != null) {
			metaGroupCacheModel.active = active;
		}

		Date inactiveDate = getInactiveDate();

		if (inactiveDate != null) {
			metaGroupCacheModel.inactiveDate = inactiveDate.getTime();
		}
		else {
			metaGroupCacheModel.inactiveDate = Long.MIN_VALUE;
		}

		return metaGroupCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MetaGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MetaGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MetaGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MetaGroup)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MetaGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MetaGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MetaGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MetaGroup)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MetaGroup>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MetaGroup.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _metaGroupId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _groupCode;
	private String _originalGroupCode;
	private String _groupName;
	private String _type;
	private Boolean _active;
	private Date _inactiveDate;
	private long _columnBitmask;
	private MetaGroup _escapedModel;

}