/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.MetaCode;
import com.dhsoft.edc.backend.model.MetaCodeModel;
import com.dhsoft.edc.backend.model.MetaCodeSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MetaCode service. Represents a row in the &quot;EDC_MetaCode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MetaCodeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MetaCodeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MetaCodeImpl
 * @generated
 */
@JSON(strict = true)
public class MetaCodeModelImpl
	extends BaseModelImpl<MetaCode> implements MetaCodeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a meta code model instance should use the <code>MetaCode</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_MetaCode";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"metaCodeId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"groupCode", Types.VARCHAR},
		{"code_", Types.VARCHAR}, {"label", Types.VARCHAR},
		{"valueType", Types.VARCHAR}, {"value", Types.VARCHAR},
		{"active_", Types.BOOLEAN}, {"inactiveDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("metaCodeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("groupCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("label", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("valueType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("inactiveDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_MetaCode (uuid_ VARCHAR(75) null,metaCodeId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,groupCode VARCHAR(75) null,code_ VARCHAR(75) null,label VARCHAR(75) null,valueType VARCHAR(75) null,value VARCHAR(75) null,active_ BOOLEAN,inactiveDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table EDC_MetaCode";

	public static final String ORDER_BY_JPQL = " ORDER BY metaCode.code ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_MetaCode.code_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CODE_COLUMN_BITMASK = 1L;

	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	public static final long GROUPCODE_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long PROJECTID_COLUMN_BITMASK = 16L;

	public static final long USERID_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MetaCode toModel(MetaCodeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MetaCode model = new MetaCodeImpl();

		model.setUuid(soapModel.getUuid());
		model.setMetaCodeId(soapModel.getMetaCodeId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setGroupCode(soapModel.getGroupCode());
		model.setCode(soapModel.getCode());
		model.setLabel(soapModel.getLabel());
		model.setValueType(soapModel.getValueType());
		model.setValue(soapModel.getValue());
		model.setActive(soapModel.getActive());
		model.setInactiveDate(soapModel.getInactiveDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MetaCode> toModels(MetaCodeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MetaCode> models = new ArrayList<MetaCode>(soapModels.length);

		for (MetaCodeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MetaCodeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _metaCodeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMetaCodeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _metaCodeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MetaCode.class;
	}

	@Override
	public String getModelClassName() {
		return MetaCode.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MetaCode, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MetaCode, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MetaCode, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MetaCode)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MetaCode, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MetaCode, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MetaCode)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MetaCode, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MetaCode, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MetaCode, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MetaCode, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MetaCode, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MetaCode, Object>>();
		Map<String, BiConsumer<MetaCode, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MetaCode, ?>>();

		attributeGetterFunctions.put("uuid", MetaCode::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<MetaCode, String>)MetaCode::setUuid);
		attributeGetterFunctions.put("metaCodeId", MetaCode::getMetaCodeId);
		attributeSetterBiConsumers.put(
			"metaCodeId", (BiConsumer<MetaCode, Long>)MetaCode::setMetaCodeId);
		attributeGetterFunctions.put("groupId", MetaCode::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<MetaCode, Long>)MetaCode::setGroupId);
		attributeGetterFunctions.put("companyId", MetaCode::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<MetaCode, Long>)MetaCode::setCompanyId);
		attributeGetterFunctions.put("projectId", MetaCode::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId", (BiConsumer<MetaCode, Long>)MetaCode::setProjectId);
		attributeGetterFunctions.put("userId", MetaCode::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<MetaCode, Long>)MetaCode::setUserId);
		attributeGetterFunctions.put("userName", MetaCode::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<MetaCode, String>)MetaCode::setUserName);
		attributeGetterFunctions.put("createDate", MetaCode::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<MetaCode, Date>)MetaCode::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", MetaCode::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MetaCode, Date>)MetaCode::setModifiedDate);
		attributeGetterFunctions.put("status", MetaCode::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<MetaCode, Integer>)MetaCode::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", MetaCode::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<MetaCode, Long>)MetaCode::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", MetaCode::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<MetaCode, String>)MetaCode::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", MetaCode::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<MetaCode, Date>)MetaCode::setStatusDate);
		attributeGetterFunctions.put("groupCode", MetaCode::getGroupCode);
		attributeSetterBiConsumers.put(
			"groupCode", (BiConsumer<MetaCode, String>)MetaCode::setGroupCode);
		attributeGetterFunctions.put("code", MetaCode::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<MetaCode, String>)MetaCode::setCode);
		attributeGetterFunctions.put("label", MetaCode::getLabel);
		attributeSetterBiConsumers.put(
			"label", (BiConsumer<MetaCode, String>)MetaCode::setLabel);
		attributeGetterFunctions.put("valueType", MetaCode::getValueType);
		attributeSetterBiConsumers.put(
			"valueType", (BiConsumer<MetaCode, String>)MetaCode::setValueType);
		attributeGetterFunctions.put("value", MetaCode::getValue);
		attributeSetterBiConsumers.put(
			"value", (BiConsumer<MetaCode, String>)MetaCode::setValue);
		attributeGetterFunctions.put("active", MetaCode::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<MetaCode, Boolean>)MetaCode::setActive);
		attributeGetterFunctions.put("inactiveDate", MetaCode::getInactiveDate);
		attributeSetterBiConsumers.put(
			"inactiveDate",
			(BiConsumer<MetaCode, Date>)MetaCode::setInactiveDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getMetaCodeId() {
		return _metaCodeId;
	}

	@Override
	public void setMetaCodeId(long metaCodeId) {
		_metaCodeId = metaCodeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getGroupCode() {
		if (_groupCode == null) {
			return "";
		}
		else {
			return _groupCode;
		}
	}

	@Override
	public void setGroupCode(String groupCode) {
		_columnBitmask |= GROUPCODE_COLUMN_BITMASK;

		if (_originalGroupCode == null) {
			_originalGroupCode = _groupCode;
		}

		_groupCode = groupCode;
	}

	public String getOriginalGroupCode() {
		return GetterUtil.getString(_originalGroupCode);
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask = -1L;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public String getLabel() {
		if (_label == null) {
			return "";
		}
		else {
			return _label;
		}
	}

	@Override
	public void setLabel(String label) {
		_label = label;
	}

	@JSON
	@Override
	public String getValueType() {
		if (_valueType == null) {
			return "";
		}
		else {
			return _valueType;
		}
	}

	@Override
	public void setValueType(String valueType) {
		_valueType = valueType;
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	@JSON
	@Override
	public Boolean getActive() {
		return _active;
	}

	@Override
	public void setActive(Boolean active) {
		_active = active;
	}

	@JSON
	@Override
	public Date getInactiveDate() {
		return _inactiveDate;
	}

	@Override
	public void setInactiveDate(Date inactiveDate) {
		_inactiveDate = inactiveDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(MetaCode.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MetaCode.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MetaCode toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MetaCode>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MetaCodeImpl metaCodeImpl = new MetaCodeImpl();

		metaCodeImpl.setUuid(getUuid());
		metaCodeImpl.setMetaCodeId(getMetaCodeId());
		metaCodeImpl.setGroupId(getGroupId());
		metaCodeImpl.setCompanyId(getCompanyId());
		metaCodeImpl.setProjectId(getProjectId());
		metaCodeImpl.setUserId(getUserId());
		metaCodeImpl.setUserName(getUserName());
		metaCodeImpl.setCreateDate(getCreateDate());
		metaCodeImpl.setModifiedDate(getModifiedDate());
		metaCodeImpl.setStatus(getStatus());
		metaCodeImpl.setStatusByUserId(getStatusByUserId());
		metaCodeImpl.setStatusByUserName(getStatusByUserName());
		metaCodeImpl.setStatusDate(getStatusDate());
		metaCodeImpl.setGroupCode(getGroupCode());
		metaCodeImpl.setCode(getCode());
		metaCodeImpl.setLabel(getLabel());
		metaCodeImpl.setValueType(getValueType());
		metaCodeImpl.setValue(getValue());
		metaCodeImpl.setActive(getActive());
		metaCodeImpl.setInactiveDate(getInactiveDate());

		metaCodeImpl.resetOriginalValues();

		return metaCodeImpl;
	}

	@Override
	public int compareTo(MetaCode metaCode) {
		int value = 0;

		value = getCode().compareTo(metaCode.getCode());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MetaCode)) {
			return false;
		}

		MetaCode metaCode = (MetaCode)object;

		long primaryKey = metaCode.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;

		_originalGroupCode = _groupCode;

		_originalCode = _code;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MetaCode> toCacheModel() {
		MetaCodeCacheModel metaCodeCacheModel = new MetaCodeCacheModel();

		metaCodeCacheModel.uuid = getUuid();

		String uuid = metaCodeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			metaCodeCacheModel.uuid = null;
		}

		metaCodeCacheModel.metaCodeId = getMetaCodeId();

		metaCodeCacheModel.groupId = getGroupId();

		metaCodeCacheModel.companyId = getCompanyId();

		metaCodeCacheModel.projectId = getProjectId();

		metaCodeCacheModel.userId = getUserId();

		metaCodeCacheModel.userName = getUserName();

		String userName = metaCodeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			metaCodeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			metaCodeCacheModel.createDate = createDate.getTime();
		}
		else {
			metaCodeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			metaCodeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			metaCodeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		metaCodeCacheModel.status = getStatus();

		metaCodeCacheModel.statusByUserId = getStatusByUserId();

		metaCodeCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = metaCodeCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			metaCodeCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			metaCodeCacheModel.statusDate = statusDate.getTime();
		}
		else {
			metaCodeCacheModel.statusDate = Long.MIN_VALUE;
		}

		metaCodeCacheModel.groupCode = getGroupCode();

		String groupCode = metaCodeCacheModel.groupCode;

		if ((groupCode != null) && (groupCode.length() == 0)) {
			metaCodeCacheModel.groupCode = null;
		}

		metaCodeCacheModel.code = getCode();

		String code = metaCodeCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			metaCodeCacheModel.code = null;
		}

		metaCodeCacheModel.label = getLabel();

		String label = metaCodeCacheModel.label;

		if ((label != null) && (label.length() == 0)) {
			metaCodeCacheModel.label = null;
		}

		metaCodeCacheModel.valueType = getValueType();

		String valueType = metaCodeCacheModel.valueType;

		if ((valueType != null) && (valueType.length() == 0)) {
			metaCodeCacheModel.valueType = null;
		}

		metaCodeCacheModel.value = getValue();

		String value = metaCodeCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			metaCodeCacheModel.value = null;
		}

		Boolean active = getActive();

		if (active != null) {
			metaCodeCacheModel.active = active;
		}

		Date inactiveDate = getInactiveDate();

		if (inactiveDate != null) {
			metaCodeCacheModel.inactiveDate = inactiveDate.getTime();
		}
		else {
			metaCodeCacheModel.inactiveDate = Long.MIN_VALUE;
		}

		return metaCodeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MetaCode, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MetaCode, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MetaCode, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MetaCode)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MetaCode, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MetaCode, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MetaCode, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MetaCode)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MetaCode>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MetaCode.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _metaCodeId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _groupCode;
	private String _originalGroupCode;
	private String _code;
	private String _originalCode;
	private String _label;
	private String _valueType;
	private String _value;
	private Boolean _active;
	private Date _inactiveDate;
	private long _columnBitmask;
	private MetaCode _escapedModel;

}