/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.QueryLink;
import com.dhsoft.edc.backend.model.QueryLinkModel;
import com.dhsoft.edc.backend.model.QueryLinkSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the QueryLink service. Represents a row in the &quot;EDC_QueryLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>QueryLinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QueryLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QueryLinkImpl
 * @generated
 */
@JSON(strict = true)
public class QueryLinkModelImpl
	extends BaseModelImpl<QueryLink> implements QueryLinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a query link model instance should use the <code>QueryLink</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_QueryLink";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"queryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"subjectId", Types.BIGINT},
		{"visitGroupId", Types.BIGINT}, {"visitDefinitionId", Types.BIGINT},
		{"visitCRFId", Types.BIGINT}, {"subCRFId", Types.BIGINT},
		{"instanceId", Types.BIGINT}, {"itemCode", Types.BIGINT},
		{"sourceType", Types.VARCHAR}, {"scope", Types.VARCHAR},
		{"isTypeManual", Types.VARCHAR}, {"type_", Types.VARCHAR},
		{"openUserId", Types.BIGINT}, {"openUserName", Types.VARCHAR},
		{"openDate", Types.TIMESTAMP}, {"openComment", Types.VARCHAR},
		{"answerUserID", Types.BIGINT}, {"answerUserName", Types.VARCHAR},
		{"answerDate", Types.TIMESTAMP}, {"answerComment", Types.VARCHAR},
		{"closeUserID", Types.BIGINT}, {"closeUserName", Types.VARCHAR},
		{"closeDate", Types.TIMESTAMP}, {"closeComment", Types.VARCHAR},
		{"queryStatus", Types.INTEGER}, {"isReopen", Types.VARCHAR},
		{"reopenId", Types.BIGINT}, {"ruleId", Types.BIGINT},
		{"ruleInfo", Types.VARCHAR}, {"activeStatus", Types.INTEGER},
		{"inactiveDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("queryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("subjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("visitGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("visitDefinitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("visitCRFId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subCRFId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("instanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("itemCode", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sourceType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scope", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isTypeManual", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("openUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("openUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("openDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("openComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("answerUserID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("answerUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("answerDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("answerComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("closeUserID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("closeUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("closeDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("closeComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("queryStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isReopen", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reopenId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ruleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ruleInfo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("activeStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("inactiveDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_QueryLink (uuid_ VARCHAR(75) null,queryId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,subjectId LONG,visitGroupId LONG,visitDefinitionId LONG,visitCRFId LONG,subCRFId LONG,instanceId LONG,itemCode LONG,sourceType VARCHAR(75) null,scope VARCHAR(75) null,isTypeManual VARCHAR(75) null,type_ VARCHAR(75) null,openUserId LONG,openUserName VARCHAR(75) null,openDate DATE null,openComment VARCHAR(75) null,answerUserID LONG,answerUserName VARCHAR(75) null,answerDate DATE null,answerComment VARCHAR(75) null,closeUserID LONG,closeUserName VARCHAR(75) null,closeDate DATE null,closeComment VARCHAR(75) null,queryStatus INTEGER,isReopen VARCHAR(75) null,reopenId LONG,ruleId LONG,ruleInfo VARCHAR(75) null,activeStatus INTEGER,inactiveDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table EDC_QueryLink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY queryLink.queryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_QueryLink.queryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ANSWERUSERID_COLUMN_BITMASK = 1L;

	public static final long CLOSEUSERID_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long INSTANCEID_COLUMN_BITMASK = 16L;

	public static final long ITEMCODE_COLUMN_BITMASK = 32L;

	public static final long OPENUSERID_COLUMN_BITMASK = 64L;

	public static final long PROJECTID_COLUMN_BITMASK = 128L;

	public static final long REOPENID_COLUMN_BITMASK = 256L;

	public static final long RULEID_COLUMN_BITMASK = 512L;

	public static final long SUBCRFID_COLUMN_BITMASK = 1024L;

	public static final long SUBJECTID_COLUMN_BITMASK = 2048L;

	public static final long USERID_COLUMN_BITMASK = 4096L;

	public static final long UUID_COLUMN_BITMASK = 8192L;

	public static final long VISITCRFID_COLUMN_BITMASK = 16384L;

	public static final long VISITDEFINITIONID_COLUMN_BITMASK = 32768L;

	public static final long VISITGROUPID_COLUMN_BITMASK = 65536L;

	public static final long QUERYID_COLUMN_BITMASK = 131072L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QueryLink toModel(QueryLinkSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QueryLink model = new QueryLinkImpl();

		model.setUuid(soapModel.getUuid());
		model.setQueryId(soapModel.getQueryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setSubjectId(soapModel.getSubjectId());
		model.setVisitGroupId(soapModel.getVisitGroupId());
		model.setVisitDefinitionId(soapModel.getVisitDefinitionId());
		model.setVisitCRFId(soapModel.getVisitCRFId());
		model.setSubCRFId(soapModel.getSubCRFId());
		model.setInstanceId(soapModel.getInstanceId());
		model.setItemCode(soapModel.getItemCode());
		model.setSourceType(soapModel.getSourceType());
		model.setScope(soapModel.getScope());
		model.setIsTypeManual(soapModel.getIsTypeManual());
		model.setType(soapModel.getType());
		model.setOpenUserId(soapModel.getOpenUserId());
		model.setOpenUserName(soapModel.getOpenUserName());
		model.setOpenDate(soapModel.getOpenDate());
		model.setOpenComment(soapModel.getOpenComment());
		model.setAnswerUserID(soapModel.getAnswerUserID());
		model.setAnswerUserName(soapModel.getAnswerUserName());
		model.setAnswerDate(soapModel.getAnswerDate());
		model.setAnswerComment(soapModel.getAnswerComment());
		model.setCloseUserID(soapModel.getCloseUserID());
		model.setCloseUserName(soapModel.getCloseUserName());
		model.setCloseDate(soapModel.getCloseDate());
		model.setCloseComment(soapModel.getCloseComment());
		model.setQueryStatus(soapModel.getQueryStatus());
		model.setIsReopen(soapModel.getIsReopen());
		model.setReopenId(soapModel.getReopenId());
		model.setRuleId(soapModel.getRuleId());
		model.setRuleInfo(soapModel.getRuleInfo());
		model.setActiveStatus(soapModel.getActiveStatus());
		model.setInactiveDate(soapModel.getInactiveDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QueryLink> toModels(QueryLinkSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QueryLink> models = new ArrayList<QueryLink>(soapModels.length);

		for (QueryLinkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public QueryLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _queryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setQueryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _queryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QueryLink.class;
	}

	@Override
	public String getModelClassName() {
		return QueryLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<QueryLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<QueryLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QueryLink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((QueryLink)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<QueryLink, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<QueryLink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(QueryLink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<QueryLink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<QueryLink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<QueryLink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<QueryLink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<QueryLink, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<QueryLink, Object>>();
		Map<String, BiConsumer<QueryLink, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<QueryLink, ?>>();

		attributeGetterFunctions.put("uuid", QueryLink::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<QueryLink, String>)QueryLink::setUuid);
		attributeGetterFunctions.put("queryId", QueryLink::getQueryId);
		attributeSetterBiConsumers.put(
			"queryId", (BiConsumer<QueryLink, Long>)QueryLink::setQueryId);
		attributeGetterFunctions.put("groupId", QueryLink::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<QueryLink, Long>)QueryLink::setGroupId);
		attributeGetterFunctions.put("companyId", QueryLink::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<QueryLink, Long>)QueryLink::setCompanyId);
		attributeGetterFunctions.put("projectId", QueryLink::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId", (BiConsumer<QueryLink, Long>)QueryLink::setProjectId);
		attributeGetterFunctions.put("userId", QueryLink::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<QueryLink, Long>)QueryLink::setUserId);
		attributeGetterFunctions.put("userName", QueryLink::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<QueryLink, String>)QueryLink::setUserName);
		attributeGetterFunctions.put("createDate", QueryLink::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<QueryLink, Date>)QueryLink::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", QueryLink::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<QueryLink, Date>)QueryLink::setModifiedDate);
		attributeGetterFunctions.put("subjectId", QueryLink::getSubjectId);
		attributeSetterBiConsumers.put(
			"subjectId", (BiConsumer<QueryLink, Long>)QueryLink::setSubjectId);
		attributeGetterFunctions.put(
			"visitGroupId", QueryLink::getVisitGroupId);
		attributeSetterBiConsumers.put(
			"visitGroupId",
			(BiConsumer<QueryLink, Long>)QueryLink::setVisitGroupId);
		attributeGetterFunctions.put(
			"visitDefinitionId", QueryLink::getVisitDefinitionId);
		attributeSetterBiConsumers.put(
			"visitDefinitionId",
			(BiConsumer<QueryLink, Long>)QueryLink::setVisitDefinitionId);
		attributeGetterFunctions.put("visitCRFId", QueryLink::getVisitCRFId);
		attributeSetterBiConsumers.put(
			"visitCRFId",
			(BiConsumer<QueryLink, Long>)QueryLink::setVisitCRFId);
		attributeGetterFunctions.put("subCRFId", QueryLink::getSubCRFId);
		attributeSetterBiConsumers.put(
			"subCRFId", (BiConsumer<QueryLink, Long>)QueryLink::setSubCRFId);
		attributeGetterFunctions.put("instanceId", QueryLink::getInstanceId);
		attributeSetterBiConsumers.put(
			"instanceId",
			(BiConsumer<QueryLink, Long>)QueryLink::setInstanceId);
		attributeGetterFunctions.put("itemCode", QueryLink::getItemCode);
		attributeSetterBiConsumers.put(
			"itemCode", (BiConsumer<QueryLink, Long>)QueryLink::setItemCode);
		attributeGetterFunctions.put("sourceType", QueryLink::getSourceType);
		attributeSetterBiConsumers.put(
			"sourceType",
			(BiConsumer<QueryLink, String>)QueryLink::setSourceType);
		attributeGetterFunctions.put("scope", QueryLink::getScope);
		attributeSetterBiConsumers.put(
			"scope", (BiConsumer<QueryLink, String>)QueryLink::setScope);
		attributeGetterFunctions.put(
			"isTypeManual", QueryLink::getIsTypeManual);
		attributeSetterBiConsumers.put(
			"isTypeManual",
			(BiConsumer<QueryLink, String>)QueryLink::setIsTypeManual);
		attributeGetterFunctions.put("type", QueryLink::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<QueryLink, String>)QueryLink::setType);
		attributeGetterFunctions.put("openUserId", QueryLink::getOpenUserId);
		attributeSetterBiConsumers.put(
			"openUserId",
			(BiConsumer<QueryLink, Long>)QueryLink::setOpenUserId);
		attributeGetterFunctions.put(
			"openUserName", QueryLink::getOpenUserName);
		attributeSetterBiConsumers.put(
			"openUserName",
			(BiConsumer<QueryLink, String>)QueryLink::setOpenUserName);
		attributeGetterFunctions.put("openDate", QueryLink::getOpenDate);
		attributeSetterBiConsumers.put(
			"openDate", (BiConsumer<QueryLink, Date>)QueryLink::setOpenDate);
		attributeGetterFunctions.put("openComment", QueryLink::getOpenComment);
		attributeSetterBiConsumers.put(
			"openComment",
			(BiConsumer<QueryLink, String>)QueryLink::setOpenComment);
		attributeGetterFunctions.put(
			"answerUserID", QueryLink::getAnswerUserID);
		attributeSetterBiConsumers.put(
			"answerUserID",
			(BiConsumer<QueryLink, Long>)QueryLink::setAnswerUserID);
		attributeGetterFunctions.put(
			"answerUserName", QueryLink::getAnswerUserName);
		attributeSetterBiConsumers.put(
			"answerUserName",
			(BiConsumer<QueryLink, String>)QueryLink::setAnswerUserName);
		attributeGetterFunctions.put("answerDate", QueryLink::getAnswerDate);
		attributeSetterBiConsumers.put(
			"answerDate",
			(BiConsumer<QueryLink, Date>)QueryLink::setAnswerDate);
		attributeGetterFunctions.put(
			"answerComment", QueryLink::getAnswerComment);
		attributeSetterBiConsumers.put(
			"answerComment",
			(BiConsumer<QueryLink, String>)QueryLink::setAnswerComment);
		attributeGetterFunctions.put("closeUserID", QueryLink::getCloseUserID);
		attributeSetterBiConsumers.put(
			"closeUserID",
			(BiConsumer<QueryLink, Long>)QueryLink::setCloseUserID);
		attributeGetterFunctions.put(
			"closeUserName", QueryLink::getCloseUserName);
		attributeSetterBiConsumers.put(
			"closeUserName",
			(BiConsumer<QueryLink, String>)QueryLink::setCloseUserName);
		attributeGetterFunctions.put("closeDate", QueryLink::getCloseDate);
		attributeSetterBiConsumers.put(
			"closeDate", (BiConsumer<QueryLink, Date>)QueryLink::setCloseDate);
		attributeGetterFunctions.put(
			"closeComment", QueryLink::getCloseComment);
		attributeSetterBiConsumers.put(
			"closeComment",
			(BiConsumer<QueryLink, String>)QueryLink::setCloseComment);
		attributeGetterFunctions.put("queryStatus", QueryLink::getQueryStatus);
		attributeSetterBiConsumers.put(
			"queryStatus",
			(BiConsumer<QueryLink, Integer>)QueryLink::setQueryStatus);
		attributeGetterFunctions.put("isReopen", QueryLink::getIsReopen);
		attributeSetterBiConsumers.put(
			"isReopen", (BiConsumer<QueryLink, String>)QueryLink::setIsReopen);
		attributeGetterFunctions.put("reopenId", QueryLink::getReopenId);
		attributeSetterBiConsumers.put(
			"reopenId", (BiConsumer<QueryLink, Long>)QueryLink::setReopenId);
		attributeGetterFunctions.put("ruleId", QueryLink::getRuleId);
		attributeSetterBiConsumers.put(
			"ruleId", (BiConsumer<QueryLink, Long>)QueryLink::setRuleId);
		attributeGetterFunctions.put("ruleInfo", QueryLink::getRuleInfo);
		attributeSetterBiConsumers.put(
			"ruleInfo", (BiConsumer<QueryLink, String>)QueryLink::setRuleInfo);
		attributeGetterFunctions.put(
			"activeStatus", QueryLink::getActiveStatus);
		attributeSetterBiConsumers.put(
			"activeStatus",
			(BiConsumer<QueryLink, Integer>)QueryLink::setActiveStatus);
		attributeGetterFunctions.put(
			"inactiveDate", QueryLink::getInactiveDate);
		attributeSetterBiConsumers.put(
			"inactiveDate",
			(BiConsumer<QueryLink, Date>)QueryLink::setInactiveDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getQueryId() {
		return _queryId;
	}

	@Override
	public void setQueryId(long queryId) {
		_queryId = queryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getSubjectId() {
		return _subjectId;
	}

	@Override
	public void setSubjectId(long subjectId) {
		_columnBitmask |= SUBJECTID_COLUMN_BITMASK;

		if (!_setOriginalSubjectId) {
			_setOriginalSubjectId = true;

			_originalSubjectId = _subjectId;
		}

		_subjectId = subjectId;
	}

	public long getOriginalSubjectId() {
		return _originalSubjectId;
	}

	@JSON
	@Override
	public long getVisitGroupId() {
		return _visitGroupId;
	}

	@Override
	public void setVisitGroupId(long visitGroupId) {
		_columnBitmask |= VISITGROUPID_COLUMN_BITMASK;

		if (!_setOriginalVisitGroupId) {
			_setOriginalVisitGroupId = true;

			_originalVisitGroupId = _visitGroupId;
		}

		_visitGroupId = visitGroupId;
	}

	public long getOriginalVisitGroupId() {
		return _originalVisitGroupId;
	}

	@JSON
	@Override
	public long getVisitDefinitionId() {
		return _visitDefinitionId;
	}

	@Override
	public void setVisitDefinitionId(long visitDefinitionId) {
		_columnBitmask |= VISITDEFINITIONID_COLUMN_BITMASK;

		if (!_setOriginalVisitDefinitionId) {
			_setOriginalVisitDefinitionId = true;

			_originalVisitDefinitionId = _visitDefinitionId;
		}

		_visitDefinitionId = visitDefinitionId;
	}

	public long getOriginalVisitDefinitionId() {
		return _originalVisitDefinitionId;
	}

	@JSON
	@Override
	public long getVisitCRFId() {
		return _visitCRFId;
	}

	@Override
	public void setVisitCRFId(long visitCRFId) {
		_columnBitmask |= VISITCRFID_COLUMN_BITMASK;

		if (!_setOriginalVisitCRFId) {
			_setOriginalVisitCRFId = true;

			_originalVisitCRFId = _visitCRFId;
		}

		_visitCRFId = visitCRFId;
	}

	public long getOriginalVisitCRFId() {
		return _originalVisitCRFId;
	}

	@JSON
	@Override
	public long getSubCRFId() {
		return _subCRFId;
	}

	@Override
	public void setSubCRFId(long subCRFId) {
		_columnBitmask |= SUBCRFID_COLUMN_BITMASK;

		if (!_setOriginalSubCRFId) {
			_setOriginalSubCRFId = true;

			_originalSubCRFId = _subCRFId;
		}

		_subCRFId = subCRFId;
	}

	public long getOriginalSubCRFId() {
		return _originalSubCRFId;
	}

	@JSON
	@Override
	public long getInstanceId() {
		return _instanceId;
	}

	@Override
	public void setInstanceId(long instanceId) {
		_columnBitmask |= INSTANCEID_COLUMN_BITMASK;

		if (!_setOriginalInstanceId) {
			_setOriginalInstanceId = true;

			_originalInstanceId = _instanceId;
		}

		_instanceId = instanceId;
	}

	public long getOriginalInstanceId() {
		return _originalInstanceId;
	}

	@JSON
	@Override
	public long getItemCode() {
		return _itemCode;
	}

	@Override
	public void setItemCode(long itemCode) {
		_columnBitmask |= ITEMCODE_COLUMN_BITMASK;

		if (!_setOriginalItemCode) {
			_setOriginalItemCode = true;

			_originalItemCode = _itemCode;
		}

		_itemCode = itemCode;
	}

	public long getOriginalItemCode() {
		return _originalItemCode;
	}

	@JSON
	@Override
	public String getSourceType() {
		if (_sourceType == null) {
			return "";
		}
		else {
			return _sourceType;
		}
	}

	@Override
	public void setSourceType(String sourceType) {
		_sourceType = sourceType;
	}

	@JSON
	@Override
	public String getScope() {
		if (_scope == null) {
			return "";
		}
		else {
			return _scope;
		}
	}

	@Override
	public void setScope(String scope) {
		_scope = scope;
	}

	@JSON
	@Override
	public String getIsTypeManual() {
		if (_isTypeManual == null) {
			return "";
		}
		else {
			return _isTypeManual;
		}
	}

	@Override
	public void setIsTypeManual(String isTypeManual) {
		_isTypeManual = isTypeManual;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@JSON
	@Override
	public long getOpenUserId() {
		return _openUserId;
	}

	@Override
	public void setOpenUserId(long openUserId) {
		_columnBitmask |= OPENUSERID_COLUMN_BITMASK;

		if (!_setOriginalOpenUserId) {
			_setOriginalOpenUserId = true;

			_originalOpenUserId = _openUserId;
		}

		_openUserId = openUserId;
	}

	@Override
	public String getOpenUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getOpenUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setOpenUserUuid(String openUserUuid) {
	}

	public long getOriginalOpenUserId() {
		return _originalOpenUserId;
	}

	@JSON
	@Override
	public String getOpenUserName() {
		if (_openUserName == null) {
			return "";
		}
		else {
			return _openUserName;
		}
	}

	@Override
	public void setOpenUserName(String openUserName) {
		_openUserName = openUserName;
	}

	@JSON
	@Override
	public Date getOpenDate() {
		return _openDate;
	}

	@Override
	public void setOpenDate(Date openDate) {
		_openDate = openDate;
	}

	@JSON
	@Override
	public String getOpenComment() {
		if (_openComment == null) {
			return "";
		}
		else {
			return _openComment;
		}
	}

	@Override
	public void setOpenComment(String openComment) {
		_openComment = openComment;
	}

	@JSON
	@Override
	public long getAnswerUserID() {
		return _answerUserID;
	}

	@Override
	public void setAnswerUserID(long answerUserID) {
		_columnBitmask |= ANSWERUSERID_COLUMN_BITMASK;

		if (!_setOriginalAnswerUserID) {
			_setOriginalAnswerUserID = true;

			_originalAnswerUserID = _answerUserID;
		}

		_answerUserID = answerUserID;
	}

	public long getOriginalAnswerUserID() {
		return _originalAnswerUserID;
	}

	@JSON
	@Override
	public String getAnswerUserName() {
		if (_answerUserName == null) {
			return "";
		}
		else {
			return _answerUserName;
		}
	}

	@Override
	public void setAnswerUserName(String answerUserName) {
		_answerUserName = answerUserName;
	}

	@JSON
	@Override
	public Date getAnswerDate() {
		return _answerDate;
	}

	@Override
	public void setAnswerDate(Date answerDate) {
		_answerDate = answerDate;
	}

	@JSON
	@Override
	public String getAnswerComment() {
		if (_answerComment == null) {
			return "";
		}
		else {
			return _answerComment;
		}
	}

	@Override
	public void setAnswerComment(String answerComment) {
		_answerComment = answerComment;
	}

	@JSON
	@Override
	public long getCloseUserID() {
		return _closeUserID;
	}

	@Override
	public void setCloseUserID(long closeUserID) {
		_columnBitmask |= CLOSEUSERID_COLUMN_BITMASK;

		if (!_setOriginalCloseUserID) {
			_setOriginalCloseUserID = true;

			_originalCloseUserID = _closeUserID;
		}

		_closeUserID = closeUserID;
	}

	public long getOriginalCloseUserID() {
		return _originalCloseUserID;
	}

	@JSON
	@Override
	public String getCloseUserName() {
		if (_closeUserName == null) {
			return "";
		}
		else {
			return _closeUserName;
		}
	}

	@Override
	public void setCloseUserName(String closeUserName) {
		_closeUserName = closeUserName;
	}

	@JSON
	@Override
	public Date getCloseDate() {
		return _closeDate;
	}

	@Override
	public void setCloseDate(Date closeDate) {
		_closeDate = closeDate;
	}

	@JSON
	@Override
	public String getCloseComment() {
		if (_closeComment == null) {
			return "";
		}
		else {
			return _closeComment;
		}
	}

	@Override
	public void setCloseComment(String closeComment) {
		_closeComment = closeComment;
	}

	@JSON
	@Override
	public int getQueryStatus() {
		return _queryStatus;
	}

	@Override
	public void setQueryStatus(int queryStatus) {
		_queryStatus = queryStatus;
	}

	@JSON
	@Override
	public String getIsReopen() {
		if (_isReopen == null) {
			return "";
		}
		else {
			return _isReopen;
		}
	}

	@Override
	public void setIsReopen(String isReopen) {
		_isReopen = isReopen;
	}

	@JSON
	@Override
	public long getReopenId() {
		return _reopenId;
	}

	@Override
	public void setReopenId(long reopenId) {
		_columnBitmask |= REOPENID_COLUMN_BITMASK;

		if (!_setOriginalReopenId) {
			_setOriginalReopenId = true;

			_originalReopenId = _reopenId;
		}

		_reopenId = reopenId;
	}

	public long getOriginalReopenId() {
		return _originalReopenId;
	}

	@JSON
	@Override
	public long getRuleId() {
		return _ruleId;
	}

	@Override
	public void setRuleId(long ruleId) {
		_columnBitmask |= RULEID_COLUMN_BITMASK;

		if (!_setOriginalRuleId) {
			_setOriginalRuleId = true;

			_originalRuleId = _ruleId;
		}

		_ruleId = ruleId;
	}

	public long getOriginalRuleId() {
		return _originalRuleId;
	}

	@JSON
	@Override
	public String getRuleInfo() {
		if (_ruleInfo == null) {
			return "";
		}
		else {
			return _ruleInfo;
		}
	}

	@Override
	public void setRuleInfo(String ruleInfo) {
		_ruleInfo = ruleInfo;
	}

	@JSON
	@Override
	public int getActiveStatus() {
		return _activeStatus;
	}

	@Override
	public void setActiveStatus(int activeStatus) {
		_activeStatus = activeStatus;
	}

	@JSON
	@Override
	public Date getInactiveDate() {
		return _inactiveDate;
	}

	@Override
	public void setInactiveDate(Date inactiveDate) {
		_inactiveDate = inactiveDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(QueryLink.class.getName()));
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), QueryLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QueryLink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, QueryLink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QueryLinkImpl queryLinkImpl = new QueryLinkImpl();

		queryLinkImpl.setUuid(getUuid());
		queryLinkImpl.setQueryId(getQueryId());
		queryLinkImpl.setGroupId(getGroupId());
		queryLinkImpl.setCompanyId(getCompanyId());
		queryLinkImpl.setProjectId(getProjectId());
		queryLinkImpl.setUserId(getUserId());
		queryLinkImpl.setUserName(getUserName());
		queryLinkImpl.setCreateDate(getCreateDate());
		queryLinkImpl.setModifiedDate(getModifiedDate());
		queryLinkImpl.setSubjectId(getSubjectId());
		queryLinkImpl.setVisitGroupId(getVisitGroupId());
		queryLinkImpl.setVisitDefinitionId(getVisitDefinitionId());
		queryLinkImpl.setVisitCRFId(getVisitCRFId());
		queryLinkImpl.setSubCRFId(getSubCRFId());
		queryLinkImpl.setInstanceId(getInstanceId());
		queryLinkImpl.setItemCode(getItemCode());
		queryLinkImpl.setSourceType(getSourceType());
		queryLinkImpl.setScope(getScope());
		queryLinkImpl.setIsTypeManual(getIsTypeManual());
		queryLinkImpl.setType(getType());
		queryLinkImpl.setOpenUserId(getOpenUserId());
		queryLinkImpl.setOpenUserName(getOpenUserName());
		queryLinkImpl.setOpenDate(getOpenDate());
		queryLinkImpl.setOpenComment(getOpenComment());
		queryLinkImpl.setAnswerUserID(getAnswerUserID());
		queryLinkImpl.setAnswerUserName(getAnswerUserName());
		queryLinkImpl.setAnswerDate(getAnswerDate());
		queryLinkImpl.setAnswerComment(getAnswerComment());
		queryLinkImpl.setCloseUserID(getCloseUserID());
		queryLinkImpl.setCloseUserName(getCloseUserName());
		queryLinkImpl.setCloseDate(getCloseDate());
		queryLinkImpl.setCloseComment(getCloseComment());
		queryLinkImpl.setQueryStatus(getQueryStatus());
		queryLinkImpl.setIsReopen(getIsReopen());
		queryLinkImpl.setReopenId(getReopenId());
		queryLinkImpl.setRuleId(getRuleId());
		queryLinkImpl.setRuleInfo(getRuleInfo());
		queryLinkImpl.setActiveStatus(getActiveStatus());
		queryLinkImpl.setInactiveDate(getInactiveDate());

		queryLinkImpl.resetOriginalValues();

		return queryLinkImpl;
	}

	@Override
	public int compareTo(QueryLink queryLink) {
		long primaryKey = queryLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof QueryLink)) {
			return false;
		}

		QueryLink queryLink = (QueryLink)object;

		long primaryKey = queryLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;
		_originalSubjectId = _subjectId;

		_setOriginalSubjectId = false;

		_originalVisitGroupId = _visitGroupId;

		_setOriginalVisitGroupId = false;

		_originalVisitDefinitionId = _visitDefinitionId;

		_setOriginalVisitDefinitionId = false;

		_originalVisitCRFId = _visitCRFId;

		_setOriginalVisitCRFId = false;

		_originalSubCRFId = _subCRFId;

		_setOriginalSubCRFId = false;

		_originalInstanceId = _instanceId;

		_setOriginalInstanceId = false;

		_originalItemCode = _itemCode;

		_setOriginalItemCode = false;

		_originalOpenUserId = _openUserId;

		_setOriginalOpenUserId = false;

		_originalAnswerUserID = _answerUserID;

		_setOriginalAnswerUserID = false;

		_originalCloseUserID = _closeUserID;

		_setOriginalCloseUserID = false;

		_originalReopenId = _reopenId;

		_setOriginalReopenId = false;

		_originalRuleId = _ruleId;

		_setOriginalRuleId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<QueryLink> toCacheModel() {
		QueryLinkCacheModel queryLinkCacheModel = new QueryLinkCacheModel();

		queryLinkCacheModel.uuid = getUuid();

		String uuid = queryLinkCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			queryLinkCacheModel.uuid = null;
		}

		queryLinkCacheModel.queryId = getQueryId();

		queryLinkCacheModel.groupId = getGroupId();

		queryLinkCacheModel.companyId = getCompanyId();

		queryLinkCacheModel.projectId = getProjectId();

		queryLinkCacheModel.userId = getUserId();

		queryLinkCacheModel.userName = getUserName();

		String userName = queryLinkCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			queryLinkCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			queryLinkCacheModel.createDate = createDate.getTime();
		}
		else {
			queryLinkCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			queryLinkCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			queryLinkCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		queryLinkCacheModel.subjectId = getSubjectId();

		queryLinkCacheModel.visitGroupId = getVisitGroupId();

		queryLinkCacheModel.visitDefinitionId = getVisitDefinitionId();

		queryLinkCacheModel.visitCRFId = getVisitCRFId();

		queryLinkCacheModel.subCRFId = getSubCRFId();

		queryLinkCacheModel.instanceId = getInstanceId();

		queryLinkCacheModel.itemCode = getItemCode();

		queryLinkCacheModel.sourceType = getSourceType();

		String sourceType = queryLinkCacheModel.sourceType;

		if ((sourceType != null) && (sourceType.length() == 0)) {
			queryLinkCacheModel.sourceType = null;
		}

		queryLinkCacheModel.scope = getScope();

		String scope = queryLinkCacheModel.scope;

		if ((scope != null) && (scope.length() == 0)) {
			queryLinkCacheModel.scope = null;
		}

		queryLinkCacheModel.isTypeManual = getIsTypeManual();

		String isTypeManual = queryLinkCacheModel.isTypeManual;

		if ((isTypeManual != null) && (isTypeManual.length() == 0)) {
			queryLinkCacheModel.isTypeManual = null;
		}

		queryLinkCacheModel.type = getType();

		String type = queryLinkCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			queryLinkCacheModel.type = null;
		}

		queryLinkCacheModel.openUserId = getOpenUserId();

		queryLinkCacheModel.openUserName = getOpenUserName();

		String openUserName = queryLinkCacheModel.openUserName;

		if ((openUserName != null) && (openUserName.length() == 0)) {
			queryLinkCacheModel.openUserName = null;
		}

		Date openDate = getOpenDate();

		if (openDate != null) {
			queryLinkCacheModel.openDate = openDate.getTime();
		}
		else {
			queryLinkCacheModel.openDate = Long.MIN_VALUE;
		}

		queryLinkCacheModel.openComment = getOpenComment();

		String openComment = queryLinkCacheModel.openComment;

		if ((openComment != null) && (openComment.length() == 0)) {
			queryLinkCacheModel.openComment = null;
		}

		queryLinkCacheModel.answerUserID = getAnswerUserID();

		queryLinkCacheModel.answerUserName = getAnswerUserName();

		String answerUserName = queryLinkCacheModel.answerUserName;

		if ((answerUserName != null) && (answerUserName.length() == 0)) {
			queryLinkCacheModel.answerUserName = null;
		}

		Date answerDate = getAnswerDate();

		if (answerDate != null) {
			queryLinkCacheModel.answerDate = answerDate.getTime();
		}
		else {
			queryLinkCacheModel.answerDate = Long.MIN_VALUE;
		}

		queryLinkCacheModel.answerComment = getAnswerComment();

		String answerComment = queryLinkCacheModel.answerComment;

		if ((answerComment != null) && (answerComment.length() == 0)) {
			queryLinkCacheModel.answerComment = null;
		}

		queryLinkCacheModel.closeUserID = getCloseUserID();

		queryLinkCacheModel.closeUserName = getCloseUserName();

		String closeUserName = queryLinkCacheModel.closeUserName;

		if ((closeUserName != null) && (closeUserName.length() == 0)) {
			queryLinkCacheModel.closeUserName = null;
		}

		Date closeDate = getCloseDate();

		if (closeDate != null) {
			queryLinkCacheModel.closeDate = closeDate.getTime();
		}
		else {
			queryLinkCacheModel.closeDate = Long.MIN_VALUE;
		}

		queryLinkCacheModel.closeComment = getCloseComment();

		String closeComment = queryLinkCacheModel.closeComment;

		if ((closeComment != null) && (closeComment.length() == 0)) {
			queryLinkCacheModel.closeComment = null;
		}

		queryLinkCacheModel.queryStatus = getQueryStatus();

		queryLinkCacheModel.isReopen = getIsReopen();

		String isReopen = queryLinkCacheModel.isReopen;

		if ((isReopen != null) && (isReopen.length() == 0)) {
			queryLinkCacheModel.isReopen = null;
		}

		queryLinkCacheModel.reopenId = getReopenId();

		queryLinkCacheModel.ruleId = getRuleId();

		queryLinkCacheModel.ruleInfo = getRuleInfo();

		String ruleInfo = queryLinkCacheModel.ruleInfo;

		if ((ruleInfo != null) && (ruleInfo.length() == 0)) {
			queryLinkCacheModel.ruleInfo = null;
		}

		queryLinkCacheModel.activeStatus = getActiveStatus();

		Date inactiveDate = getInactiveDate();

		if (inactiveDate != null) {
			queryLinkCacheModel.inactiveDate = inactiveDate.getTime();
		}
		else {
			queryLinkCacheModel.inactiveDate = Long.MIN_VALUE;
		}

		return queryLinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<QueryLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<QueryLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QueryLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((QueryLink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<QueryLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<QueryLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QueryLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((QueryLink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, QueryLink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					QueryLink.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _queryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _subjectId;
	private long _originalSubjectId;
	private boolean _setOriginalSubjectId;
	private long _visitGroupId;
	private long _originalVisitGroupId;
	private boolean _setOriginalVisitGroupId;
	private long _visitDefinitionId;
	private long _originalVisitDefinitionId;
	private boolean _setOriginalVisitDefinitionId;
	private long _visitCRFId;
	private long _originalVisitCRFId;
	private boolean _setOriginalVisitCRFId;
	private long _subCRFId;
	private long _originalSubCRFId;
	private boolean _setOriginalSubCRFId;
	private long _instanceId;
	private long _originalInstanceId;
	private boolean _setOriginalInstanceId;
	private long _itemCode;
	private long _originalItemCode;
	private boolean _setOriginalItemCode;
	private String _sourceType;
	private String _scope;
	private String _isTypeManual;
	private String _type;
	private long _openUserId;
	private long _originalOpenUserId;
	private boolean _setOriginalOpenUserId;
	private String _openUserName;
	private Date _openDate;
	private String _openComment;
	private long _answerUserID;
	private long _originalAnswerUserID;
	private boolean _setOriginalAnswerUserID;
	private String _answerUserName;
	private Date _answerDate;
	private String _answerComment;
	private long _closeUserID;
	private long _originalCloseUserID;
	private boolean _setOriginalCloseUserID;
	private String _closeUserName;
	private Date _closeDate;
	private String _closeComment;
	private int _queryStatus;
	private String _isReopen;
	private long _reopenId;
	private long _originalReopenId;
	private boolean _setOriginalReopenId;
	private long _ruleId;
	private long _originalRuleId;
	private boolean _setOriginalRuleId;
	private String _ruleInfo;
	private int _activeStatus;
	private Date _inactiveDate;
	private long _columnBitmask;
	private QueryLink _escapedModel;

}