/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.Randomization;
import com.dhsoft.edc.backend.model.RandomizationModel;
import com.dhsoft.edc.backend.model.RandomizationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Randomization service. Represents a row in the &quot;EDC_Randomization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RandomizationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RandomizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RandomizationImpl
 * @generated
 */
@JSON(strict = true)
public class RandomizationModelImpl
	extends BaseModelImpl<Randomization> implements RandomizationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a randomization model instance should use the <code>Randomization</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_Randomization";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"randomizationId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"randomNo", Types.VARCHAR},
		{"useStatus", Types.INTEGER}, {"sourceType", Types.INTEGER},
		{"criteria", Types.VARCHAR}, {"expGroupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("randomizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("randomNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("useStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sourceType", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("criteria", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("expGroupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_Randomization (uuid_ VARCHAR(75) null,randomizationId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,randomNo VARCHAR(75) null,useStatus INTEGER,sourceType INTEGER,criteria VARCHAR(75) null,expGroupId LONG)";

	public static final String TABLE_SQL_DROP = "drop table EDC_Randomization";

	public static final String ORDER_BY_JPQL =
		" ORDER BY randomization.randomizationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_Randomization.randomizationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long EXPGROUPID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long PROJECTID_COLUMN_BITMASK = 8L;

	public static final long USERID_COLUMN_BITMASK = 16L;

	public static final long UUID_COLUMN_BITMASK = 32L;

	public static final long RANDOMIZATIONID_COLUMN_BITMASK = 64L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Randomization toModel(RandomizationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Randomization model = new RandomizationImpl();

		model.setUuid(soapModel.getUuid());
		model.setRandomizationId(soapModel.getRandomizationId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setRandomNo(soapModel.getRandomNo());
		model.setUseStatus(soapModel.getUseStatus());
		model.setSourceType(soapModel.getSourceType());
		model.setCriteria(soapModel.getCriteria());
		model.setExpGroupId(soapModel.getExpGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Randomization> toModels(RandomizationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Randomization> models = new ArrayList<Randomization>(
			soapModels.length);

		for (RandomizationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public RandomizationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _randomizationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRandomizationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _randomizationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Randomization.class;
	}

	@Override
	public String getModelClassName() {
		return Randomization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Randomization, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Randomization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Randomization, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Randomization)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Randomization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Randomization, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Randomization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Randomization, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Randomization, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Randomization, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Randomization, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Randomization, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Randomization, Object>>();
		Map<String, BiConsumer<Randomization, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Randomization, ?>>();

		attributeGetterFunctions.put("uuid", Randomization::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Randomization, String>)Randomization::setUuid);
		attributeGetterFunctions.put(
			"randomizationId", Randomization::getRandomizationId);
		attributeSetterBiConsumers.put(
			"randomizationId",
			(BiConsumer<Randomization, Long>)Randomization::setRandomizationId);
		attributeGetterFunctions.put("groupId", Randomization::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<Randomization, Long>)Randomization::setGroupId);
		attributeGetterFunctions.put("companyId", Randomization::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Randomization, Long>)Randomization::setCompanyId);
		attributeGetterFunctions.put("projectId", Randomization::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<Randomization, Long>)Randomization::setProjectId);
		attributeGetterFunctions.put("userId", Randomization::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<Randomization, Long>)Randomization::setUserId);
		attributeGetterFunctions.put("userName", Randomization::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Randomization, String>)Randomization::setUserName);
		attributeGetterFunctions.put(
			"createDate", Randomization::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Randomization, Date>)Randomization::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Randomization::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Randomization, Date>)Randomization::setModifiedDate);
		attributeGetterFunctions.put("status", Randomization::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<Randomization, Integer>)Randomization::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Randomization::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Randomization, Long>)Randomization::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Randomization::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Randomization, String>)
				Randomization::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", Randomization::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<Randomization, Date>)Randomization::setStatusDate);
		attributeGetterFunctions.put("randomNo", Randomization::getRandomNo);
		attributeSetterBiConsumers.put(
			"randomNo",
			(BiConsumer<Randomization, String>)Randomization::setRandomNo);
		attributeGetterFunctions.put("useStatus", Randomization::getUseStatus);
		attributeSetterBiConsumers.put(
			"useStatus",
			(BiConsumer<Randomization, Integer>)Randomization::setUseStatus);
		attributeGetterFunctions.put(
			"sourceType", Randomization::getSourceType);
		attributeSetterBiConsumers.put(
			"sourceType",
			(BiConsumer<Randomization, Integer>)Randomization::setSourceType);
		attributeGetterFunctions.put("criteria", Randomization::getCriteria);
		attributeSetterBiConsumers.put(
			"criteria",
			(BiConsumer<Randomization, String>)Randomization::setCriteria);
		attributeGetterFunctions.put(
			"expGroupId", Randomization::getExpGroupId);
		attributeSetterBiConsumers.put(
			"expGroupId",
			(BiConsumer<Randomization, Long>)Randomization::setExpGroupId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getRandomizationId() {
		return _randomizationId;
	}

	@Override
	public void setRandomizationId(long randomizationId) {
		_randomizationId = randomizationId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getRandomNo() {
		if (_randomNo == null) {
			return "";
		}
		else {
			return _randomNo;
		}
	}

	@Override
	public void setRandomNo(String randomNo) {
		_randomNo = randomNo;
	}

	@JSON
	@Override
	public int getUseStatus() {
		return _useStatus;
	}

	@Override
	public void setUseStatus(int useStatus) {
		_useStatus = useStatus;
	}

	@JSON
	@Override
	public int getSourceType() {
		return _sourceType;
	}

	@Override
	public void setSourceType(int sourceType) {
		_sourceType = sourceType;
	}

	@JSON
	@Override
	public String getCriteria() {
		if (_criteria == null) {
			return "";
		}
		else {
			return _criteria;
		}
	}

	@Override
	public void setCriteria(String criteria) {
		_criteria = criteria;
	}

	@JSON
	@Override
	public long getExpGroupId() {
		return _expGroupId;
	}

	@Override
	public void setExpGroupId(long expGroupId) {
		_columnBitmask |= EXPGROUPID_COLUMN_BITMASK;

		if (!_setOriginalExpGroupId) {
			_setOriginalExpGroupId = true;

			_originalExpGroupId = _expGroupId;
		}

		_expGroupId = expGroupId;
	}

	public long getOriginalExpGroupId() {
		return _originalExpGroupId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Randomization.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Randomization.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Randomization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Randomization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RandomizationImpl randomizationImpl = new RandomizationImpl();

		randomizationImpl.setUuid(getUuid());
		randomizationImpl.setRandomizationId(getRandomizationId());
		randomizationImpl.setGroupId(getGroupId());
		randomizationImpl.setCompanyId(getCompanyId());
		randomizationImpl.setProjectId(getProjectId());
		randomizationImpl.setUserId(getUserId());
		randomizationImpl.setUserName(getUserName());
		randomizationImpl.setCreateDate(getCreateDate());
		randomizationImpl.setModifiedDate(getModifiedDate());
		randomizationImpl.setStatus(getStatus());
		randomizationImpl.setStatusByUserId(getStatusByUserId());
		randomizationImpl.setStatusByUserName(getStatusByUserName());
		randomizationImpl.setStatusDate(getStatusDate());
		randomizationImpl.setRandomNo(getRandomNo());
		randomizationImpl.setUseStatus(getUseStatus());
		randomizationImpl.setSourceType(getSourceType());
		randomizationImpl.setCriteria(getCriteria());
		randomizationImpl.setExpGroupId(getExpGroupId());

		randomizationImpl.resetOriginalValues();

		return randomizationImpl;
	}

	@Override
	public int compareTo(Randomization randomization) {
		long primaryKey = randomization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Randomization)) {
			return false;
		}

		Randomization randomization = (Randomization)object;

		long primaryKey = randomization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;

		_originalExpGroupId = _expGroupId;

		_setOriginalExpGroupId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Randomization> toCacheModel() {
		RandomizationCacheModel randomizationCacheModel =
			new RandomizationCacheModel();

		randomizationCacheModel.uuid = getUuid();

		String uuid = randomizationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			randomizationCacheModel.uuid = null;
		}

		randomizationCacheModel.randomizationId = getRandomizationId();

		randomizationCacheModel.groupId = getGroupId();

		randomizationCacheModel.companyId = getCompanyId();

		randomizationCacheModel.projectId = getProjectId();

		randomizationCacheModel.userId = getUserId();

		randomizationCacheModel.userName = getUserName();

		String userName = randomizationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			randomizationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			randomizationCacheModel.createDate = createDate.getTime();
		}
		else {
			randomizationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			randomizationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			randomizationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		randomizationCacheModel.status = getStatus();

		randomizationCacheModel.statusByUserId = getStatusByUserId();

		randomizationCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = randomizationCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			randomizationCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			randomizationCacheModel.statusDate = statusDate.getTime();
		}
		else {
			randomizationCacheModel.statusDate = Long.MIN_VALUE;
		}

		randomizationCacheModel.randomNo = getRandomNo();

		String randomNo = randomizationCacheModel.randomNo;

		if ((randomNo != null) && (randomNo.length() == 0)) {
			randomizationCacheModel.randomNo = null;
		}

		randomizationCacheModel.useStatus = getUseStatus();

		randomizationCacheModel.sourceType = getSourceType();

		randomizationCacheModel.criteria = getCriteria();

		String criteria = randomizationCacheModel.criteria;

		if ((criteria != null) && (criteria.length() == 0)) {
			randomizationCacheModel.criteria = null;
		}

		randomizationCacheModel.expGroupId = getExpGroupId();

		return randomizationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Randomization, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Randomization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Randomization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Randomization)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Randomization, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Randomization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Randomization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Randomization)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Randomization>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Randomization.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _randomizationId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _randomNo;
	private int _useStatus;
	private int _sourceType;
	private String _criteria;
	private long _expGroupId;
	private long _originalExpGroupId;
	private boolean _setOriginalExpGroupId;
	private long _columnBitmask;
	private Randomization _escapedModel;

}