/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.Subject;
import com.dhsoft.edc.backend.model.SubjectModel;
import com.dhsoft.edc.backend.model.SubjectSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Subject service. Represents a row in the &quot;EDC_Subject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SubjectModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubjectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubjectImpl
 * @generated
 */
@JSON(strict = true)
public class SubjectModelImpl
	extends BaseModelImpl<Subject> implements SubjectModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subject model instance should use the <code>Subject</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_Subject";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"subjectId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"institutionId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"serialId", Types.VARCHAR}, {"randomNo", Types.VARCHAR},
		{"name", Types.VARCHAR}, {"subjectStatus", Types.INTEGER},
		{"subjectStatusApplyDate", Types.TIMESTAMP},
		{"consentAgreeDate", Types.TIMESTAMP}, {"expGroupId", Types.BIGINT},
		{"applyDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("institutionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("serialId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("randomNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subjectStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("subjectStatusApplyDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("consentAgreeDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("applyDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_Subject (uuid_ VARCHAR(75) null,subjectId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,institutionId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,serialId VARCHAR(75) null,randomNo VARCHAR(75) null,name VARCHAR(75) null,subjectStatus INTEGER,subjectStatusApplyDate DATE null,consentAgreeDate DATE null,expGroupId LONG,applyDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table EDC_Subject";

	public static final String ORDER_BY_JPQL =
		" ORDER BY subject.subjectId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_Subject.subjectId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long EXPGROUPID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long INSTITUTIONID_COLUMN_BITMASK = 8L;

	public static final long PROJECTID_COLUMN_BITMASK = 16L;

	public static final long USERID_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static final long SUBJECTID_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Subject toModel(SubjectSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Subject model = new SubjectImpl();

		model.setUuid(soapModel.getUuid());
		model.setSubjectId(soapModel.getSubjectId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setInstitutionId(soapModel.getInstitutionId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setSerialId(soapModel.getSerialId());
		model.setRandomNo(soapModel.getRandomNo());
		model.setName(soapModel.getName());
		model.setSubjectStatus(soapModel.getSubjectStatus());
		model.setSubjectStatusApplyDate(soapModel.getSubjectStatusApplyDate());
		model.setConsentAgreeDate(soapModel.getConsentAgreeDate());
		model.setExpGroupId(soapModel.getExpGroupId());
		model.setApplyDate(soapModel.getApplyDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Subject> toModels(SubjectSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Subject> models = new ArrayList<Subject>(soapModels.length);

		for (SubjectSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SubjectModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _subjectId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubjectId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subjectId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Subject.class;
	}

	@Override
	public String getModelClassName() {
		return Subject.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Subject, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Subject, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Subject, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Subject)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Subject, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Subject, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Subject)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Subject, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Subject, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Subject, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Subject, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Subject, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Subject, Object>>();
		Map<String, BiConsumer<Subject, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Subject, ?>>();

		attributeGetterFunctions.put("uuid", Subject::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Subject, String>)Subject::setUuid);
		attributeGetterFunctions.put("subjectId", Subject::getSubjectId);
		attributeSetterBiConsumers.put(
			"subjectId", (BiConsumer<Subject, Long>)Subject::setSubjectId);
		attributeGetterFunctions.put("groupId", Subject::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Subject, Long>)Subject::setGroupId);
		attributeGetterFunctions.put("companyId", Subject::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Subject, Long>)Subject::setCompanyId);
		attributeGetterFunctions.put("projectId", Subject::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId", (BiConsumer<Subject, Long>)Subject::setProjectId);
		attributeGetterFunctions.put(
			"institutionId", Subject::getInstitutionId);
		attributeSetterBiConsumers.put(
			"institutionId",
			(BiConsumer<Subject, Long>)Subject::setInstitutionId);
		attributeGetterFunctions.put("userId", Subject::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Subject, Long>)Subject::setUserId);
		attributeGetterFunctions.put("userName", Subject::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Subject, String>)Subject::setUserName);
		attributeGetterFunctions.put("createDate", Subject::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Subject, Date>)Subject::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Subject::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Subject, Date>)Subject::setModifiedDate);
		attributeGetterFunctions.put("status", Subject::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Subject, Integer>)Subject::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Subject::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Subject, Long>)Subject::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Subject::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Subject, String>)Subject::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Subject::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Subject, Date>)Subject::setStatusDate);
		attributeGetterFunctions.put("serialId", Subject::getSerialId);
		attributeSetterBiConsumers.put(
			"serialId", (BiConsumer<Subject, String>)Subject::setSerialId);
		attributeGetterFunctions.put("randomNo", Subject::getRandomNo);
		attributeSetterBiConsumers.put(
			"randomNo", (BiConsumer<Subject, String>)Subject::setRandomNo);
		attributeGetterFunctions.put("name", Subject::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Subject, String>)Subject::setName);
		attributeGetterFunctions.put(
			"subjectStatus", Subject::getSubjectStatus);
		attributeSetterBiConsumers.put(
			"subjectStatus",
			(BiConsumer<Subject, Integer>)Subject::setSubjectStatus);
		attributeGetterFunctions.put(
			"subjectStatusApplyDate", Subject::getSubjectStatusApplyDate);
		attributeSetterBiConsumers.put(
			"subjectStatusApplyDate",
			(BiConsumer<Subject, Date>)Subject::setSubjectStatusApplyDate);
		attributeGetterFunctions.put(
			"consentAgreeDate", Subject::getConsentAgreeDate);
		attributeSetterBiConsumers.put(
			"consentAgreeDate",
			(BiConsumer<Subject, Date>)Subject::setConsentAgreeDate);
		attributeGetterFunctions.put("expGroupId", Subject::getExpGroupId);
		attributeSetterBiConsumers.put(
			"expGroupId", (BiConsumer<Subject, Long>)Subject::setExpGroupId);
		attributeGetterFunctions.put("applyDate", Subject::getApplyDate);
		attributeSetterBiConsumers.put(
			"applyDate", (BiConsumer<Subject, Date>)Subject::setApplyDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getSubjectId() {
		return _subjectId;
	}

	@Override
	public void setSubjectId(long subjectId) {
		_subjectId = subjectId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getSerialId() {
		if (_serialId == null) {
			return "";
		}
		else {
			return _serialId;
		}
	}

	@Override
	public void setSerialId(String serialId) {
		_serialId = serialId;
	}

	@JSON
	@Override
	public String getRandomNo() {
		if (_randomNo == null) {
			return "";
		}
		else {
			return _randomNo;
		}
	}

	@Override
	public void setRandomNo(String randomNo) {
		_randomNo = randomNo;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public int getSubjectStatus() {
		return _subjectStatus;
	}

	@Override
	public void setSubjectStatus(int subjectStatus) {
		_subjectStatus = subjectStatus;
	}

	@JSON
	@Override
	public Date getSubjectStatusApplyDate() {
		return _subjectStatusApplyDate;
	}

	@Override
	public void setSubjectStatusApplyDate(Date subjectStatusApplyDate) {
		_subjectStatusApplyDate = subjectStatusApplyDate;
	}

	@JSON
	@Override
	public Date getConsentAgreeDate() {
		return _consentAgreeDate;
	}

	@Override
	public void setConsentAgreeDate(Date consentAgreeDate) {
		_consentAgreeDate = consentAgreeDate;
	}

	@JSON
	@Override
	public long getExpGroupId() {
		return _expGroupId;
	}

	@Override
	public void setExpGroupId(long expGroupId) {
		_columnBitmask |= EXPGROUPID_COLUMN_BITMASK;

		if (!_setOriginalExpGroupId) {
			_setOriginalExpGroupId = true;

			_originalExpGroupId = _expGroupId;
		}

		_expGroupId = expGroupId;
	}

	public long getOriginalExpGroupId() {
		return _originalExpGroupId;
	}

	@JSON
	@Override
	public Date getApplyDate() {
		return _applyDate;
	}

	@Override
	public void setApplyDate(Date applyDate) {
		_applyDate = applyDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Subject.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Subject.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Subject toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Subject>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubjectImpl subjectImpl = new SubjectImpl();

		subjectImpl.setUuid(getUuid());
		subjectImpl.setSubjectId(getSubjectId());
		subjectImpl.setGroupId(getGroupId());
		subjectImpl.setCompanyId(getCompanyId());
		subjectImpl.setProjectId(getProjectId());
		subjectImpl.setInstitutionId(getInstitutionId());
		subjectImpl.setUserId(getUserId());
		subjectImpl.setUserName(getUserName());
		subjectImpl.setCreateDate(getCreateDate());
		subjectImpl.setModifiedDate(getModifiedDate());
		subjectImpl.setStatus(getStatus());
		subjectImpl.setStatusByUserId(getStatusByUserId());
		subjectImpl.setStatusByUserName(getStatusByUserName());
		subjectImpl.setStatusDate(getStatusDate());
		subjectImpl.setSerialId(getSerialId());
		subjectImpl.setRandomNo(getRandomNo());
		subjectImpl.setName(getName());
		subjectImpl.setSubjectStatus(getSubjectStatus());
		subjectImpl.setSubjectStatusApplyDate(getSubjectStatusApplyDate());
		subjectImpl.setConsentAgreeDate(getConsentAgreeDate());
		subjectImpl.setExpGroupId(getExpGroupId());
		subjectImpl.setApplyDate(getApplyDate());

		subjectImpl.resetOriginalValues();

		return subjectImpl;
	}

	@Override
	public int compareTo(Subject subject) {
		long primaryKey = subject.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Subject)) {
			return false;
		}

		Subject subject = (Subject)object;

		long primaryKey = subject.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalInstitutionId = _institutionId;

		_setOriginalInstitutionId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;

		_originalExpGroupId = _expGroupId;

		_setOriginalExpGroupId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Subject> toCacheModel() {
		SubjectCacheModel subjectCacheModel = new SubjectCacheModel();

		subjectCacheModel.uuid = getUuid();

		String uuid = subjectCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			subjectCacheModel.uuid = null;
		}

		subjectCacheModel.subjectId = getSubjectId();

		subjectCacheModel.groupId = getGroupId();

		subjectCacheModel.companyId = getCompanyId();

		subjectCacheModel.projectId = getProjectId();

		subjectCacheModel.institutionId = getInstitutionId();

		subjectCacheModel.userId = getUserId();

		subjectCacheModel.userName = getUserName();

		String userName = subjectCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			subjectCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			subjectCacheModel.createDate = createDate.getTime();
		}
		else {
			subjectCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			subjectCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			subjectCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		subjectCacheModel.status = getStatus();

		subjectCacheModel.statusByUserId = getStatusByUserId();

		subjectCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = subjectCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			subjectCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			subjectCacheModel.statusDate = statusDate.getTime();
		}
		else {
			subjectCacheModel.statusDate = Long.MIN_VALUE;
		}

		subjectCacheModel.serialId = getSerialId();

		String serialId = subjectCacheModel.serialId;

		if ((serialId != null) && (serialId.length() == 0)) {
			subjectCacheModel.serialId = null;
		}

		subjectCacheModel.randomNo = getRandomNo();

		String randomNo = subjectCacheModel.randomNo;

		if ((randomNo != null) && (randomNo.length() == 0)) {
			subjectCacheModel.randomNo = null;
		}

		subjectCacheModel.name = getName();

		String name = subjectCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			subjectCacheModel.name = null;
		}

		subjectCacheModel.subjectStatus = getSubjectStatus();

		Date subjectStatusApplyDate = getSubjectStatusApplyDate();

		if (subjectStatusApplyDate != null) {
			subjectCacheModel.subjectStatusApplyDate =
				subjectStatusApplyDate.getTime();
		}
		else {
			subjectCacheModel.subjectStatusApplyDate = Long.MIN_VALUE;
		}

		Date consentAgreeDate = getConsentAgreeDate();

		if (consentAgreeDate != null) {
			subjectCacheModel.consentAgreeDate = consentAgreeDate.getTime();
		}
		else {
			subjectCacheModel.consentAgreeDate = Long.MIN_VALUE;
		}

		subjectCacheModel.expGroupId = getExpGroupId();

		Date applyDate = getApplyDate();

		if (applyDate != null) {
			subjectCacheModel.applyDate = applyDate.getTime();
		}
		else {
			subjectCacheModel.applyDate = Long.MIN_VALUE;
		}

		return subjectCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Subject, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Subject, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Subject, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Subject)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Subject, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Subject, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Subject, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Subject)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Subject>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Subject.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _subjectId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _serialId;
	private String _randomNo;
	private String _name;
	private int _subjectStatus;
	private Date _subjectStatusApplyDate;
	private Date _consentAgreeDate;
	private long _expGroupId;
	private long _originalExpGroupId;
	private boolean _setOriginalExpGroupId;
	private Date _applyDate;
	private long _columnBitmask;
	private Subject _escapedModel;

}