/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.SubjectVisitDefinition;
import com.dhsoft.edc.backend.model.SubjectVisitDefinitionModel;
import com.dhsoft.edc.backend.model.SubjectVisitDefinitionSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SubjectVisitDefinition service. Represents a row in the &quot;EDC_SubjectVisitDefinition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SubjectVisitDefinitionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubjectVisitDefinitionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubjectVisitDefinitionImpl
 * @generated
 */
@JSON(strict = true)
public class SubjectVisitDefinitionModelImpl
	extends BaseModelImpl<SubjectVisitDefinition>
	implements SubjectVisitDefinitionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subject visit definition model instance should use the <code>SubjectVisitDefinition</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_SubjectVisitDefinition";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"subjectVisitDefinitionId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"visitGroupId", Types.BIGINT},
		{"subjectId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"parentCode", Types.VARCHAR},
		{"visitDefinitionCode", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"order_", Types.VARCHAR}, {"extCode", Types.VARCHAR},
		{"anchorType", Types.VARCHAR}, {"offset", Types.INTEGER},
		{"windowMinus", Types.INTEGER}, {"windowPlus", Types.INTEGER},
		{"type_", Types.INTEGER}, {"repeatCount", Types.INTEGER},
		{"visitCRFId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subjectVisitDefinitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("visitGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("visitDefinitionCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("order_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("extCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("anchorType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("offset", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("windowMinus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("windowPlus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("repeatCount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("visitCRFId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_SubjectVisitDefinition (uuid_ VARCHAR(75) null,subjectVisitDefinitionId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,visitGroupId LONG,subjectId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,parentCode VARCHAR(75) null,visitDefinitionCode VARCHAR(75) null,name VARCHAR(75) null,order_ VARCHAR(75) null,extCode VARCHAR(75) null,anchorType VARCHAR(75) null,offset INTEGER,windowMinus INTEGER,windowPlus INTEGER,type_ INTEGER,repeatCount INTEGER,visitCRFId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table EDC_SubjectVisitDefinition";

	public static final String ORDER_BY_JPQL =
		" ORDER BY subjectVisitDefinition.subjectVisitDefinitionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_SubjectVisitDefinition.subjectVisitDefinitionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long PROJECTID_COLUMN_BITMASK = 4L;

	public static final long SUBJECTID_COLUMN_BITMASK = 8L;

	public static final long USERID_COLUMN_BITMASK = 16L;

	public static final long UUID_COLUMN_BITMASK = 32L;

	public static final long VISITCRFID_COLUMN_BITMASK = 64L;

	public static final long VISITGROUPID_COLUMN_BITMASK = 128L;

	public static final long SUBJECTVISITDEFINITIONID_COLUMN_BITMASK = 256L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SubjectVisitDefinition toModel(
		SubjectVisitDefinitionSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		SubjectVisitDefinition model = new SubjectVisitDefinitionImpl();

		model.setUuid(soapModel.getUuid());
		model.setSubjectVisitDefinitionId(
			soapModel.getSubjectVisitDefinitionId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setVisitGroupId(soapModel.getVisitGroupId());
		model.setSubjectId(soapModel.getSubjectId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setParentCode(soapModel.getParentCode());
		model.setVisitDefinitionCode(soapModel.getVisitDefinitionCode());
		model.setName(soapModel.getName());
		model.setOrder(soapModel.getOrder());
		model.setExtCode(soapModel.getExtCode());
		model.setAnchorType(soapModel.getAnchorType());
		model.setOffset(soapModel.getOffset());
		model.setWindowMinus(soapModel.getWindowMinus());
		model.setWindowPlus(soapModel.getWindowPlus());
		model.setType(soapModel.getType());
		model.setRepeatCount(soapModel.getRepeatCount());
		model.setVisitCRFId(soapModel.getVisitCRFId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SubjectVisitDefinition> toModels(
		SubjectVisitDefinitionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SubjectVisitDefinition> models =
			new ArrayList<SubjectVisitDefinition>(soapModels.length);

		for (SubjectVisitDefinitionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SubjectVisitDefinitionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _subjectVisitDefinitionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubjectVisitDefinitionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subjectVisitDefinitionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SubjectVisitDefinition.class;
	}

	@Override
	public String getModelClassName() {
		return SubjectVisitDefinition.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SubjectVisitDefinition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SubjectVisitDefinition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubjectVisitDefinition, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SubjectVisitDefinition)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SubjectVisitDefinition, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SubjectVisitDefinition, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SubjectVisitDefinition)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SubjectVisitDefinition, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SubjectVisitDefinition, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SubjectVisitDefinition, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SubjectVisitDefinition, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SubjectVisitDefinition, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SubjectVisitDefinition, Object>>();
		Map<String, BiConsumer<SubjectVisitDefinition, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<SubjectVisitDefinition, ?>>();

		attributeGetterFunctions.put("uuid", SubjectVisitDefinition::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<SubjectVisitDefinition, String>)
				SubjectVisitDefinition::setUuid);
		attributeGetterFunctions.put(
			"subjectVisitDefinitionId",
			SubjectVisitDefinition::getSubjectVisitDefinitionId);
		attributeSetterBiConsumers.put(
			"subjectVisitDefinitionId",
			(BiConsumer<SubjectVisitDefinition, Long>)
				SubjectVisitDefinition::setSubjectVisitDefinitionId);
		attributeGetterFunctions.put(
			"groupId", SubjectVisitDefinition::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SubjectVisitDefinition, Long>)
				SubjectVisitDefinition::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SubjectVisitDefinition::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SubjectVisitDefinition, Long>)
				SubjectVisitDefinition::setCompanyId);
		attributeGetterFunctions.put(
			"projectId", SubjectVisitDefinition::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<SubjectVisitDefinition, Long>)
				SubjectVisitDefinition::setProjectId);
		attributeGetterFunctions.put(
			"visitGroupId", SubjectVisitDefinition::getVisitGroupId);
		attributeSetterBiConsumers.put(
			"visitGroupId",
			(BiConsumer<SubjectVisitDefinition, Long>)
				SubjectVisitDefinition::setVisitGroupId);
		attributeGetterFunctions.put(
			"subjectId", SubjectVisitDefinition::getSubjectId);
		attributeSetterBiConsumers.put(
			"subjectId",
			(BiConsumer<SubjectVisitDefinition, Long>)
				SubjectVisitDefinition::setSubjectId);
		attributeGetterFunctions.put(
			"userId", SubjectVisitDefinition::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SubjectVisitDefinition, Long>)
				SubjectVisitDefinition::setUserId);
		attributeGetterFunctions.put(
			"userName", SubjectVisitDefinition::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SubjectVisitDefinition, String>)
				SubjectVisitDefinition::setUserName);
		attributeGetterFunctions.put(
			"createDate", SubjectVisitDefinition::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SubjectVisitDefinition, Date>)
				SubjectVisitDefinition::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SubjectVisitDefinition::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SubjectVisitDefinition, Date>)
				SubjectVisitDefinition::setModifiedDate);
		attributeGetterFunctions.put(
			"status", SubjectVisitDefinition::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<SubjectVisitDefinition, Integer>)
				SubjectVisitDefinition::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", SubjectVisitDefinition::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<SubjectVisitDefinition, Long>)
				SubjectVisitDefinition::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", SubjectVisitDefinition::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<SubjectVisitDefinition, String>)
				SubjectVisitDefinition::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", SubjectVisitDefinition::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<SubjectVisitDefinition, Date>)
				SubjectVisitDefinition::setStatusDate);
		attributeGetterFunctions.put(
			"parentCode", SubjectVisitDefinition::getParentCode);
		attributeSetterBiConsumers.put(
			"parentCode",
			(BiConsumer<SubjectVisitDefinition, String>)
				SubjectVisitDefinition::setParentCode);
		attributeGetterFunctions.put(
			"visitDefinitionCode",
			SubjectVisitDefinition::getVisitDefinitionCode);
		attributeSetterBiConsumers.put(
			"visitDefinitionCode",
			(BiConsumer<SubjectVisitDefinition, String>)
				SubjectVisitDefinition::setVisitDefinitionCode);
		attributeGetterFunctions.put("name", SubjectVisitDefinition::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<SubjectVisitDefinition, String>)
				SubjectVisitDefinition::setName);
		attributeGetterFunctions.put("order", SubjectVisitDefinition::getOrder);
		attributeSetterBiConsumers.put(
			"order",
			(BiConsumer<SubjectVisitDefinition, String>)
				SubjectVisitDefinition::setOrder);
		attributeGetterFunctions.put(
			"extCode", SubjectVisitDefinition::getExtCode);
		attributeSetterBiConsumers.put(
			"extCode",
			(BiConsumer<SubjectVisitDefinition, String>)
				SubjectVisitDefinition::setExtCode);
		attributeGetterFunctions.put(
			"anchorType", SubjectVisitDefinition::getAnchorType);
		attributeSetterBiConsumers.put(
			"anchorType",
			(BiConsumer<SubjectVisitDefinition, String>)
				SubjectVisitDefinition::setAnchorType);
		attributeGetterFunctions.put(
			"offset", SubjectVisitDefinition::getOffset);
		attributeSetterBiConsumers.put(
			"offset",
			(BiConsumer<SubjectVisitDefinition, Integer>)
				SubjectVisitDefinition::setOffset);
		attributeGetterFunctions.put(
			"windowMinus", SubjectVisitDefinition::getWindowMinus);
		attributeSetterBiConsumers.put(
			"windowMinus",
			(BiConsumer<SubjectVisitDefinition, Integer>)
				SubjectVisitDefinition::setWindowMinus);
		attributeGetterFunctions.put(
			"windowPlus", SubjectVisitDefinition::getWindowPlus);
		attributeSetterBiConsumers.put(
			"windowPlus",
			(BiConsumer<SubjectVisitDefinition, Integer>)
				SubjectVisitDefinition::setWindowPlus);
		attributeGetterFunctions.put("type", SubjectVisitDefinition::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<SubjectVisitDefinition, Integer>)
				SubjectVisitDefinition::setType);
		attributeGetterFunctions.put(
			"repeatCount", SubjectVisitDefinition::getRepeatCount);
		attributeSetterBiConsumers.put(
			"repeatCount",
			(BiConsumer<SubjectVisitDefinition, Integer>)
				SubjectVisitDefinition::setRepeatCount);
		attributeGetterFunctions.put(
			"visitCRFId", SubjectVisitDefinition::getVisitCRFId);
		attributeSetterBiConsumers.put(
			"visitCRFId",
			(BiConsumer<SubjectVisitDefinition, Long>)
				SubjectVisitDefinition::setVisitCRFId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getSubjectVisitDefinitionId() {
		return _subjectVisitDefinitionId;
	}

	@Override
	public void setSubjectVisitDefinitionId(long subjectVisitDefinitionId) {
		_subjectVisitDefinitionId = subjectVisitDefinitionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getVisitGroupId() {
		return _visitGroupId;
	}

	@Override
	public void setVisitGroupId(long visitGroupId) {
		_columnBitmask |= VISITGROUPID_COLUMN_BITMASK;

		if (!_setOriginalVisitGroupId) {
			_setOriginalVisitGroupId = true;

			_originalVisitGroupId = _visitGroupId;
		}

		_visitGroupId = visitGroupId;
	}

	public long getOriginalVisitGroupId() {
		return _originalVisitGroupId;
	}

	@JSON
	@Override
	public long getSubjectId() {
		return _subjectId;
	}

	@Override
	public void setSubjectId(long subjectId) {
		_columnBitmask |= SUBJECTID_COLUMN_BITMASK;

		if (!_setOriginalSubjectId) {
			_setOriginalSubjectId = true;

			_originalSubjectId = _subjectId;
		}

		_subjectId = subjectId;
	}

	public long getOriginalSubjectId() {
		return _originalSubjectId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getParentCode() {
		if (_parentCode == null) {
			return "";
		}
		else {
			return _parentCode;
		}
	}

	@Override
	public void setParentCode(String parentCode) {
		_parentCode = parentCode;
	}

	@JSON
	@Override
	public String getVisitDefinitionCode() {
		if (_visitDefinitionCode == null) {
			return "";
		}
		else {
			return _visitDefinitionCode;
		}
	}

	@Override
	public void setVisitDefinitionCode(String visitDefinitionCode) {
		_visitDefinitionCode = visitDefinitionCode;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getOrder() {
		if (_order == null) {
			return "";
		}
		else {
			return _order;
		}
	}

	@Override
	public void setOrder(String order) {
		_order = order;
	}

	@JSON
	@Override
	public String getExtCode() {
		if (_extCode == null) {
			return "";
		}
		else {
			return _extCode;
		}
	}

	@Override
	public void setExtCode(String extCode) {
		_extCode = extCode;
	}

	@JSON
	@Override
	public String getAnchorType() {
		if (_anchorType == null) {
			return "";
		}
		else {
			return _anchorType;
		}
	}

	@Override
	public void setAnchorType(String anchorType) {
		_anchorType = anchorType;
	}

	@JSON
	@Override
	public int getOffset() {
		return _offset;
	}

	@Override
	public void setOffset(int offset) {
		_offset = offset;
	}

	@JSON
	@Override
	public int getWindowMinus() {
		return _windowMinus;
	}

	@Override
	public void setWindowMinus(int windowMinus) {
		_windowMinus = windowMinus;
	}

	@JSON
	@Override
	public int getWindowPlus() {
		return _windowPlus;
	}

	@Override
	public void setWindowPlus(int windowPlus) {
		_windowPlus = windowPlus;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_type = type;
	}

	@JSON
	@Override
	public int getRepeatCount() {
		return _repeatCount;
	}

	@Override
	public void setRepeatCount(int repeatCount) {
		_repeatCount = repeatCount;
	}

	@JSON
	@Override
	public long getVisitCRFId() {
		return _visitCRFId;
	}

	@Override
	public void setVisitCRFId(long visitCRFId) {
		_columnBitmask |= VISITCRFID_COLUMN_BITMASK;

		if (!_setOriginalVisitCRFId) {
			_setOriginalVisitCRFId = true;

			_originalVisitCRFId = _visitCRFId;
		}

		_visitCRFId = visitCRFId;
	}

	public long getOriginalVisitCRFId() {
		return _originalVisitCRFId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(SubjectVisitDefinition.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SubjectVisitDefinition.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SubjectVisitDefinition toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SubjectVisitDefinition>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubjectVisitDefinitionImpl subjectVisitDefinitionImpl =
			new SubjectVisitDefinitionImpl();

		subjectVisitDefinitionImpl.setUuid(getUuid());
		subjectVisitDefinitionImpl.setSubjectVisitDefinitionId(
			getSubjectVisitDefinitionId());
		subjectVisitDefinitionImpl.setGroupId(getGroupId());
		subjectVisitDefinitionImpl.setCompanyId(getCompanyId());
		subjectVisitDefinitionImpl.setProjectId(getProjectId());
		subjectVisitDefinitionImpl.setVisitGroupId(getVisitGroupId());
		subjectVisitDefinitionImpl.setSubjectId(getSubjectId());
		subjectVisitDefinitionImpl.setUserId(getUserId());
		subjectVisitDefinitionImpl.setUserName(getUserName());
		subjectVisitDefinitionImpl.setCreateDate(getCreateDate());
		subjectVisitDefinitionImpl.setModifiedDate(getModifiedDate());
		subjectVisitDefinitionImpl.setStatus(getStatus());
		subjectVisitDefinitionImpl.setStatusByUserId(getStatusByUserId());
		subjectVisitDefinitionImpl.setStatusByUserName(getStatusByUserName());
		subjectVisitDefinitionImpl.setStatusDate(getStatusDate());
		subjectVisitDefinitionImpl.setParentCode(getParentCode());
		subjectVisitDefinitionImpl.setVisitDefinitionCode(
			getVisitDefinitionCode());
		subjectVisitDefinitionImpl.setName(getName());
		subjectVisitDefinitionImpl.setOrder(getOrder());
		subjectVisitDefinitionImpl.setExtCode(getExtCode());
		subjectVisitDefinitionImpl.setAnchorType(getAnchorType());
		subjectVisitDefinitionImpl.setOffset(getOffset());
		subjectVisitDefinitionImpl.setWindowMinus(getWindowMinus());
		subjectVisitDefinitionImpl.setWindowPlus(getWindowPlus());
		subjectVisitDefinitionImpl.setType(getType());
		subjectVisitDefinitionImpl.setRepeatCount(getRepeatCount());
		subjectVisitDefinitionImpl.setVisitCRFId(getVisitCRFId());

		subjectVisitDefinitionImpl.resetOriginalValues();

		return subjectVisitDefinitionImpl;
	}

	@Override
	public int compareTo(SubjectVisitDefinition subjectVisitDefinition) {
		long primaryKey = subjectVisitDefinition.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SubjectVisitDefinition)) {
			return false;
		}

		SubjectVisitDefinition subjectVisitDefinition =
			(SubjectVisitDefinition)object;

		long primaryKey = subjectVisitDefinition.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalVisitGroupId = _visitGroupId;

		_setOriginalVisitGroupId = false;

		_originalSubjectId = _subjectId;

		_setOriginalSubjectId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;

		_originalVisitCRFId = _visitCRFId;

		_setOriginalVisitCRFId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SubjectVisitDefinition> toCacheModel() {
		SubjectVisitDefinitionCacheModel subjectVisitDefinitionCacheModel =
			new SubjectVisitDefinitionCacheModel();

		subjectVisitDefinitionCacheModel.uuid = getUuid();

		String uuid = subjectVisitDefinitionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			subjectVisitDefinitionCacheModel.uuid = null;
		}

		subjectVisitDefinitionCacheModel.subjectVisitDefinitionId =
			getSubjectVisitDefinitionId();

		subjectVisitDefinitionCacheModel.groupId = getGroupId();

		subjectVisitDefinitionCacheModel.companyId = getCompanyId();

		subjectVisitDefinitionCacheModel.projectId = getProjectId();

		subjectVisitDefinitionCacheModel.visitGroupId = getVisitGroupId();

		subjectVisitDefinitionCacheModel.subjectId = getSubjectId();

		subjectVisitDefinitionCacheModel.userId = getUserId();

		subjectVisitDefinitionCacheModel.userName = getUserName();

		String userName = subjectVisitDefinitionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			subjectVisitDefinitionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			subjectVisitDefinitionCacheModel.createDate = createDate.getTime();
		}
		else {
			subjectVisitDefinitionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			subjectVisitDefinitionCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			subjectVisitDefinitionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		subjectVisitDefinitionCacheModel.status = getStatus();

		subjectVisitDefinitionCacheModel.statusByUserId = getStatusByUserId();

		subjectVisitDefinitionCacheModel.statusByUserName =
			getStatusByUserName();

		String statusByUserName =
			subjectVisitDefinitionCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			subjectVisitDefinitionCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			subjectVisitDefinitionCacheModel.statusDate = statusDate.getTime();
		}
		else {
			subjectVisitDefinitionCacheModel.statusDate = Long.MIN_VALUE;
		}

		subjectVisitDefinitionCacheModel.parentCode = getParentCode();

		String parentCode = subjectVisitDefinitionCacheModel.parentCode;

		if ((parentCode != null) && (parentCode.length() == 0)) {
			subjectVisitDefinitionCacheModel.parentCode = null;
		}

		subjectVisitDefinitionCacheModel.visitDefinitionCode =
			getVisitDefinitionCode();

		String visitDefinitionCode =
			subjectVisitDefinitionCacheModel.visitDefinitionCode;

		if ((visitDefinitionCode != null) &&
			(visitDefinitionCode.length() == 0)) {

			subjectVisitDefinitionCacheModel.visitDefinitionCode = null;
		}

		subjectVisitDefinitionCacheModel.name = getName();

		String name = subjectVisitDefinitionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			subjectVisitDefinitionCacheModel.name = null;
		}

		subjectVisitDefinitionCacheModel.order = getOrder();

		String order = subjectVisitDefinitionCacheModel.order;

		if ((order != null) && (order.length() == 0)) {
			subjectVisitDefinitionCacheModel.order = null;
		}

		subjectVisitDefinitionCacheModel.extCode = getExtCode();

		String extCode = subjectVisitDefinitionCacheModel.extCode;

		if ((extCode != null) && (extCode.length() == 0)) {
			subjectVisitDefinitionCacheModel.extCode = null;
		}

		subjectVisitDefinitionCacheModel.anchorType = getAnchorType();

		String anchorType = subjectVisitDefinitionCacheModel.anchorType;

		if ((anchorType != null) && (anchorType.length() == 0)) {
			subjectVisitDefinitionCacheModel.anchorType = null;
		}

		subjectVisitDefinitionCacheModel.offset = getOffset();

		subjectVisitDefinitionCacheModel.windowMinus = getWindowMinus();

		subjectVisitDefinitionCacheModel.windowPlus = getWindowPlus();

		subjectVisitDefinitionCacheModel.type = getType();

		subjectVisitDefinitionCacheModel.repeatCount = getRepeatCount();

		subjectVisitDefinitionCacheModel.visitCRFId = getVisitCRFId();

		return subjectVisitDefinitionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SubjectVisitDefinition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SubjectVisitDefinition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubjectVisitDefinition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SubjectVisitDefinition)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SubjectVisitDefinition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SubjectVisitDefinition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubjectVisitDefinition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((SubjectVisitDefinition)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SubjectVisitDefinition>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SubjectVisitDefinition.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _subjectVisitDefinitionId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _visitGroupId;
	private long _originalVisitGroupId;
	private boolean _setOriginalVisitGroupId;
	private long _subjectId;
	private long _originalSubjectId;
	private boolean _setOriginalSubjectId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _parentCode;
	private String _visitDefinitionCode;
	private String _name;
	private String _order;
	private String _extCode;
	private String _anchorType;
	private int _offset;
	private int _windowMinus;
	private int _windowPlus;
	private int _type;
	private int _repeatCount;
	private long _visitCRFId;
	private long _originalVisitCRFId;
	private boolean _setOriginalVisitCRFId;
	private long _columnBitmask;
	private SubjectVisitDefinition _escapedModel;

}