/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.VisitGroup;
import com.dhsoft.edc.backend.model.VisitGroupModel;
import com.dhsoft.edc.backend.model.VisitGroupSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the VisitGroup service. Represents a row in the &quot;EDC_VisitGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VisitGroupModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VisitGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VisitGroupImpl
 * @generated
 */
@JSON(strict = true)
public class VisitGroupModelImpl
	extends BaseModelImpl<VisitGroup> implements VisitGroupModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a visit group model instance should use the <code>VisitGroup</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_VisitGroup";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"visitGroupId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"expGroupId", Types.BIGINT},
		{"visitGroupCode", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"activeStatus", Types.INTEGER},
		{"activeDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("visitGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("visitGroupCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("activeStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("activeDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_VisitGroup (uuid_ VARCHAR(75) null,visitGroupId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,expGroupId LONG,visitGroupCode VARCHAR(75) null,name VARCHAR(75) null,description VARCHAR(75) null,activeStatus INTEGER,activeDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table EDC_VisitGroup";

	public static final String ORDER_BY_JPQL =
		" ORDER BY visitGroup.visitGroupId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_VisitGroup.visitGroupId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long PROJECTID_COLUMN_BITMASK = 4L;

	public static final long USERID_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long VISITGROUPID_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VisitGroup toModel(VisitGroupSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VisitGroup model = new VisitGroupImpl();

		model.setUuid(soapModel.getUuid());
		model.setVisitGroupId(soapModel.getVisitGroupId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setExpGroupId(soapModel.getExpGroupId());
		model.setVisitGroupCode(soapModel.getVisitGroupCode());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setActiveStatus(soapModel.getActiveStatus());
		model.setActiveDate(soapModel.getActiveDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VisitGroup> toModels(VisitGroupSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VisitGroup> models = new ArrayList<VisitGroup>(soapModels.length);

		for (VisitGroupSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public VisitGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _visitGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVisitGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _visitGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VisitGroup.class;
	}

	@Override
	public String getModelClassName() {
		return VisitGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<VisitGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<VisitGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VisitGroup, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((VisitGroup)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<VisitGroup, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<VisitGroup, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(VisitGroup)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<VisitGroup, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<VisitGroup, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<VisitGroup, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<VisitGroup, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<VisitGroup, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<VisitGroup, Object>>();
		Map<String, BiConsumer<VisitGroup, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<VisitGroup, ?>>();

		attributeGetterFunctions.put("uuid", VisitGroup::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<VisitGroup, String>)VisitGroup::setUuid);
		attributeGetterFunctions.put(
			"visitGroupId", VisitGroup::getVisitGroupId);
		attributeSetterBiConsumers.put(
			"visitGroupId",
			(BiConsumer<VisitGroup, Long>)VisitGroup::setVisitGroupId);
		attributeGetterFunctions.put("groupId", VisitGroup::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<VisitGroup, Long>)VisitGroup::setGroupId);
		attributeGetterFunctions.put("companyId", VisitGroup::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<VisitGroup, Long>)VisitGroup::setCompanyId);
		attributeGetterFunctions.put("projectId", VisitGroup::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<VisitGroup, Long>)VisitGroup::setProjectId);
		attributeGetterFunctions.put("userId", VisitGroup::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<VisitGroup, Long>)VisitGroup::setUserId);
		attributeGetterFunctions.put("userName", VisitGroup::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<VisitGroup, String>)VisitGroup::setUserName);
		attributeGetterFunctions.put("createDate", VisitGroup::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<VisitGroup, Date>)VisitGroup::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", VisitGroup::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<VisitGroup, Date>)VisitGroup::setModifiedDate);
		attributeGetterFunctions.put("status", VisitGroup::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<VisitGroup, Integer>)VisitGroup::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", VisitGroup::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<VisitGroup, Long>)VisitGroup::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", VisitGroup::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<VisitGroup, String>)VisitGroup::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", VisitGroup::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<VisitGroup, Date>)VisitGroup::setStatusDate);
		attributeGetterFunctions.put("expGroupId", VisitGroup::getExpGroupId);
		attributeSetterBiConsumers.put(
			"expGroupId",
			(BiConsumer<VisitGroup, Long>)VisitGroup::setExpGroupId);
		attributeGetterFunctions.put(
			"visitGroupCode", VisitGroup::getVisitGroupCode);
		attributeSetterBiConsumers.put(
			"visitGroupCode",
			(BiConsumer<VisitGroup, String>)VisitGroup::setVisitGroupCode);
		attributeGetterFunctions.put("name", VisitGroup::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<VisitGroup, String>)VisitGroup::setName);
		attributeGetterFunctions.put("description", VisitGroup::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<VisitGroup, String>)VisitGroup::setDescription);
		attributeGetterFunctions.put(
			"activeStatus", VisitGroup::getActiveStatus);
		attributeSetterBiConsumers.put(
			"activeStatus",
			(BiConsumer<VisitGroup, Integer>)VisitGroup::setActiveStatus);
		attributeGetterFunctions.put("activeDate", VisitGroup::getActiveDate);
		attributeSetterBiConsumers.put(
			"activeDate",
			(BiConsumer<VisitGroup, Date>)VisitGroup::setActiveDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getVisitGroupId() {
		return _visitGroupId;
	}

	@Override
	public void setVisitGroupId(long visitGroupId) {
		_visitGroupId = visitGroupId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public long getExpGroupId() {
		return _expGroupId;
	}

	@Override
	public void setExpGroupId(long expGroupId) {
		_expGroupId = expGroupId;
	}

	@JSON
	@Override
	public String getVisitGroupCode() {
		if (_visitGroupCode == null) {
			return "";
		}
		else {
			return _visitGroupCode;
		}
	}

	@Override
	public void setVisitGroupCode(String visitGroupCode) {
		_visitGroupCode = visitGroupCode;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getActiveStatus() {
		return _activeStatus;
	}

	@Override
	public void setActiveStatus(int activeStatus) {
		_activeStatus = activeStatus;
	}

	@JSON
	@Override
	public Date getActiveDate() {
		return _activeDate;
	}

	@Override
	public void setActiveDate(Date activeDate) {
		_activeDate = activeDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(VisitGroup.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), VisitGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VisitGroup toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, VisitGroup>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VisitGroupImpl visitGroupImpl = new VisitGroupImpl();

		visitGroupImpl.setUuid(getUuid());
		visitGroupImpl.setVisitGroupId(getVisitGroupId());
		visitGroupImpl.setGroupId(getGroupId());
		visitGroupImpl.setCompanyId(getCompanyId());
		visitGroupImpl.setProjectId(getProjectId());
		visitGroupImpl.setUserId(getUserId());
		visitGroupImpl.setUserName(getUserName());
		visitGroupImpl.setCreateDate(getCreateDate());
		visitGroupImpl.setModifiedDate(getModifiedDate());
		visitGroupImpl.setStatus(getStatus());
		visitGroupImpl.setStatusByUserId(getStatusByUserId());
		visitGroupImpl.setStatusByUserName(getStatusByUserName());
		visitGroupImpl.setStatusDate(getStatusDate());
		visitGroupImpl.setExpGroupId(getExpGroupId());
		visitGroupImpl.setVisitGroupCode(getVisitGroupCode());
		visitGroupImpl.setName(getName());
		visitGroupImpl.setDescription(getDescription());
		visitGroupImpl.setActiveStatus(getActiveStatus());
		visitGroupImpl.setActiveDate(getActiveDate());

		visitGroupImpl.resetOriginalValues();

		return visitGroupImpl;
	}

	@Override
	public int compareTo(VisitGroup visitGroup) {
		long primaryKey = visitGroup.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof VisitGroup)) {
			return false;
		}

		VisitGroup visitGroup = (VisitGroup)object;

		long primaryKey = visitGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<VisitGroup> toCacheModel() {
		VisitGroupCacheModel visitGroupCacheModel = new VisitGroupCacheModel();

		visitGroupCacheModel.uuid = getUuid();

		String uuid = visitGroupCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			visitGroupCacheModel.uuid = null;
		}

		visitGroupCacheModel.visitGroupId = getVisitGroupId();

		visitGroupCacheModel.groupId = getGroupId();

		visitGroupCacheModel.companyId = getCompanyId();

		visitGroupCacheModel.projectId = getProjectId();

		visitGroupCacheModel.userId = getUserId();

		visitGroupCacheModel.userName = getUserName();

		String userName = visitGroupCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			visitGroupCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			visitGroupCacheModel.createDate = createDate.getTime();
		}
		else {
			visitGroupCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			visitGroupCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			visitGroupCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		visitGroupCacheModel.status = getStatus();

		visitGroupCacheModel.statusByUserId = getStatusByUserId();

		visitGroupCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = visitGroupCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			visitGroupCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			visitGroupCacheModel.statusDate = statusDate.getTime();
		}
		else {
			visitGroupCacheModel.statusDate = Long.MIN_VALUE;
		}

		visitGroupCacheModel.expGroupId = getExpGroupId();

		visitGroupCacheModel.visitGroupCode = getVisitGroupCode();

		String visitGroupCode = visitGroupCacheModel.visitGroupCode;

		if ((visitGroupCode != null) && (visitGroupCode.length() == 0)) {
			visitGroupCacheModel.visitGroupCode = null;
		}

		visitGroupCacheModel.name = getName();

		String name = visitGroupCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			visitGroupCacheModel.name = null;
		}

		visitGroupCacheModel.description = getDescription();

		String description = visitGroupCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			visitGroupCacheModel.description = null;
		}

		visitGroupCacheModel.activeStatus = getActiveStatus();

		Date activeDate = getActiveDate();

		if (activeDate != null) {
			visitGroupCacheModel.activeDate = activeDate.getTime();
		}
		else {
			visitGroupCacheModel.activeDate = Long.MIN_VALUE;
		}

		return visitGroupCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<VisitGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<VisitGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VisitGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((VisitGroup)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<VisitGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<VisitGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VisitGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((VisitGroup)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, VisitGroup>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					VisitGroup.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _visitGroupId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _expGroupId;
	private String _visitGroupCode;
	private String _name;
	private String _description;
	private int _activeStatus;
	private Date _activeDate;
	private long _columnBitmask;
	private VisitGroup _escapedModel;

}