/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.VisitDefinition;
import com.dhsoft.edc.backend.model.VisitDefinitionModel;
import com.dhsoft.edc.backend.model.VisitDefinitionSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the VisitDefinition service. Represents a row in the &quot;EDC_VisitDefinition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VisitDefinitionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VisitDefinitionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VisitDefinitionImpl
 * @generated
 */
@JSON(strict = true)
public class VisitDefinitionModelImpl
	extends BaseModelImpl<VisitDefinition> implements VisitDefinitionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a visit definition model instance should use the <code>VisitDefinition</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_VisitDefinition";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"visitDefinitionId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"visitGroupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"visitDefinitionCode", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"order_", Types.INTEGER}, {"anchorType", Types.VARCHAR},
		{"offset", Types.INTEGER}, {"windowMinus", Types.INTEGER},
		{"windowPlus", Types.INTEGER}, {"type_", Types.INTEGER},
		{"repeatCount", Types.INTEGER}, {"visitCRFId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("visitDefinitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("visitGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("visitDefinitionCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("order_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("anchorType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("offset", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("windowMinus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("windowPlus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("repeatCount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("visitCRFId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_VisitDefinition (uuid_ VARCHAR(75) null,visitDefinitionId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,visitGroupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,visitDefinitionCode VARCHAR(75) null,name VARCHAR(75) null,order_ INTEGER,anchorType VARCHAR(75) null,offset INTEGER,windowMinus INTEGER,windowPlus INTEGER,type_ INTEGER,repeatCount INTEGER,visitCRFId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table EDC_VisitDefinition";

	public static final String ORDER_BY_JPQL =
		" ORDER BY visitDefinition.visitDefinitionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_VisitDefinition.visitDefinitionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long PROJECTID_COLUMN_BITMASK = 4L;

	public static final long USERID_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long VISITCRFID_COLUMN_BITMASK = 32L;

	public static final long VISITDEFINITIONCODE_COLUMN_BITMASK = 64L;

	public static final long VISITGROUPID_COLUMN_BITMASK = 128L;

	public static final long VISITDEFINITIONID_COLUMN_BITMASK = 256L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VisitDefinition toModel(VisitDefinitionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VisitDefinition model = new VisitDefinitionImpl();

		model.setUuid(soapModel.getUuid());
		model.setVisitDefinitionId(soapModel.getVisitDefinitionId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setVisitGroupId(soapModel.getVisitGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setVisitDefinitionCode(soapModel.getVisitDefinitionCode());
		model.setName(soapModel.getName());
		model.setOrder(soapModel.getOrder());
		model.setAnchorType(soapModel.getAnchorType());
		model.setOffset(soapModel.getOffset());
		model.setWindowMinus(soapModel.getWindowMinus());
		model.setWindowPlus(soapModel.getWindowPlus());
		model.setType(soapModel.getType());
		model.setRepeatCount(soapModel.getRepeatCount());
		model.setVisitCRFId(soapModel.getVisitCRFId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VisitDefinition> toModels(
		VisitDefinitionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<VisitDefinition> models = new ArrayList<VisitDefinition>(
			soapModels.length);

		for (VisitDefinitionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public VisitDefinitionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _visitDefinitionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVisitDefinitionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _visitDefinitionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VisitDefinition.class;
	}

	@Override
	public String getModelClassName() {
		return VisitDefinition.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<VisitDefinition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<VisitDefinition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VisitDefinition, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((VisitDefinition)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<VisitDefinition, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<VisitDefinition, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(VisitDefinition)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<VisitDefinition, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<VisitDefinition, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<VisitDefinition, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<VisitDefinition, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<VisitDefinition, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<VisitDefinition, Object>>();
		Map<String, BiConsumer<VisitDefinition, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<VisitDefinition, ?>>();

		attributeGetterFunctions.put("uuid", VisitDefinition::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<VisitDefinition, String>)VisitDefinition::setUuid);
		attributeGetterFunctions.put(
			"visitDefinitionId", VisitDefinition::getVisitDefinitionId);
		attributeSetterBiConsumers.put(
			"visitDefinitionId",
			(BiConsumer<VisitDefinition, Long>)
				VisitDefinition::setVisitDefinitionId);
		attributeGetterFunctions.put("groupId", VisitDefinition::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<VisitDefinition, Long>)VisitDefinition::setGroupId);
		attributeGetterFunctions.put(
			"companyId", VisitDefinition::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<VisitDefinition, Long>)VisitDefinition::setCompanyId);
		attributeGetterFunctions.put(
			"projectId", VisitDefinition::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<VisitDefinition, Long>)VisitDefinition::setProjectId);
		attributeGetterFunctions.put(
			"visitGroupId", VisitDefinition::getVisitGroupId);
		attributeSetterBiConsumers.put(
			"visitGroupId",
			(BiConsumer<VisitDefinition, Long>)
				VisitDefinition::setVisitGroupId);
		attributeGetterFunctions.put("userId", VisitDefinition::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<VisitDefinition, Long>)VisitDefinition::setUserId);
		attributeGetterFunctions.put("userName", VisitDefinition::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<VisitDefinition, String>)VisitDefinition::setUserName);
		attributeGetterFunctions.put(
			"createDate", VisitDefinition::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<VisitDefinition, Date>)VisitDefinition::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", VisitDefinition::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<VisitDefinition, Date>)
				VisitDefinition::setModifiedDate);
		attributeGetterFunctions.put("status", VisitDefinition::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<VisitDefinition, Integer>)VisitDefinition::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", VisitDefinition::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<VisitDefinition, Long>)
				VisitDefinition::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", VisitDefinition::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<VisitDefinition, String>)
				VisitDefinition::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", VisitDefinition::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<VisitDefinition, Date>)VisitDefinition::setStatusDate);
		attributeGetterFunctions.put(
			"visitDefinitionCode", VisitDefinition::getVisitDefinitionCode);
		attributeSetterBiConsumers.put(
			"visitDefinitionCode",
			(BiConsumer<VisitDefinition, String>)
				VisitDefinition::setVisitDefinitionCode);
		attributeGetterFunctions.put("name", VisitDefinition::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<VisitDefinition, String>)VisitDefinition::setName);
		attributeGetterFunctions.put("order", VisitDefinition::getOrder);
		attributeSetterBiConsumers.put(
			"order",
			(BiConsumer<VisitDefinition, Integer>)VisitDefinition::setOrder);
		attributeGetterFunctions.put(
			"anchorType", VisitDefinition::getAnchorType);
		attributeSetterBiConsumers.put(
			"anchorType",
			(BiConsumer<VisitDefinition, String>)
				VisitDefinition::setAnchorType);
		attributeGetterFunctions.put("offset", VisitDefinition::getOffset);
		attributeSetterBiConsumers.put(
			"offset",
			(BiConsumer<VisitDefinition, Integer>)VisitDefinition::setOffset);
		attributeGetterFunctions.put(
			"windowMinus", VisitDefinition::getWindowMinus);
		attributeSetterBiConsumers.put(
			"windowMinus",
			(BiConsumer<VisitDefinition, Integer>)
				VisitDefinition::setWindowMinus);
		attributeGetterFunctions.put(
			"windowPlus", VisitDefinition::getWindowPlus);
		attributeSetterBiConsumers.put(
			"windowPlus",
			(BiConsumer<VisitDefinition, Integer>)
				VisitDefinition::setWindowPlus);
		attributeGetterFunctions.put("type", VisitDefinition::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<VisitDefinition, Integer>)VisitDefinition::setType);
		attributeGetterFunctions.put(
			"repeatCount", VisitDefinition::getRepeatCount);
		attributeSetterBiConsumers.put(
			"repeatCount",
			(BiConsumer<VisitDefinition, Integer>)
				VisitDefinition::setRepeatCount);
		attributeGetterFunctions.put(
			"visitCRFId", VisitDefinition::getVisitCRFId);
		attributeSetterBiConsumers.put(
			"visitCRFId",
			(BiConsumer<VisitDefinition, Long>)VisitDefinition::setVisitCRFId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getVisitDefinitionId() {
		return _visitDefinitionId;
	}

	@Override
	public void setVisitDefinitionId(long visitDefinitionId) {
		_visitDefinitionId = visitDefinitionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getVisitGroupId() {
		return _visitGroupId;
	}

	@Override
	public void setVisitGroupId(long visitGroupId) {
		_columnBitmask |= VISITGROUPID_COLUMN_BITMASK;

		if (!_setOriginalVisitGroupId) {
			_setOriginalVisitGroupId = true;

			_originalVisitGroupId = _visitGroupId;
		}

		_visitGroupId = visitGroupId;
	}

	public long getOriginalVisitGroupId() {
		return _originalVisitGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getVisitDefinitionCode() {
		if (_visitDefinitionCode == null) {
			return "";
		}
		else {
			return _visitDefinitionCode;
		}
	}

	@Override
	public void setVisitDefinitionCode(String visitDefinitionCode) {
		_columnBitmask |= VISITDEFINITIONCODE_COLUMN_BITMASK;

		if (_originalVisitDefinitionCode == null) {
			_originalVisitDefinitionCode = _visitDefinitionCode;
		}

		_visitDefinitionCode = visitDefinitionCode;
	}

	public String getOriginalVisitDefinitionCode() {
		return GetterUtil.getString(_originalVisitDefinitionCode);
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public int getOrder() {
		return _order;
	}

	@Override
	public void setOrder(int order) {
		_order = order;
	}

	@JSON
	@Override
	public String getAnchorType() {
		if (_anchorType == null) {
			return "";
		}
		else {
			return _anchorType;
		}
	}

	@Override
	public void setAnchorType(String anchorType) {
		_anchorType = anchorType;
	}

	@JSON
	@Override
	public int getOffset() {
		return _offset;
	}

	@Override
	public void setOffset(int offset) {
		_offset = offset;
	}

	@JSON
	@Override
	public int getWindowMinus() {
		return _windowMinus;
	}

	@Override
	public void setWindowMinus(int windowMinus) {
		_windowMinus = windowMinus;
	}

	@JSON
	@Override
	public int getWindowPlus() {
		return _windowPlus;
	}

	@Override
	public void setWindowPlus(int windowPlus) {
		_windowPlus = windowPlus;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_type = type;
	}

	@JSON
	@Override
	public int getRepeatCount() {
		return _repeatCount;
	}

	@Override
	public void setRepeatCount(int repeatCount) {
		_repeatCount = repeatCount;
	}

	@JSON
	@Override
	public long getVisitCRFId() {
		return _visitCRFId;
	}

	@Override
	public void setVisitCRFId(long visitCRFId) {
		_columnBitmask |= VISITCRFID_COLUMN_BITMASK;

		if (!_setOriginalVisitCRFId) {
			_setOriginalVisitCRFId = true;

			_originalVisitCRFId = _visitCRFId;
		}

		_visitCRFId = visitCRFId;
	}

	public long getOriginalVisitCRFId() {
		return _originalVisitCRFId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(VisitDefinition.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), VisitDefinition.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VisitDefinition toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, VisitDefinition>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VisitDefinitionImpl visitDefinitionImpl = new VisitDefinitionImpl();

		visitDefinitionImpl.setUuid(getUuid());
		visitDefinitionImpl.setVisitDefinitionId(getVisitDefinitionId());
		visitDefinitionImpl.setGroupId(getGroupId());
		visitDefinitionImpl.setCompanyId(getCompanyId());
		visitDefinitionImpl.setProjectId(getProjectId());
		visitDefinitionImpl.setVisitGroupId(getVisitGroupId());
		visitDefinitionImpl.setUserId(getUserId());
		visitDefinitionImpl.setUserName(getUserName());
		visitDefinitionImpl.setCreateDate(getCreateDate());
		visitDefinitionImpl.setModifiedDate(getModifiedDate());
		visitDefinitionImpl.setStatus(getStatus());
		visitDefinitionImpl.setStatusByUserId(getStatusByUserId());
		visitDefinitionImpl.setStatusByUserName(getStatusByUserName());
		visitDefinitionImpl.setStatusDate(getStatusDate());
		visitDefinitionImpl.setVisitDefinitionCode(getVisitDefinitionCode());
		visitDefinitionImpl.setName(getName());
		visitDefinitionImpl.setOrder(getOrder());
		visitDefinitionImpl.setAnchorType(getAnchorType());
		visitDefinitionImpl.setOffset(getOffset());
		visitDefinitionImpl.setWindowMinus(getWindowMinus());
		visitDefinitionImpl.setWindowPlus(getWindowPlus());
		visitDefinitionImpl.setType(getType());
		visitDefinitionImpl.setRepeatCount(getRepeatCount());
		visitDefinitionImpl.setVisitCRFId(getVisitCRFId());

		visitDefinitionImpl.resetOriginalValues();

		return visitDefinitionImpl;
	}

	@Override
	public int compareTo(VisitDefinition visitDefinition) {
		long primaryKey = visitDefinition.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof VisitDefinition)) {
			return false;
		}

		VisitDefinition visitDefinition = (VisitDefinition)object;

		long primaryKey = visitDefinition.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalVisitGroupId = _visitGroupId;

		_setOriginalVisitGroupId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;

		_originalVisitDefinitionCode = _visitDefinitionCode;

		_originalVisitCRFId = _visitCRFId;

		_setOriginalVisitCRFId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<VisitDefinition> toCacheModel() {
		VisitDefinitionCacheModel visitDefinitionCacheModel =
			new VisitDefinitionCacheModel();

		visitDefinitionCacheModel.uuid = getUuid();

		String uuid = visitDefinitionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			visitDefinitionCacheModel.uuid = null;
		}

		visitDefinitionCacheModel.visitDefinitionId = getVisitDefinitionId();

		visitDefinitionCacheModel.groupId = getGroupId();

		visitDefinitionCacheModel.companyId = getCompanyId();

		visitDefinitionCacheModel.projectId = getProjectId();

		visitDefinitionCacheModel.visitGroupId = getVisitGroupId();

		visitDefinitionCacheModel.userId = getUserId();

		visitDefinitionCacheModel.userName = getUserName();

		String userName = visitDefinitionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			visitDefinitionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			visitDefinitionCacheModel.createDate = createDate.getTime();
		}
		else {
			visitDefinitionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			visitDefinitionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			visitDefinitionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		visitDefinitionCacheModel.status = getStatus();

		visitDefinitionCacheModel.statusByUserId = getStatusByUserId();

		visitDefinitionCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = visitDefinitionCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			visitDefinitionCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			visitDefinitionCacheModel.statusDate = statusDate.getTime();
		}
		else {
			visitDefinitionCacheModel.statusDate = Long.MIN_VALUE;
		}

		visitDefinitionCacheModel.visitDefinitionCode =
			getVisitDefinitionCode();

		String visitDefinitionCode =
			visitDefinitionCacheModel.visitDefinitionCode;

		if ((visitDefinitionCode != null) &&
			(visitDefinitionCode.length() == 0)) {

			visitDefinitionCacheModel.visitDefinitionCode = null;
		}

		visitDefinitionCacheModel.name = getName();

		String name = visitDefinitionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			visitDefinitionCacheModel.name = null;
		}

		visitDefinitionCacheModel.order = getOrder();

		visitDefinitionCacheModel.anchorType = getAnchorType();

		String anchorType = visitDefinitionCacheModel.anchorType;

		if ((anchorType != null) && (anchorType.length() == 0)) {
			visitDefinitionCacheModel.anchorType = null;
		}

		visitDefinitionCacheModel.offset = getOffset();

		visitDefinitionCacheModel.windowMinus = getWindowMinus();

		visitDefinitionCacheModel.windowPlus = getWindowPlus();

		visitDefinitionCacheModel.type = getType();

		visitDefinitionCacheModel.repeatCount = getRepeatCount();

		visitDefinitionCacheModel.visitCRFId = getVisitCRFId();

		return visitDefinitionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<VisitDefinition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<VisitDefinition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VisitDefinition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((VisitDefinition)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<VisitDefinition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<VisitDefinition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VisitDefinition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((VisitDefinition)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, VisitDefinition>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					VisitDefinition.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _visitDefinitionId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _visitGroupId;
	private long _originalVisitGroupId;
	private boolean _setOriginalVisitGroupId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _visitDefinitionCode;
	private String _originalVisitDefinitionCode;
	private String _name;
	private int _order;
	private String _anchorType;
	private int _offset;
	private int _windowMinus;
	private int _windowPlus;
	private int _type;
	private int _repeatCount;
	private long _visitCRFId;
	private long _originalVisitCRFId;
	private boolean _setOriginalVisitCRFId;
	private long _columnBitmask;
	private VisitDefinition _escapedModel;

}