/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.model.impl;

import com.dhsoft.edc.backend.model.VisitEvent;
import com.dhsoft.edc.backend.model.VisitEventModel;
import com.dhsoft.edc.backend.model.VisitEventSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the VisitEvent service. Represents a row in the &quot;EDC_VisitEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VisitEventModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VisitEventImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VisitEventImpl
 * @generated
 */
@JSON(strict = true)
public class VisitEventModelImpl
	extends BaseModelImpl<VisitEvent> implements VisitEventModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a visit event model instance should use the <code>VisitEvent</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDC_VisitEvent";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"visitEventId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"institutionId", Types.BIGINT},
		{"subjectId", Types.BIGINT}, {"visitDefinitionId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"anchorType", Types.VARCHAR}, {"anchorDate", Types.TIMESTAMP},
		{"offset", Types.INTEGER}, {"planDate", Types.TIMESTAMP},
		{"eventDate", Types.TIMESTAMP}, {"deviationStatus", Types.VARCHAR},
		{"instanceLinkObj", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("visitEventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("institutionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("visitDefinitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("anchorType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("anchorDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("offset", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("planDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("eventDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("deviationStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("instanceLinkObj", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDC_VisitEvent (uuid_ VARCHAR(75) null,visitEventId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,institutionId LONG,subjectId LONG,visitDefinitionId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,anchorType VARCHAR(75) null,anchorDate DATE null,offset INTEGER,planDate DATE null,eventDate DATE null,deviationStatus VARCHAR(75) null,instanceLinkObj VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table EDC_VisitEvent";

	public static final String ORDER_BY_JPQL =
		" ORDER BY visitEvent.visitEventId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDC_VisitEvent.visitEventId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long INSTITUTIONID_COLUMN_BITMASK = 4L;

	public static final long PROJECTID_COLUMN_BITMASK = 8L;

	public static final long SUBJECTID_COLUMN_BITMASK = 16L;

	public static final long USERID_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static final long VISITDEFINITIONID_COLUMN_BITMASK = 128L;

	public static final long VISITEVENTID_COLUMN_BITMASK = 256L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VisitEvent toModel(VisitEventSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VisitEvent model = new VisitEventImpl();

		model.setUuid(soapModel.getUuid());
		model.setVisitEventId(soapModel.getVisitEventId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setInstitutionId(soapModel.getInstitutionId());
		model.setSubjectId(soapModel.getSubjectId());
		model.setVisitDefinitionId(soapModel.getVisitDefinitionId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setAnchorType(soapModel.getAnchorType());
		model.setAnchorDate(soapModel.getAnchorDate());
		model.setOffset(soapModel.getOffset());
		model.setPlanDate(soapModel.getPlanDate());
		model.setEventDate(soapModel.getEventDate());
		model.setDeviationStatus(soapModel.getDeviationStatus());
		model.setInstanceLinkObj(soapModel.getInstanceLinkObj());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VisitEvent> toModels(VisitEventSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VisitEvent> models = new ArrayList<VisitEvent>(soapModels.length);

		for (VisitEventSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public VisitEventModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _visitEventId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVisitEventId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _visitEventId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VisitEvent.class;
	}

	@Override
	public String getModelClassName() {
		return VisitEvent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<VisitEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<VisitEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VisitEvent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((VisitEvent)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<VisitEvent, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<VisitEvent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(VisitEvent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<VisitEvent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<VisitEvent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<VisitEvent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<VisitEvent, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<VisitEvent, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<VisitEvent, Object>>();
		Map<String, BiConsumer<VisitEvent, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<VisitEvent, ?>>();

		attributeGetterFunctions.put("uuid", VisitEvent::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<VisitEvent, String>)VisitEvent::setUuid);
		attributeGetterFunctions.put(
			"visitEventId", VisitEvent::getVisitEventId);
		attributeSetterBiConsumers.put(
			"visitEventId",
			(BiConsumer<VisitEvent, Long>)VisitEvent::setVisitEventId);
		attributeGetterFunctions.put("groupId", VisitEvent::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<VisitEvent, Long>)VisitEvent::setGroupId);
		attributeGetterFunctions.put("companyId", VisitEvent::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<VisitEvent, Long>)VisitEvent::setCompanyId);
		attributeGetterFunctions.put("projectId", VisitEvent::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<VisitEvent, Long>)VisitEvent::setProjectId);
		attributeGetterFunctions.put(
			"institutionId", VisitEvent::getInstitutionId);
		attributeSetterBiConsumers.put(
			"institutionId",
			(BiConsumer<VisitEvent, Long>)VisitEvent::setInstitutionId);
		attributeGetterFunctions.put("subjectId", VisitEvent::getSubjectId);
		attributeSetterBiConsumers.put(
			"subjectId",
			(BiConsumer<VisitEvent, Long>)VisitEvent::setSubjectId);
		attributeGetterFunctions.put(
			"visitDefinitionId", VisitEvent::getVisitDefinitionId);
		attributeSetterBiConsumers.put(
			"visitDefinitionId",
			(BiConsumer<VisitEvent, Long>)VisitEvent::setVisitDefinitionId);
		attributeGetterFunctions.put("userId", VisitEvent::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<VisitEvent, Long>)VisitEvent::setUserId);
		attributeGetterFunctions.put("userName", VisitEvent::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<VisitEvent, String>)VisitEvent::setUserName);
		attributeGetterFunctions.put("createDate", VisitEvent::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<VisitEvent, Date>)VisitEvent::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", VisitEvent::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<VisitEvent, Date>)VisitEvent::setModifiedDate);
		attributeGetterFunctions.put("status", VisitEvent::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<VisitEvent, Integer>)VisitEvent::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", VisitEvent::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<VisitEvent, Long>)VisitEvent::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", VisitEvent::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<VisitEvent, String>)VisitEvent::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", VisitEvent::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<VisitEvent, Date>)VisitEvent::setStatusDate);
		attributeGetterFunctions.put("anchorType", VisitEvent::getAnchorType);
		attributeSetterBiConsumers.put(
			"anchorType",
			(BiConsumer<VisitEvent, String>)VisitEvent::setAnchorType);
		attributeGetterFunctions.put("anchorDate", VisitEvent::getAnchorDate);
		attributeSetterBiConsumers.put(
			"anchorDate",
			(BiConsumer<VisitEvent, Date>)VisitEvent::setAnchorDate);
		attributeGetterFunctions.put("offset", VisitEvent::getOffset);
		attributeSetterBiConsumers.put(
			"offset", (BiConsumer<VisitEvent, Integer>)VisitEvent::setOffset);
		attributeGetterFunctions.put("planDate", VisitEvent::getPlanDate);
		attributeSetterBiConsumers.put(
			"planDate", (BiConsumer<VisitEvent, Date>)VisitEvent::setPlanDate);
		attributeGetterFunctions.put("eventDate", VisitEvent::getEventDate);
		attributeSetterBiConsumers.put(
			"eventDate",
			(BiConsumer<VisitEvent, Date>)VisitEvent::setEventDate);
		attributeGetterFunctions.put(
			"deviationStatus", VisitEvent::getDeviationStatus);
		attributeSetterBiConsumers.put(
			"deviationStatus",
			(BiConsumer<VisitEvent, String>)VisitEvent::setDeviationStatus);
		attributeGetterFunctions.put(
			"instanceLinkObj", VisitEvent::getInstanceLinkObj);
		attributeSetterBiConsumers.put(
			"instanceLinkObj",
			(BiConsumer<VisitEvent, String>)VisitEvent::setInstanceLinkObj);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getVisitEventId() {
		return _visitEventId;
	}

	@Override
	public void setVisitEventId(long visitEventId) {
		_visitEventId = visitEventId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@JSON
	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@JSON
	@Override
	public long getSubjectId() {
		return _subjectId;
	}

	@Override
	public void setSubjectId(long subjectId) {
		_columnBitmask |= SUBJECTID_COLUMN_BITMASK;

		if (!_setOriginalSubjectId) {
			_setOriginalSubjectId = true;

			_originalSubjectId = _subjectId;
		}

		_subjectId = subjectId;
	}

	public long getOriginalSubjectId() {
		return _originalSubjectId;
	}

	@JSON
	@Override
	public long getVisitDefinitionId() {
		return _visitDefinitionId;
	}

	@Override
	public void setVisitDefinitionId(long visitDefinitionId) {
		_columnBitmask |= VISITDEFINITIONID_COLUMN_BITMASK;

		if (!_setOriginalVisitDefinitionId) {
			_setOriginalVisitDefinitionId = true;

			_originalVisitDefinitionId = _visitDefinitionId;
		}

		_visitDefinitionId = visitDefinitionId;
	}

	public long getOriginalVisitDefinitionId() {
		return _originalVisitDefinitionId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getAnchorType() {
		if (_anchorType == null) {
			return "";
		}
		else {
			return _anchorType;
		}
	}

	@Override
	public void setAnchorType(String anchorType) {
		_anchorType = anchorType;
	}

	@JSON
	@Override
	public Date getAnchorDate() {
		return _anchorDate;
	}

	@Override
	public void setAnchorDate(Date anchorDate) {
		_anchorDate = anchorDate;
	}

	@JSON
	@Override
	public int getOffset() {
		return _offset;
	}

	@Override
	public void setOffset(int offset) {
		_offset = offset;
	}

	@JSON
	@Override
	public Date getPlanDate() {
		return _planDate;
	}

	@Override
	public void setPlanDate(Date planDate) {
		_planDate = planDate;
	}

	@JSON
	@Override
	public Date getEventDate() {
		return _eventDate;
	}

	@Override
	public void setEventDate(Date eventDate) {
		_eventDate = eventDate;
	}

	@JSON
	@Override
	public String getDeviationStatus() {
		if (_deviationStatus == null) {
			return "";
		}
		else {
			return _deviationStatus;
		}
	}

	@Override
	public void setDeviationStatus(String deviationStatus) {
		_deviationStatus = deviationStatus;
	}

	@JSON
	@Override
	public String getInstanceLinkObj() {
		if (_instanceLinkObj == null) {
			return "";
		}
		else {
			return _instanceLinkObj;
		}
	}

	@Override
	public void setInstanceLinkObj(String instanceLinkObj) {
		_instanceLinkObj = instanceLinkObj;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(VisitEvent.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), VisitEvent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VisitEvent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, VisitEvent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VisitEventImpl visitEventImpl = new VisitEventImpl();

		visitEventImpl.setUuid(getUuid());
		visitEventImpl.setVisitEventId(getVisitEventId());
		visitEventImpl.setGroupId(getGroupId());
		visitEventImpl.setCompanyId(getCompanyId());
		visitEventImpl.setProjectId(getProjectId());
		visitEventImpl.setInstitutionId(getInstitutionId());
		visitEventImpl.setSubjectId(getSubjectId());
		visitEventImpl.setVisitDefinitionId(getVisitDefinitionId());
		visitEventImpl.setUserId(getUserId());
		visitEventImpl.setUserName(getUserName());
		visitEventImpl.setCreateDate(getCreateDate());
		visitEventImpl.setModifiedDate(getModifiedDate());
		visitEventImpl.setStatus(getStatus());
		visitEventImpl.setStatusByUserId(getStatusByUserId());
		visitEventImpl.setStatusByUserName(getStatusByUserName());
		visitEventImpl.setStatusDate(getStatusDate());
		visitEventImpl.setAnchorType(getAnchorType());
		visitEventImpl.setAnchorDate(getAnchorDate());
		visitEventImpl.setOffset(getOffset());
		visitEventImpl.setPlanDate(getPlanDate());
		visitEventImpl.setEventDate(getEventDate());
		visitEventImpl.setDeviationStatus(getDeviationStatus());
		visitEventImpl.setInstanceLinkObj(getInstanceLinkObj());

		visitEventImpl.resetOriginalValues();

		return visitEventImpl;
	}

	@Override
	public int compareTo(VisitEvent visitEvent) {
		long primaryKey = visitEvent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof VisitEvent)) {
			return false;
		}

		VisitEvent visitEvent = (VisitEvent)object;

		long primaryKey = visitEvent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProjectId = _projectId;

		_setOriginalProjectId = false;

		_originalInstitutionId = _institutionId;

		_setOriginalInstitutionId = false;

		_originalSubjectId = _subjectId;

		_setOriginalSubjectId = false;

		_originalVisitDefinitionId = _visitDefinitionId;

		_setOriginalVisitDefinitionId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<VisitEvent> toCacheModel() {
		VisitEventCacheModel visitEventCacheModel = new VisitEventCacheModel();

		visitEventCacheModel.uuid = getUuid();

		String uuid = visitEventCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			visitEventCacheModel.uuid = null;
		}

		visitEventCacheModel.visitEventId = getVisitEventId();

		visitEventCacheModel.groupId = getGroupId();

		visitEventCacheModel.companyId = getCompanyId();

		visitEventCacheModel.projectId = getProjectId();

		visitEventCacheModel.institutionId = getInstitutionId();

		visitEventCacheModel.subjectId = getSubjectId();

		visitEventCacheModel.visitDefinitionId = getVisitDefinitionId();

		visitEventCacheModel.userId = getUserId();

		visitEventCacheModel.userName = getUserName();

		String userName = visitEventCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			visitEventCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			visitEventCacheModel.createDate = createDate.getTime();
		}
		else {
			visitEventCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			visitEventCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			visitEventCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		visitEventCacheModel.status = getStatus();

		visitEventCacheModel.statusByUserId = getStatusByUserId();

		visitEventCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = visitEventCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			visitEventCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			visitEventCacheModel.statusDate = statusDate.getTime();
		}
		else {
			visitEventCacheModel.statusDate = Long.MIN_VALUE;
		}

		visitEventCacheModel.anchorType = getAnchorType();

		String anchorType = visitEventCacheModel.anchorType;

		if ((anchorType != null) && (anchorType.length() == 0)) {
			visitEventCacheModel.anchorType = null;
		}

		Date anchorDate = getAnchorDate();

		if (anchorDate != null) {
			visitEventCacheModel.anchorDate = anchorDate.getTime();
		}
		else {
			visitEventCacheModel.anchorDate = Long.MIN_VALUE;
		}

		visitEventCacheModel.offset = getOffset();

		Date planDate = getPlanDate();

		if (planDate != null) {
			visitEventCacheModel.planDate = planDate.getTime();
		}
		else {
			visitEventCacheModel.planDate = Long.MIN_VALUE;
		}

		Date eventDate = getEventDate();

		if (eventDate != null) {
			visitEventCacheModel.eventDate = eventDate.getTime();
		}
		else {
			visitEventCacheModel.eventDate = Long.MIN_VALUE;
		}

		visitEventCacheModel.deviationStatus = getDeviationStatus();

		String deviationStatus = visitEventCacheModel.deviationStatus;

		if ((deviationStatus != null) && (deviationStatus.length() == 0)) {
			visitEventCacheModel.deviationStatus = null;
		}

		visitEventCacheModel.instanceLinkObj = getInstanceLinkObj();

		String instanceLinkObj = visitEventCacheModel.instanceLinkObj;

		if ((instanceLinkObj != null) && (instanceLinkObj.length() == 0)) {
			visitEventCacheModel.instanceLinkObj = null;
		}

		return visitEventCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<VisitEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<VisitEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VisitEvent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((VisitEvent)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<VisitEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<VisitEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VisitEvent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((VisitEvent)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, VisitEvent>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					VisitEvent.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _visitEventId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _subjectId;
	private long _originalSubjectId;
	private boolean _setOriginalSubjectId;
	private long _visitDefinitionId;
	private long _originalVisitDefinitionId;
	private boolean _setOriginalVisitDefinitionId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _anchorType;
	private Date _anchorDate;
	private int _offset;
	private Date _planDate;
	private Date _eventDate;
	private String _deviationStatus;
	private String _instanceLinkObj;
	private long _columnBitmask;
	private VisitEvent _escapedModel;

}