/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.service.base;

import com.dhsoft.edc.backend.model.ApprovalRequest;
import com.dhsoft.edc.backend.service.ApprovalRequestLocalService;
import com.dhsoft.edc.backend.service.ApprovalRequestLocalServiceUtil;
import com.dhsoft.edc.backend.service.persistence.ApprovalRequestPersistence;
import com.dhsoft.edc.backend.service.persistence.AssignAuditPersistence;
import com.dhsoft.edc.backend.service.persistence.AssignInstitutionRolePersistence;
import com.dhsoft.edc.backend.service.persistence.AssignProjectScopePersistence;
import com.dhsoft.edc.backend.service.persistence.ExperimentalGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.InstResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.InstanceLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.InstitutionPersistence;
import com.dhsoft.edc.backend.service.persistence.MetaCodePersistence;
import com.dhsoft.edc.backend.service.persistence.MetaGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.ProjectPersistence;
import com.dhsoft.edc.backend.service.persistence.QueryLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.RandomizationPersistence;
import com.dhsoft.edc.backend.service.persistence.ResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectVisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitEventPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitGroupPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the approval request local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dhsoft.edc.backend.service.impl.ApprovalRequestLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dhsoft.edc.backend.service.impl.ApprovalRequestLocalServiceImpl
 * @generated
 */
public abstract class ApprovalRequestLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, ApprovalRequestLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ApprovalRequestLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ApprovalRequestLocalServiceUtil</code>.
	 */

	/**
	 * Adds the approval request to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApprovalRequestLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param approvalRequest the approval request
	 * @return the approval request that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ApprovalRequest addApprovalRequest(ApprovalRequest approvalRequest) {
		approvalRequest.setNew(true);

		return approvalRequestPersistence.update(approvalRequest);
	}

	/**
	 * Creates a new approval request with the primary key. Does not add the approval request to the database.
	 *
	 * @param approvalRequestId the primary key for the new approval request
	 * @return the new approval request
	 */
	@Override
	@Transactional(enabled = false)
	public ApprovalRequest createApprovalRequest(long approvalRequestId) {
		return approvalRequestPersistence.create(approvalRequestId);
	}

	/**
	 * Deletes the approval request with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApprovalRequestLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param approvalRequestId the primary key of the approval request
	 * @return the approval request that was removed
	 * @throws PortalException if a approval request with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ApprovalRequest deleteApprovalRequest(long approvalRequestId)
		throws PortalException {

		return approvalRequestPersistence.remove(approvalRequestId);
	}

	/**
	 * Deletes the approval request from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApprovalRequestLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param approvalRequest the approval request
	 * @return the approval request that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ApprovalRequest deleteApprovalRequest(
		ApprovalRequest approvalRequest) {

		return approvalRequestPersistence.remove(approvalRequest);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ApprovalRequest.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return approvalRequestPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.ApprovalRequestModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return approvalRequestPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.ApprovalRequestModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return approvalRequestPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return approvalRequestPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return approvalRequestPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ApprovalRequest fetchApprovalRequest(long approvalRequestId) {
		return approvalRequestPersistence.fetchByPrimaryKey(approvalRequestId);
	}

	/**
	 * Returns the approval request matching the UUID and group.
	 *
	 * @param uuid the approval request's UUID
	 * @param groupId the primary key of the group
	 * @return the matching approval request, or <code>null</code> if a matching approval request could not be found
	 */
	@Override
	public ApprovalRequest fetchApprovalRequestByUuidAndGroupId(
		String uuid, long groupId) {

		return approvalRequestPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the approval request with the primary key.
	 *
	 * @param approvalRequestId the primary key of the approval request
	 * @return the approval request
	 * @throws PortalException if a approval request with the primary key could not be found
	 */
	@Override
	public ApprovalRequest getApprovalRequest(long approvalRequestId)
		throws PortalException {

		return approvalRequestPersistence.findByPrimaryKey(approvalRequestId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(approvalRequestLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ApprovalRequest.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("approvalRequestId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			approvalRequestLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ApprovalRequest.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"approvalRequestId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(approvalRequestLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ApprovalRequest.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("approvalRequestId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return approvalRequestLocalService.deleteApprovalRequest(
			(ApprovalRequest)persistedModel);
	}

	public BasePersistence<ApprovalRequest> getBasePersistence() {
		return approvalRequestPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return approvalRequestPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the approval requests matching the UUID and company.
	 *
	 * @param uuid the UUID of the approval requests
	 * @param companyId the primary key of the company
	 * @return the matching approval requests, or an empty list if no matches were found
	 */
	@Override
	public List<ApprovalRequest> getApprovalRequestsByUuidAndCompanyId(
		String uuid, long companyId) {

		return approvalRequestPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of approval requests matching the UUID and company.
	 *
	 * @param uuid the UUID of the approval requests
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of approval requests
	 * @param end the upper bound of the range of approval requests (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching approval requests, or an empty list if no matches were found
	 */
	@Override
	public List<ApprovalRequest> getApprovalRequestsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<ApprovalRequest> orderByComparator) {

		return approvalRequestPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the approval request matching the UUID and group.
	 *
	 * @param uuid the approval request's UUID
	 * @param groupId the primary key of the group
	 * @return the matching approval request
	 * @throws PortalException if a matching approval request could not be found
	 */
	@Override
	public ApprovalRequest getApprovalRequestByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return approvalRequestPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the approval requests.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.ApprovalRequestModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of approval requests
	 * @param end the upper bound of the range of approval requests (not inclusive)
	 * @return the range of approval requests
	 */
	@Override
	public List<ApprovalRequest> getApprovalRequests(int start, int end) {
		return approvalRequestPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of approval requests.
	 *
	 * @return the number of approval requests
	 */
	@Override
	public int getApprovalRequestsCount() {
		return approvalRequestPersistence.countAll();
	}

	/**
	 * Updates the approval request in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApprovalRequestLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param approvalRequest the approval request
	 * @return the approval request that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ApprovalRequest updateApprovalRequest(
		ApprovalRequest approvalRequest) {

		return approvalRequestPersistence.update(approvalRequest);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ApprovalRequestLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		approvalRequestLocalService = (ApprovalRequestLocalService)aopProxy;

		_setLocalServiceUtilService(approvalRequestLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ApprovalRequestLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ApprovalRequest.class;
	}

	protected String getModelClassName() {
		return ApprovalRequest.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = approvalRequestPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ApprovalRequestLocalService approvalRequestLocalService) {

		try {
			Field field =
				ApprovalRequestLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, approvalRequestLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected ApprovalRequestLocalService approvalRequestLocalService;

	@Reference
	protected ApprovalRequestPersistence approvalRequestPersistence;

	@Reference
	protected AssignAuditPersistence assignAuditPersistence;

	@Reference
	protected AssignInstitutionRolePersistence assignInstitutionRolePersistence;

	@Reference
	protected AssignProjectScopePersistence assignProjectScopePersistence;

	@Reference
	protected ExperimentalGroupPersistence experimentalGroupPersistence;

	@Reference
	protected InstanceLinkPersistence instanceLinkPersistence;

	@Reference
	protected InstitutionPersistence institutionPersistence;

	@Reference
	protected InstResearcherPersistence instResearcherPersistence;

	@Reference
	protected MetaCodePersistence metaCodePersistence;

	@Reference
	protected MetaGroupPersistence metaGroupPersistence;

	@Reference
	protected ProjectPersistence projectPersistence;

	@Reference
	protected QueryLinkPersistence queryLinkPersistence;

	@Reference
	protected RandomizationPersistence randomizationPersistence;

	@Reference
	protected ResearcherPersistence researcherPersistence;

	@Reference
	protected SubjectPersistence subjectPersistence;

	@Reference
	protected SubjectVisitDefinitionPersistence
		subjectVisitDefinitionPersistence;

	@Reference
	protected VisitDefinitionPersistence visitDefinitionPersistence;

	@Reference
	protected VisitEventPersistence visitEventPersistence;

	@Reference
	protected VisitGroupPersistence visitGroupPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService
		workflowInstanceLinkLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetLinkLocalService
		assetLinkLocalService;

	@Reference
	protected com.liferay.ratings.kernel.service.RatingsStatsLocalService
		ratingsStatsLocalService;

	@Reference
	protected com.liferay.trash.kernel.service.TrashEntryLocalService
		trashEntryLocalService;

	@Reference
	protected com.liferay.trash.kernel.service.TrashVersionLocalService
		trashVersionLocalService;

}