/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.service.base;

import com.dhsoft.edc.backend.model.AssignInstitutionRole;
import com.dhsoft.edc.backend.service.AssignInstitutionRoleLocalService;
import com.dhsoft.edc.backend.service.AssignInstitutionRoleLocalServiceUtil;
import com.dhsoft.edc.backend.service.persistence.ApprovalRequestPersistence;
import com.dhsoft.edc.backend.service.persistence.AssignAuditPersistence;
import com.dhsoft.edc.backend.service.persistence.AssignInstitutionRolePersistence;
import com.dhsoft.edc.backend.service.persistence.AssignProjectScopePersistence;
import com.dhsoft.edc.backend.service.persistence.ExperimentalGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.InstResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.InstanceLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.InstitutionPersistence;
import com.dhsoft.edc.backend.service.persistence.MetaCodePersistence;
import com.dhsoft.edc.backend.service.persistence.MetaGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.ProjectPersistence;
import com.dhsoft.edc.backend.service.persistence.QueryLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.RandomizationPersistence;
import com.dhsoft.edc.backend.service.persistence.ResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectVisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitEventPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitGroupPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the assign institution role local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dhsoft.edc.backend.service.impl.AssignInstitutionRoleLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dhsoft.edc.backend.service.impl.AssignInstitutionRoleLocalServiceImpl
 * @generated
 */
public abstract class AssignInstitutionRoleLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, AssignInstitutionRoleLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AssignInstitutionRoleLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AssignInstitutionRoleLocalServiceUtil</code>.
	 */

	/**
	 * Adds the assign institution role to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssignInstitutionRoleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assignInstitutionRole the assign institution role
	 * @return the assign institution role that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssignInstitutionRole addAssignInstitutionRole(
		AssignInstitutionRole assignInstitutionRole) {

		assignInstitutionRole.setNew(true);

		return assignInstitutionRolePersistence.update(assignInstitutionRole);
	}

	/**
	 * Creates a new assign institution role with the primary key. Does not add the assign institution role to the database.
	 *
	 * @param institutionRoleId the primary key for the new assign institution role
	 * @return the new assign institution role
	 */
	@Override
	@Transactional(enabled = false)
	public AssignInstitutionRole createAssignInstitutionRole(
		long institutionRoleId) {

		return assignInstitutionRolePersistence.create(institutionRoleId);
	}

	/**
	 * Deletes the assign institution role with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssignInstitutionRoleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param institutionRoleId the primary key of the assign institution role
	 * @return the assign institution role that was removed
	 * @throws PortalException if a assign institution role with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssignInstitutionRole deleteAssignInstitutionRole(
			long institutionRoleId)
		throws PortalException {

		return assignInstitutionRolePersistence.remove(institutionRoleId);
	}

	/**
	 * Deletes the assign institution role from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssignInstitutionRoleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assignInstitutionRole the assign institution role
	 * @return the assign institution role that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssignInstitutionRole deleteAssignInstitutionRole(
		AssignInstitutionRole assignInstitutionRole) {

		return assignInstitutionRolePersistence.remove(assignInstitutionRole);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AssignInstitutionRole.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assignInstitutionRolePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.AssignInstitutionRoleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return assignInstitutionRolePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.AssignInstitutionRoleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return assignInstitutionRolePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assignInstitutionRolePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return assignInstitutionRolePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AssignInstitutionRole fetchAssignInstitutionRole(
		long institutionRoleId) {

		return assignInstitutionRolePersistence.fetchByPrimaryKey(
			institutionRoleId);
	}

	/**
	 * Returns the assign institution role matching the UUID and group.
	 *
	 * @param uuid the assign institution role's UUID
	 * @param groupId the primary key of the group
	 * @return the matching assign institution role, or <code>null</code> if a matching assign institution role could not be found
	 */
	@Override
	public AssignInstitutionRole fetchAssignInstitutionRoleByUuidAndGroupId(
		String uuid, long groupId) {

		return assignInstitutionRolePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the assign institution role with the primary key.
	 *
	 * @param institutionRoleId the primary key of the assign institution role
	 * @return the assign institution role
	 * @throws PortalException if a assign institution role with the primary key could not be found
	 */
	@Override
	public AssignInstitutionRole getAssignInstitutionRole(
			long institutionRoleId)
		throws PortalException {

		return assignInstitutionRolePersistence.findByPrimaryKey(
			institutionRoleId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			assignInstitutionRoleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssignInstitutionRole.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("institutionRoleId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			assignInstitutionRoleLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			AssignInstitutionRole.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"institutionRoleId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			assignInstitutionRoleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssignInstitutionRole.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("institutionRoleId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<AssignInstitutionRole>() {

				@Override
				public void performAction(
						AssignInstitutionRole assignInstitutionRole)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, assignInstitutionRole);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					AssignInstitutionRole.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return assignInstitutionRoleLocalService.deleteAssignInstitutionRole(
			(AssignInstitutionRole)persistedModel);
	}

	public BasePersistence<AssignInstitutionRole> getBasePersistence() {
		return assignInstitutionRolePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return assignInstitutionRolePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the assign institution roles matching the UUID and company.
	 *
	 * @param uuid the UUID of the assign institution roles
	 * @param companyId the primary key of the company
	 * @return the matching assign institution roles, or an empty list if no matches were found
	 */
	@Override
	public List<AssignInstitutionRole>
		getAssignInstitutionRolesByUuidAndCompanyId(
			String uuid, long companyId) {

		return assignInstitutionRolePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of assign institution roles matching the UUID and company.
	 *
	 * @param uuid the UUID of the assign institution roles
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of assign institution roles
	 * @param end the upper bound of the range of assign institution roles (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching assign institution roles, or an empty list if no matches were found
	 */
	@Override
	public List<AssignInstitutionRole>
		getAssignInstitutionRolesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<AssignInstitutionRole> orderByComparator) {

		return assignInstitutionRolePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the assign institution role matching the UUID and group.
	 *
	 * @param uuid the assign institution role's UUID
	 * @param groupId the primary key of the group
	 * @return the matching assign institution role
	 * @throws PortalException if a matching assign institution role could not be found
	 */
	@Override
	public AssignInstitutionRole getAssignInstitutionRoleByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return assignInstitutionRolePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the assign institution roles.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.AssignInstitutionRoleModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of assign institution roles
	 * @param end the upper bound of the range of assign institution roles (not inclusive)
	 * @return the range of assign institution roles
	 */
	@Override
	public List<AssignInstitutionRole> getAssignInstitutionRoles(
		int start, int end) {

		return assignInstitutionRolePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of assign institution roles.
	 *
	 * @return the number of assign institution roles
	 */
	@Override
	public int getAssignInstitutionRolesCount() {
		return assignInstitutionRolePersistence.countAll();
	}

	/**
	 * Updates the assign institution role in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssignInstitutionRoleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assignInstitutionRole the assign institution role
	 * @return the assign institution role that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssignInstitutionRole updateAssignInstitutionRole(
		AssignInstitutionRole assignInstitutionRole) {

		return assignInstitutionRolePersistence.update(assignInstitutionRole);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AssignInstitutionRoleLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		assignInstitutionRoleLocalService =
			(AssignInstitutionRoleLocalService)aopProxy;

		_setLocalServiceUtilService(assignInstitutionRoleLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssignInstitutionRoleLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssignInstitutionRole.class;
	}

	protected String getModelClassName() {
		return AssignInstitutionRole.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				assignInstitutionRolePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AssignInstitutionRoleLocalService assignInstitutionRoleLocalService) {

		try {
			Field field =
				AssignInstitutionRoleLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, assignInstitutionRoleLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected ApprovalRequestPersistence approvalRequestPersistence;

	@Reference
	protected AssignAuditPersistence assignAuditPersistence;

	protected AssignInstitutionRoleLocalService
		assignInstitutionRoleLocalService;

	@Reference
	protected AssignInstitutionRolePersistence assignInstitutionRolePersistence;

	@Reference
	protected AssignProjectScopePersistence assignProjectScopePersistence;

	@Reference
	protected ExperimentalGroupPersistence experimentalGroupPersistence;

	@Reference
	protected InstanceLinkPersistence instanceLinkPersistence;

	@Reference
	protected InstitutionPersistence institutionPersistence;

	@Reference
	protected InstResearcherPersistence instResearcherPersistence;

	@Reference
	protected MetaCodePersistence metaCodePersistence;

	@Reference
	protected MetaGroupPersistence metaGroupPersistence;

	@Reference
	protected ProjectPersistence projectPersistence;

	@Reference
	protected QueryLinkPersistence queryLinkPersistence;

	@Reference
	protected RandomizationPersistence randomizationPersistence;

	@Reference
	protected ResearcherPersistence researcherPersistence;

	@Reference
	protected SubjectPersistence subjectPersistence;

	@Reference
	protected SubjectVisitDefinitionPersistence
		subjectVisitDefinitionPersistence;

	@Reference
	protected VisitDefinitionPersistence visitDefinitionPersistence;

	@Reference
	protected VisitEventPersistence visitEventPersistence;

	@Reference
	protected VisitGroupPersistence visitGroupPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}