/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.service.base;

import com.dhsoft.edc.backend.model.EdcPermissionScope;
import com.dhsoft.edc.backend.service.EdcPermissionScopeLocalService;
import com.dhsoft.edc.backend.service.EdcPermissionScopeLocalServiceUtil;
import com.dhsoft.edc.backend.service.persistence.EdcLockPersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionRoleAuditPersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionRolePersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionScopeAuditPersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionScopePersistence;
import com.dhsoft.edc.backend.service.persistence.ExperimentalGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.InstResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.InstanceLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.InstitutionPersistence;
import com.dhsoft.edc.backend.service.persistence.MetaCodePersistence;
import com.dhsoft.edc.backend.service.persistence.MetaGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.ProjectPersistence;
import com.dhsoft.edc.backend.service.persistence.QueryLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.RandomizationPersistence;
import com.dhsoft.edc.backend.service.persistence.ResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectVisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitEventPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitGroupPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the edc permission scope local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dhsoft.edc.backend.service.impl.EdcPermissionScopeLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dhsoft.edc.backend.service.impl.EdcPermissionScopeLocalServiceImpl
 * @generated
 */
public abstract class EdcPermissionScopeLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, EdcPermissionScopeLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EdcPermissionScopeLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>EdcPermissionScopeLocalServiceUtil</code>.
	 */

	/**
	 * Adds the edc permission scope to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionScopeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param edcPermissionScope the edc permission scope
	 * @return the edc permission scope that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EdcPermissionScope addEdcPermissionScope(
		EdcPermissionScope edcPermissionScope) {

		edcPermissionScope.setNew(true);

		return edcPermissionScopePersistence.update(edcPermissionScope);
	}

	/**
	 * Creates a new edc permission scope with the primary key. Does not add the edc permission scope to the database.
	 *
	 * @param permissionScopeId the primary key for the new edc permission scope
	 * @return the new edc permission scope
	 */
	@Override
	@Transactional(enabled = false)
	public EdcPermissionScope createEdcPermissionScope(long permissionScopeId) {
		return edcPermissionScopePersistence.create(permissionScopeId);
	}

	/**
	 * Deletes the edc permission scope with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionScopeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param permissionScopeId the primary key of the edc permission scope
	 * @return the edc permission scope that was removed
	 * @throws PortalException if a edc permission scope with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EdcPermissionScope deleteEdcPermissionScope(long permissionScopeId)
		throws PortalException {

		return edcPermissionScopePersistence.remove(permissionScopeId);
	}

	/**
	 * Deletes the edc permission scope from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionScopeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param edcPermissionScope the edc permission scope
	 * @return the edc permission scope that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EdcPermissionScope deleteEdcPermissionScope(
		EdcPermissionScope edcPermissionScope) {

		return edcPermissionScopePersistence.remove(edcPermissionScope);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			EdcPermissionScope.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return edcPermissionScopePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return edcPermissionScopePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return edcPermissionScopePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return edcPermissionScopePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return edcPermissionScopePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public EdcPermissionScope fetchEdcPermissionScope(long permissionScopeId) {
		return edcPermissionScopePersistence.fetchByPrimaryKey(
			permissionScopeId);
	}

	/**
	 * Returns the edc permission scope matching the UUID and group.
	 *
	 * @param uuid the edc permission scope's UUID
	 * @param groupId the primary key of the group
	 * @return the matching edc permission scope, or <code>null</code> if a matching edc permission scope could not be found
	 */
	@Override
	public EdcPermissionScope fetchEdcPermissionScopeByUuidAndGroupId(
		String uuid, long groupId) {

		return edcPermissionScopePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the edc permission scope with the primary key.
	 *
	 * @param permissionScopeId the primary key of the edc permission scope
	 * @return the edc permission scope
	 * @throws PortalException if a edc permission scope with the primary key could not be found
	 */
	@Override
	public EdcPermissionScope getEdcPermissionScope(long permissionScopeId)
		throws PortalException {

		return edcPermissionScopePersistence.findByPrimaryKey(
			permissionScopeId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			edcPermissionScopeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EdcPermissionScope.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("permissionScopeId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			edcPermissionScopeLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(EdcPermissionScope.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"permissionScopeId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			edcPermissionScopeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EdcPermissionScope.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("permissionScopeId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<EdcPermissionScope>() {

				@Override
				public void performAction(EdcPermissionScope edcPermissionScope)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, edcPermissionScope);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(EdcPermissionScope.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return edcPermissionScopeLocalService.deleteEdcPermissionScope(
			(EdcPermissionScope)persistedModel);
	}

	public BasePersistence<EdcPermissionScope> getBasePersistence() {
		return edcPermissionScopePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return edcPermissionScopePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the edc permission scopes matching the UUID and company.
	 *
	 * @param uuid the UUID of the edc permission scopes
	 * @param companyId the primary key of the company
	 * @return the matching edc permission scopes, or an empty list if no matches were found
	 */
	@Override
	public List<EdcPermissionScope> getEdcPermissionScopesByUuidAndCompanyId(
		String uuid, long companyId) {

		return edcPermissionScopePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of edc permission scopes matching the UUID and company.
	 *
	 * @param uuid the UUID of the edc permission scopes
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of edc permission scopes
	 * @param end the upper bound of the range of edc permission scopes (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching edc permission scopes, or an empty list if no matches were found
	 */
	@Override
	public List<EdcPermissionScope> getEdcPermissionScopesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<EdcPermissionScope> orderByComparator) {

		return edcPermissionScopePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the edc permission scope matching the UUID and group.
	 *
	 * @param uuid the edc permission scope's UUID
	 * @param groupId the primary key of the group
	 * @return the matching edc permission scope
	 * @throws PortalException if a matching edc permission scope could not be found
	 */
	@Override
	public EdcPermissionScope getEdcPermissionScopeByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return edcPermissionScopePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the edc permission scopes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of edc permission scopes
	 * @param end the upper bound of the range of edc permission scopes (not inclusive)
	 * @return the range of edc permission scopes
	 */
	@Override
	public List<EdcPermissionScope> getEdcPermissionScopes(int start, int end) {
		return edcPermissionScopePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of edc permission scopes.
	 *
	 * @return the number of edc permission scopes
	 */
	@Override
	public int getEdcPermissionScopesCount() {
		return edcPermissionScopePersistence.countAll();
	}

	/**
	 * Updates the edc permission scope in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionScopeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param edcPermissionScope the edc permission scope
	 * @return the edc permission scope that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EdcPermissionScope updateEdcPermissionScope(
		EdcPermissionScope edcPermissionScope) {

		return edcPermissionScopePersistence.update(edcPermissionScope);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			EdcPermissionScopeLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		edcPermissionScopeLocalService =
			(EdcPermissionScopeLocalService)aopProxy;

		_setLocalServiceUtilService(edcPermissionScopeLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EdcPermissionScopeLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EdcPermissionScope.class;
	}

	protected String getModelClassName() {
		return EdcPermissionScope.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				edcPermissionScopePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		EdcPermissionScopeLocalService edcPermissionScopeLocalService) {

		try {
			Field field =
				EdcPermissionScopeLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, edcPermissionScopeLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected EdcLockPersistence edcLockPersistence;

	@Reference
	protected EdcPermissionRolePersistence edcPermissionRolePersistence;

	@Reference
	protected EdcPermissionRoleAuditPersistence
		edcPermissionRoleAuditPersistence;

	protected EdcPermissionScopeLocalService edcPermissionScopeLocalService;

	@Reference
	protected EdcPermissionScopePersistence edcPermissionScopePersistence;

	@Reference
	protected EdcPermissionScopeAuditPersistence
		edcPermissionScopeAuditPersistence;

	@Reference
	protected ExperimentalGroupPersistence experimentalGroupPersistence;

	@Reference
	protected InstanceLinkPersistence instanceLinkPersistence;

	@Reference
	protected InstitutionPersistence institutionPersistence;

	@Reference
	protected InstResearcherPersistence instResearcherPersistence;

	@Reference
	protected MetaCodePersistence metaCodePersistence;

	@Reference
	protected MetaGroupPersistence metaGroupPersistence;

	@Reference
	protected ProjectPersistence projectPersistence;

	@Reference
	protected QueryLinkPersistence queryLinkPersistence;

	@Reference
	protected RandomizationPersistence randomizationPersistence;

	@Reference
	protected ResearcherPersistence researcherPersistence;

	@Reference
	protected SubjectPersistence subjectPersistence;

	@Reference
	protected SubjectVisitDefinitionPersistence
		subjectVisitDefinitionPersistence;

	@Reference
	protected VisitDefinitionPersistence visitDefinitionPersistence;

	@Reference
	protected VisitEventPersistence visitEventPersistence;

	@Reference
	protected VisitGroupPersistence visitGroupPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}