/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.service.base;

import com.dhsoft.edc.backend.model.EdcPermissionScopeAudit;
import com.dhsoft.edc.backend.service.EdcPermissionScopeAuditLocalService;
import com.dhsoft.edc.backend.service.EdcPermissionScopeAuditLocalServiceUtil;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionRoleAuditPersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionRolePersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionScopeAuditPersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionScopePersistence;
import com.dhsoft.edc.backend.service.persistence.ExperimentalGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.InstResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.InstanceLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.InstitutionPersistence;
import com.dhsoft.edc.backend.service.persistence.MetaCodePersistence;
import com.dhsoft.edc.backend.service.persistence.MetaGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.ProjectPersistence;
import com.dhsoft.edc.backend.service.persistence.QueryLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.RandomizationPersistence;
import com.dhsoft.edc.backend.service.persistence.ResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectVisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitEventPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitGroupPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the edc permission scope audit local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dhsoft.edc.backend.service.impl.EdcPermissionScopeAuditLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dhsoft.edc.backend.service.impl.EdcPermissionScopeAuditLocalServiceImpl
 * @generated
 */
public abstract class EdcPermissionScopeAuditLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, EdcPermissionScopeAuditLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EdcPermissionScopeAuditLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>EdcPermissionScopeAuditLocalServiceUtil</code>.
	 */

	/**
	 * Adds the edc permission scope audit to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionScopeAuditLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param edcPermissionScopeAudit the edc permission scope audit
	 * @return the edc permission scope audit that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EdcPermissionScopeAudit addEdcPermissionScopeAudit(
		EdcPermissionScopeAudit edcPermissionScopeAudit) {

		edcPermissionScopeAudit.setNew(true);

		return edcPermissionScopeAuditPersistence.update(
			edcPermissionScopeAudit);
	}

	/**
	 * Creates a new edc permission scope audit with the primary key. Does not add the edc permission scope audit to the database.
	 *
	 * @param auditScopeId the primary key for the new edc permission scope audit
	 * @return the new edc permission scope audit
	 */
	@Override
	@Transactional(enabled = false)
	public EdcPermissionScopeAudit createEdcPermissionScopeAudit(
		long auditScopeId) {

		return edcPermissionScopeAuditPersistence.create(auditScopeId);
	}

	/**
	 * Deletes the edc permission scope audit with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionScopeAuditLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditScopeId the primary key of the edc permission scope audit
	 * @return the edc permission scope audit that was removed
	 * @throws PortalException if a edc permission scope audit with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EdcPermissionScopeAudit deleteEdcPermissionScopeAudit(
			long auditScopeId)
		throws PortalException {

		return edcPermissionScopeAuditPersistence.remove(auditScopeId);
	}

	/**
	 * Deletes the edc permission scope audit from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionScopeAuditLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param edcPermissionScopeAudit the edc permission scope audit
	 * @return the edc permission scope audit that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EdcPermissionScopeAudit deleteEdcPermissionScopeAudit(
		EdcPermissionScopeAudit edcPermissionScopeAudit) {

		return edcPermissionScopeAuditPersistence.remove(
			edcPermissionScopeAudit);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			EdcPermissionScopeAudit.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return edcPermissionScopeAuditPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeAuditModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return edcPermissionScopeAuditPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeAuditModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return edcPermissionScopeAuditPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return edcPermissionScopeAuditPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return edcPermissionScopeAuditPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public EdcPermissionScopeAudit fetchEdcPermissionScopeAudit(
		long auditScopeId) {

		return edcPermissionScopeAuditPersistence.fetchByPrimaryKey(
			auditScopeId);
	}

	/**
	 * Returns the edc permission scope audit matching the UUID and group.
	 *
	 * @param uuid the edc permission scope audit's UUID
	 * @param groupId the primary key of the group
	 * @return the matching edc permission scope audit, or <code>null</code> if a matching edc permission scope audit could not be found
	 */
	@Override
	public EdcPermissionScopeAudit fetchEdcPermissionScopeAuditByUuidAndGroupId(
		String uuid, long groupId) {

		return edcPermissionScopeAuditPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the edc permission scope audit with the primary key.
	 *
	 * @param auditScopeId the primary key of the edc permission scope audit
	 * @return the edc permission scope audit
	 * @throws PortalException if a edc permission scope audit with the primary key could not be found
	 */
	@Override
	public EdcPermissionScopeAudit getEdcPermissionScopeAudit(long auditScopeId)
		throws PortalException {

		return edcPermissionScopeAuditPersistence.findByPrimaryKey(
			auditScopeId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			edcPermissionScopeAuditLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EdcPermissionScopeAudit.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditScopeId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			edcPermissionScopeAuditLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			EdcPermissionScopeAudit.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"auditScopeId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			edcPermissionScopeAuditLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EdcPermissionScopeAudit.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditScopeId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return edcPermissionScopeAuditLocalService.
			deleteEdcPermissionScopeAudit(
				(EdcPermissionScopeAudit)persistedModel);
	}

	public BasePersistence<EdcPermissionScopeAudit> getBasePersistence() {
		return edcPermissionScopeAuditPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return edcPermissionScopeAuditPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the edc permission scope audits matching the UUID and company.
	 *
	 * @param uuid the UUID of the edc permission scope audits
	 * @param companyId the primary key of the company
	 * @return the matching edc permission scope audits, or an empty list if no matches were found
	 */
	@Override
	public List<EdcPermissionScopeAudit>
		getEdcPermissionScopeAuditsByUuidAndCompanyId(
			String uuid, long companyId) {

		return edcPermissionScopeAuditPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of edc permission scope audits matching the UUID and company.
	 *
	 * @param uuid the UUID of the edc permission scope audits
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of edc permission scope audits
	 * @param end the upper bound of the range of edc permission scope audits (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching edc permission scope audits, or an empty list if no matches were found
	 */
	@Override
	public List<EdcPermissionScopeAudit>
		getEdcPermissionScopeAuditsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<EdcPermissionScopeAudit> orderByComparator) {

		return edcPermissionScopeAuditPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the edc permission scope audit matching the UUID and group.
	 *
	 * @param uuid the edc permission scope audit's UUID
	 * @param groupId the primary key of the group
	 * @return the matching edc permission scope audit
	 * @throws PortalException if a matching edc permission scope audit could not be found
	 */
	@Override
	public EdcPermissionScopeAudit getEdcPermissionScopeAuditByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return edcPermissionScopeAuditPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the edc permission scope audits.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.EdcPermissionScopeAuditModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of edc permission scope audits
	 * @param end the upper bound of the range of edc permission scope audits (not inclusive)
	 * @return the range of edc permission scope audits
	 */
	@Override
	public List<EdcPermissionScopeAudit> getEdcPermissionScopeAudits(
		int start, int end) {

		return edcPermissionScopeAuditPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of edc permission scope audits.
	 *
	 * @return the number of edc permission scope audits
	 */
	@Override
	public int getEdcPermissionScopeAuditsCount() {
		return edcPermissionScopeAuditPersistence.countAll();
	}

	/**
	 * Updates the edc permission scope audit in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionScopeAuditLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param edcPermissionScopeAudit the edc permission scope audit
	 * @return the edc permission scope audit that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EdcPermissionScopeAudit updateEdcPermissionScopeAudit(
		EdcPermissionScopeAudit edcPermissionScopeAudit) {

		return edcPermissionScopeAuditPersistence.update(
			edcPermissionScopeAudit);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			EdcPermissionScopeAuditLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		edcPermissionScopeAuditLocalService =
			(EdcPermissionScopeAuditLocalService)aopProxy;

		_setLocalServiceUtilService(edcPermissionScopeAuditLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EdcPermissionScopeAuditLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EdcPermissionScopeAudit.class;
	}

	protected String getModelClassName() {
		return EdcPermissionScopeAudit.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				edcPermissionScopeAuditPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		EdcPermissionScopeAuditLocalService
			edcPermissionScopeAuditLocalService) {

		try {
			Field field =
				EdcPermissionScopeAuditLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, edcPermissionScopeAuditLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected EdcPermissionRolePersistence edcPermissionRolePersistence;

	@Reference
	protected EdcPermissionRoleAuditPersistence
		edcPermissionRoleAuditPersistence;

	@Reference
	protected EdcPermissionScopePersistence edcPermissionScopePersistence;

	protected EdcPermissionScopeAuditLocalService
		edcPermissionScopeAuditLocalService;

	@Reference
	protected EdcPermissionScopeAuditPersistence
		edcPermissionScopeAuditPersistence;

	@Reference
	protected ExperimentalGroupPersistence experimentalGroupPersistence;

	@Reference
	protected InstanceLinkPersistence instanceLinkPersistence;

	@Reference
	protected InstitutionPersistence institutionPersistence;

	@Reference
	protected InstResearcherPersistence instResearcherPersistence;

	@Reference
	protected MetaCodePersistence metaCodePersistence;

	@Reference
	protected MetaGroupPersistence metaGroupPersistence;

	@Reference
	protected ProjectPersistence projectPersistence;

	@Reference
	protected QueryLinkPersistence queryLinkPersistence;

	@Reference
	protected RandomizationPersistence randomizationPersistence;

	@Reference
	protected ResearcherPersistence researcherPersistence;

	@Reference
	protected SubjectPersistence subjectPersistence;

	@Reference
	protected SubjectVisitDefinitionPersistence
		subjectVisitDefinitionPersistence;

	@Reference
	protected VisitDefinitionPersistence visitDefinitionPersistence;

	@Reference
	protected VisitEventPersistence visitEventPersistence;

	@Reference
	protected VisitGroupPersistence visitGroupPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}