/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.service.base;

import com.dhsoft.edc.backend.model.EdcPermissionRoleAudit;
import com.dhsoft.edc.backend.service.EdcPermissionRoleAuditLocalService;
import com.dhsoft.edc.backend.service.EdcPermissionRoleAuditLocalServiceUtil;
import com.dhsoft.edc.backend.service.persistence.EdcLockPersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionRoleAuditPersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionRolePersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionScopeAuditPersistence;
import com.dhsoft.edc.backend.service.persistence.EdcPermissionScopePersistence;
import com.dhsoft.edc.backend.service.persistence.ExperimentalGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.InstResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.InstanceLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.InstitutionPersistence;
import com.dhsoft.edc.backend.service.persistence.MetaCodePersistence;
import com.dhsoft.edc.backend.service.persistence.MetaGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.ProjectPersistence;
import com.dhsoft.edc.backend.service.persistence.QueryLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.RandomizationPersistence;
import com.dhsoft.edc.backend.service.persistence.ResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectVisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitEventPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitGroupPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the edc permission role audit local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dhsoft.edc.backend.service.impl.EdcPermissionRoleAuditLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dhsoft.edc.backend.service.impl.EdcPermissionRoleAuditLocalServiceImpl
 * @generated
 */
public abstract class EdcPermissionRoleAuditLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, EdcPermissionRoleAuditLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EdcPermissionRoleAuditLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>EdcPermissionRoleAuditLocalServiceUtil</code>.
	 */

	/**
	 * Adds the edc permission role audit to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionRoleAuditLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param edcPermissionRoleAudit the edc permission role audit
	 * @return the edc permission role audit that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EdcPermissionRoleAudit addEdcPermissionRoleAudit(
		EdcPermissionRoleAudit edcPermissionRoleAudit) {

		edcPermissionRoleAudit.setNew(true);

		return edcPermissionRoleAuditPersistence.update(edcPermissionRoleAudit);
	}

	/**
	 * Creates a new edc permission role audit with the primary key. Does not add the edc permission role audit to the database.
	 *
	 * @param auditRoleId the primary key for the new edc permission role audit
	 * @return the new edc permission role audit
	 */
	@Override
	@Transactional(enabled = false)
	public EdcPermissionRoleAudit createEdcPermissionRoleAudit(
		long auditRoleId) {

		return edcPermissionRoleAuditPersistence.create(auditRoleId);
	}

	/**
	 * Deletes the edc permission role audit with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionRoleAuditLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditRoleId the primary key of the edc permission role audit
	 * @return the edc permission role audit that was removed
	 * @throws PortalException if a edc permission role audit with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EdcPermissionRoleAudit deleteEdcPermissionRoleAudit(long auditRoleId)
		throws PortalException {

		return edcPermissionRoleAuditPersistence.remove(auditRoleId);
	}

	/**
	 * Deletes the edc permission role audit from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionRoleAuditLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param edcPermissionRoleAudit the edc permission role audit
	 * @return the edc permission role audit that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EdcPermissionRoleAudit deleteEdcPermissionRoleAudit(
		EdcPermissionRoleAudit edcPermissionRoleAudit) {

		return edcPermissionRoleAuditPersistence.remove(edcPermissionRoleAudit);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			EdcPermissionRoleAudit.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return edcPermissionRoleAuditPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.EdcPermissionRoleAuditModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return edcPermissionRoleAuditPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.EdcPermissionRoleAuditModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return edcPermissionRoleAuditPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return edcPermissionRoleAuditPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return edcPermissionRoleAuditPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public EdcPermissionRoleAudit fetchEdcPermissionRoleAudit(
		long auditRoleId) {

		return edcPermissionRoleAuditPersistence.fetchByPrimaryKey(auditRoleId);
	}

	/**
	 * Returns the edc permission role audit matching the UUID and group.
	 *
	 * @param uuid the edc permission role audit's UUID
	 * @param groupId the primary key of the group
	 * @return the matching edc permission role audit, or <code>null</code> if a matching edc permission role audit could not be found
	 */
	@Override
	public EdcPermissionRoleAudit fetchEdcPermissionRoleAuditByUuidAndGroupId(
		String uuid, long groupId) {

		return edcPermissionRoleAuditPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the edc permission role audit with the primary key.
	 *
	 * @param auditRoleId the primary key of the edc permission role audit
	 * @return the edc permission role audit
	 * @throws PortalException if a edc permission role audit with the primary key could not be found
	 */
	@Override
	public EdcPermissionRoleAudit getEdcPermissionRoleAudit(long auditRoleId)
		throws PortalException {

		return edcPermissionRoleAuditPersistence.findByPrimaryKey(auditRoleId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			edcPermissionRoleAuditLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EdcPermissionRoleAudit.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditRoleId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			edcPermissionRoleAuditLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			EdcPermissionRoleAudit.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"auditRoleId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			edcPermissionRoleAuditLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EdcPermissionRoleAudit.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditRoleId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return edcPermissionRoleAuditLocalService.deleteEdcPermissionRoleAudit(
			(EdcPermissionRoleAudit)persistedModel);
	}

	public BasePersistence<EdcPermissionRoleAudit> getBasePersistence() {
		return edcPermissionRoleAuditPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return edcPermissionRoleAuditPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the edc permission role audits matching the UUID and company.
	 *
	 * @param uuid the UUID of the edc permission role audits
	 * @param companyId the primary key of the company
	 * @return the matching edc permission role audits, or an empty list if no matches were found
	 */
	@Override
	public List<EdcPermissionRoleAudit>
		getEdcPermissionRoleAuditsByUuidAndCompanyId(
			String uuid, long companyId) {

		return edcPermissionRoleAuditPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of edc permission role audits matching the UUID and company.
	 *
	 * @param uuid the UUID of the edc permission role audits
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of edc permission role audits
	 * @param end the upper bound of the range of edc permission role audits (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching edc permission role audits, or an empty list if no matches were found
	 */
	@Override
	public List<EdcPermissionRoleAudit>
		getEdcPermissionRoleAuditsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<EdcPermissionRoleAudit> orderByComparator) {

		return edcPermissionRoleAuditPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the edc permission role audit matching the UUID and group.
	 *
	 * @param uuid the edc permission role audit's UUID
	 * @param groupId the primary key of the group
	 * @return the matching edc permission role audit
	 * @throws PortalException if a matching edc permission role audit could not be found
	 */
	@Override
	public EdcPermissionRoleAudit getEdcPermissionRoleAuditByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return edcPermissionRoleAuditPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the edc permission role audits.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dhsoft.edc.backend.model.impl.EdcPermissionRoleAuditModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of edc permission role audits
	 * @param end the upper bound of the range of edc permission role audits (not inclusive)
	 * @return the range of edc permission role audits
	 */
	@Override
	public List<EdcPermissionRoleAudit> getEdcPermissionRoleAudits(
		int start, int end) {

		return edcPermissionRoleAuditPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of edc permission role audits.
	 *
	 * @return the number of edc permission role audits
	 */
	@Override
	public int getEdcPermissionRoleAuditsCount() {
		return edcPermissionRoleAuditPersistence.countAll();
	}

	/**
	 * Updates the edc permission role audit in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EdcPermissionRoleAuditLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param edcPermissionRoleAudit the edc permission role audit
	 * @return the edc permission role audit that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EdcPermissionRoleAudit updateEdcPermissionRoleAudit(
		EdcPermissionRoleAudit edcPermissionRoleAudit) {

		return edcPermissionRoleAuditPersistence.update(edcPermissionRoleAudit);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			EdcPermissionRoleAuditLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		edcPermissionRoleAuditLocalService =
			(EdcPermissionRoleAuditLocalService)aopProxy;

		_setLocalServiceUtilService(edcPermissionRoleAuditLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EdcPermissionRoleAuditLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EdcPermissionRoleAudit.class;
	}

	protected String getModelClassName() {
		return EdcPermissionRoleAudit.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				edcPermissionRoleAuditPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		EdcPermissionRoleAuditLocalService edcPermissionRoleAuditLocalService) {

		try {
			Field field =
				EdcPermissionRoleAuditLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, edcPermissionRoleAuditLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected EdcLockPersistence edcLockPersistence;

	@Reference
	protected EdcPermissionRolePersistence edcPermissionRolePersistence;

	protected EdcPermissionRoleAuditLocalService
		edcPermissionRoleAuditLocalService;

	@Reference
	protected EdcPermissionRoleAuditPersistence
		edcPermissionRoleAuditPersistence;

	@Reference
	protected EdcPermissionScopePersistence edcPermissionScopePersistence;

	@Reference
	protected EdcPermissionScopeAuditPersistence
		edcPermissionScopeAuditPersistence;

	@Reference
	protected ExperimentalGroupPersistence experimentalGroupPersistence;

	@Reference
	protected InstanceLinkPersistence instanceLinkPersistence;

	@Reference
	protected InstitutionPersistence institutionPersistence;

	@Reference
	protected InstResearcherPersistence instResearcherPersistence;

	@Reference
	protected MetaCodePersistence metaCodePersistence;

	@Reference
	protected MetaGroupPersistence metaGroupPersistence;

	@Reference
	protected ProjectPersistence projectPersistence;

	@Reference
	protected QueryLinkPersistence queryLinkPersistence;

	@Reference
	protected RandomizationPersistence randomizationPersistence;

	@Reference
	protected ResearcherPersistence researcherPersistence;

	@Reference
	protected SubjectPersistence subjectPersistence;

	@Reference
	protected SubjectVisitDefinitionPersistence
		subjectVisitDefinitionPersistence;

	@Reference
	protected VisitDefinitionPersistence visitDefinitionPersistence;

	@Reference
	protected VisitEventPersistence visitEventPersistence;

	@Reference
	protected VisitGroupPersistence visitGroupPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}