/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dhsoft.edc.backend.service.base;

import com.dhsoft.edc.backend.model.InstanceLink;
import com.dhsoft.edc.backend.service.InstanceLinkService;
import com.dhsoft.edc.backend.service.InstanceLinkServiceUtil;
import com.dhsoft.edc.backend.service.persistence.AssignAuditPersistence;
import com.dhsoft.edc.backend.service.persistence.AssignInstitutionRolePersistence;
import com.dhsoft.edc.backend.service.persistence.AssignProjectScopePersistence;
import com.dhsoft.edc.backend.service.persistence.ExperimentalGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.InstResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.InstanceLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.InstitutionPersistence;
import com.dhsoft.edc.backend.service.persistence.MetaCodePersistence;
import com.dhsoft.edc.backend.service.persistence.MetaGroupPersistence;
import com.dhsoft.edc.backend.service.persistence.ProjectPersistence;
import com.dhsoft.edc.backend.service.persistence.QueryLinkPersistence;
import com.dhsoft.edc.backend.service.persistence.RandomizationPersistence;
import com.dhsoft.edc.backend.service.persistence.ResearcherPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectPersistence;
import com.dhsoft.edc.backend.service.persistence.SubjectVisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitDefinitionPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitEventPersistence;
import com.dhsoft.edc.backend.service.persistence.VisitGroupPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the instance link remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dhsoft.edc.backend.service.impl.InstanceLinkServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dhsoft.edc.backend.service.impl.InstanceLinkServiceImpl
 * @generated
 */
public abstract class InstanceLinkServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, InstanceLinkService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>InstanceLinkService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>InstanceLinkServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			InstanceLinkService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		instanceLinkService = (InstanceLinkService)aopProxy;

		_setServiceUtilService(instanceLinkService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return InstanceLinkService.class.getName();
	}

	protected Class<?> getModelClass() {
		return InstanceLink.class;
	}

	protected String getModelClassName() {
		return InstanceLink.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = instanceLinkPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		InstanceLinkService instanceLinkService) {

		try {
			Field field = InstanceLinkServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, instanceLinkService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AssignAuditPersistence assignAuditPersistence;

	@Reference
	protected AssignInstitutionRolePersistence assignInstitutionRolePersistence;

	@Reference
	protected AssignProjectScopePersistence assignProjectScopePersistence;

	@Reference
	protected ExperimentalGroupPersistence experimentalGroupPersistence;

	@Reference
	protected com.dhsoft.edc.backend.service.InstanceLinkLocalService
		instanceLinkLocalService;

	protected InstanceLinkService instanceLinkService;

	@Reference
	protected InstanceLinkPersistence instanceLinkPersistence;

	@Reference
	protected InstitutionPersistence institutionPersistence;

	@Reference
	protected InstResearcherPersistence instResearcherPersistence;

	@Reference
	protected MetaCodePersistence metaCodePersistence;

	@Reference
	protected MetaGroupPersistence metaGroupPersistence;

	@Reference
	protected ProjectPersistence projectPersistence;

	@Reference
	protected QueryLinkPersistence queryLinkPersistence;

	@Reference
	protected RandomizationPersistence randomizationPersistence;

	@Reference
	protected ResearcherPersistence researcherPersistence;

	@Reference
	protected SubjectPersistence subjectPersistence;

	@Reference
	protected SubjectVisitDefinitionPersistence
		subjectVisitDefinitionPersistence;

	@Reference
	protected VisitDefinitionPersistence visitDefinitionPersistence;

	@Reference
	protected VisitEventPersistence visitEventPersistence;

	@Reference
	protected VisitGroupPersistence visitGroupPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	@Reference
	protected com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService
		workflowInstanceLinkLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryService
		assetEntryService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetLinkLocalService
		assetLinkLocalService;

	@Reference
	protected com.liferay.ratings.kernel.service.RatingsStatsLocalService
		ratingsStatsLocalService;

	@Reference
	protected com.liferay.trash.kernel.service.TrashEntryLocalService
		trashEntryLocalService;

	@Reference
	protected com.liferay.trash.kernel.service.TrashEntryService
		trashEntryService;

	@Reference
	protected com.liferay.trash.kernel.service.TrashVersionLocalService
		trashVersionLocalService;

}